In [22]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats

In [32]:
df = pd.read_csv('Data/county_data_clean.csv').drop(columns='Unnamed: 0')

In [33]:
df

,state_fips_code,county_fips_code,5_digit_fips_code,state_abbreviation,name,premature_death,premature_death_black,premature_death_hispanic,premature_death_white,poor_or_fair_health,...,male_population_18_44,male_population_45_64,male_population_65,total_male_population,female_population_0_17,female_population_18_44,female_population_45_64,female_population_65,total_female_population,population_growth
0,0,0,0,US,United States,6900.630354,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,1000,AL,Alabama,9917.232898,NaN,NaN,NaN,0.214024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1001,AL,Autauga County,8824.057123,10471.252986,NaN,8706.658832,0.184111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,1003,AL,Baldwin County,7224.632160,10042.472874,3086.605695,7277.780727,0.180605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,1005,AL,Barbour County,9586.165037,11332.562909,NaN,7309.636719,0.257734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,56,37,56037,WY,Sweetwater County,7497.439952,NaN,6413.215910,7834.050381,0.153772,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3190,56,39,56039,WY,Teton County,3786.128226,NaN,NaN,NaN,0.121817,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3191,56,41,56041,WY,Uinta County,7790.302043,NaN,NaN,NaN,0.158858,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3192,56,43,56043,WY,Washakie County,5504.650970,NaN,NaN,NaN,0.161261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3193,56,45,56045,WY,Weston County,4991.168273,NaN,NaN,NaN,0.132375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The first step to take in our EDA was to determine what outliers exist, if any. The first round of outlier detection is looking at univariate outliers for each of the features using boxplots (so, not taking into account uninsured, the dependent variable).

In [30]:
indep_features_list = df.drop(columns=['uninsured']).columns.to_list()

for state in df.state_abbreviation.unique():
    #temp_df = df[df.state_abbreviation==state][indep_features_list]
    Q1 = df[df.state_abbreviation==state][indep_features_list].quantile(0.25)
    Q3 = df[df.state_abbreviation==state][indep_features_list].quantile(0.75)
    IQR = Q3 - Q1
    
    df[df.state_abbreviation==state][indep_features_list] = df[df.state_abbreviation==state][indep_features_list]\
    [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
       (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
    print("state of " + state, df[df.state_abbreviation==state][indep_features_list])

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of US    state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
0                0                 0                  0                 US

            name  premature_death  premature_death_black  \
0  United States      6900.630354                    NaN

   premature_death_hispanic  premature_death_white  poor_or_fair_health  ...  \
0                       NaN                    NaN                  NaN  ...

   male_population_18_44  male_population_45_64  male_population_65  \
0                    NaN                    NaN                 NaN

   total_male_population  female_population_0_17  female_population_18_44  \
0                    NaN                     NaN                      NaN

   female_population_45_64  female_population_65  total_female_population  \
0                      NaN                   NaN                      NaN

   population_growth
0                NaN

[1 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of AL     state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1                 1                 0               1000                 AL
2                 1                 1               1001                 AL
3                 1                 3               1003                 AL
4                 1                 5               1005                 AL
5                 1                 7               1007                 AL
..              ...               ...                ...                ...
64                1               125               1125                 AL
65                1               127               1127                 AL
66                1               129               1129                 AL
67                1               131               1131                 AL
68                1               133               1133                 AL

                 name  premature_death  premature_death_black  \
1             Alabama      9917.232898                    NaN
2      Autauga County      8824.057123           10471.252986
3      Baldwin County      7224.632160           10042.472874
4      Barbour County      9586.165037           11332.562909
5         Bibb County     11783.543675           14812.539280
..                ...              ...                    ...
64  Tuscaloosa County      8854.970748           10960.196550
65      Walker County     15487.512757           16851.219312
66  Washington County     13127.578046           14020.704480
67      Wilcox County     12067.316202           14474.489127
68     Winston County     10380.221806                    NaN

    premature_death_hispanic  premature_death_white  poor_or_fair_health  ...  \
1                        NaN                    NaN             0.214024  ...
2                        NaN            8706.658832             0.184111  ...
3                3086.605695            7277.780727             0.180605  ...
4                        NaN            7309.636719             0.257734  ...
5                        NaN           11327.563749             0.199969  ...
..                       ...                    ...                  ...  ...
64               5261.311017            8008.651971             0.208575  ...
65                       NaN           15712.784792             0.216301  ...
66                       NaN           12015.366179             0.227466  ...
67                       NaN            6698.552802             0.303712  ...
68                       NaN                    NaN             0.217809  ...

    male_population_18_44  male_population_45_64  male_population_65  \
1                     NaN                    NaN                 NaN
2                     NaN                    NaN                 NaN
3                     NaN                    NaN                 NaN
4                     NaN                    NaN                 NaN
5                     NaN                    NaN                 NaN
..                    ...                    ...                 ...
64                    NaN                    NaN                 NaN
65                    NaN                    NaN                 NaN
66                    NaN                    NaN                 NaN
67                    NaN                    NaN                 NaN
68                    NaN                    NaN                 NaN

    total_male_population  female_population_0_17  female_population_18_44  \
1                     NaN                     NaN                      NaN
2                     NaN                     NaN                      NaN
3                     NaN                     NaN                      NaN
4                     NaN                     NaN                      NaN
5                     NaN                     NaN                      NaN
..                    ...                     ...                      ...
64                    NaN                     NaN                      NaN
65                    NaN                     NaN                      NaN
66                    NaN                     NaN                      NaN
67                    NaN                     NaN                      NaN
68                    NaN                     NaN                      NaN

    female_population_45_64  female_population_65  total_female_population  \
1                       NaN                   NaN                      NaN
2                       NaN                   NaN                      NaN
3                       NaN                   NaN                      NaN
4                       NaN                   NaN                      NaN
5                       NaN                   NaN                      NaN
..                      ...                   ...                      ...
64                      NaN                   NaN                      NaN
65                      NaN                   NaN                      NaN
66                      NaN                   NaN                      NaN
67                      NaN                   NaN                      NaN
68                      NaN                   NaN                      NaN

    population_growth
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
..                ...
64                NaN
65                NaN
66                NaN
67                NaN
68                NaN

[68 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of AK     state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
69                2                 0               2000                 AK
70                2                13               2013                 AK
71                2                16               2016                 AK
72                2                20               2020                 AK
73                2                50               2050                 AK
74                2                60               2060                 AK
75                2                68               2068                 AK
76                2                70               2070                 AK
77                2                90               2090                 AK
78                2               100               2100                 AK
79                2               105               2105                 AK
80                2               110               2110                 AK
81                2               122               2122                 AK
82                2               130               2130                 AK
83                2               150               2150                 AK
84                2               158               2158                 AK
85                2               164               2164                 AK
86                2               170               2170                 AK
87                2               180               2180                 AK
88                2               185               2185                 AK
89                2               188               2188                 AK
90                2               195               2195                 AK
91                2               198               2198                 AK
92                2               220               2220                 AK
93                2               230               2230                 AK
94                2               240               2240                 AK
95                2               261               2261                 AK
96                2               275               2275                 AK
97                2               282               2282                 AK
98                2               290               2290                 AK

                                 name  premature_death  premature_death_black  \
69                             Alaska      8162.453456                    NaN
70             Aleutians East Borough              NaN                    NaN
71         Aleutians West Census Area      5043.518924                    NaN
72                  Anchorage Borough      7876.536065            9150.456196
73                 Bethel Census Area     14538.337213                    NaN
74                Bristol Bay Borough     16379.687283                    NaN
75                     Denali Borough              NaN                    NaN
76             Dillingham Census Area     14041.021652                    NaN
77       Fairbanks North Star Borough      6967.132067            6782.264612
78                     Haines Borough      4149.471471                    NaN
79          Hoonah-Angoon Census Area      7824.927522                    NaN
80                     Juneau Borough      7923.831393                    NaN
81            Kenai Peninsula Borough      7830.639129                    NaN
82          Ketchikan Gateway Borough      7149.653676                    NaN
83              Kodiak Island Borough      5196.805260                    NaN
84               Kusilvak Census Area     20346.044759                    NaN
85         Lake and Peninsula Borough     16719.375613                    NaN
86          Matanuska-Susitna Borough      7170.659493                    NaN
87                   Nome Census Area     13999.264726                    NaN
88                North Slope Borough     11148.861376                    NaN
89           Northwest Arctic Borough     16902.985093                    NaN
90             Petersburg Census Area      9433.088816                    NaN
91  Prince of Wales-Hyder Census Area     11628.029401                    NaN
92                      Sitka Borough      5987.631845                    NaN
93               Skagway Municipality              NaN                    NaN
94    Southeast Fairbanks Census Area      6378.087075                    NaN
95         Valdez-Cordova Census Area      6693.247509                    NaN
96                      Wrangell City      6286.724229                    NaN
97                    Yakutat Borough              NaN                    NaN
98          Yukon-Koyukuk Census Area     19307.389472                    NaN

    premature_death_hispanic  premature_death_white  poor_or_fair_health  ...  \
69                       NaN                    NaN             0.134379  ...
70                       NaN                    NaN             0.167410  ...
71                       NaN                    NaN             0.151764  ...
72               4572.069540            6512.625716             0.130347  ...
73                       NaN                    NaN             0.262706  ...
74                       NaN                    NaN             0.154541  ...
75                       NaN                    NaN             0.122006  ...
76                       NaN                    NaN             0.221208  ...
77               4087.121123            6039.443862             0.132091  ...
78                       NaN                    NaN             0.136558  ...
79                       NaN                    NaN             0.172805  ...
80                       NaN                    NaN             0.118662  ...
81                       NaN                    NaN             0.149072  ...
82                       NaN                    NaN             0.156319  ...
83                       NaN                    NaN             0.121540  ...
84                       NaN                    NaN             0.379484  ...
85                       NaN                    NaN             0.239735  ...
86               4688.567427            6655.970573             0.144683  ...
87                       NaN                    NaN             0.260237  ...
88                       NaN                    NaN             0.165958  ...
89                       NaN                    NaN             0.255592  ...
90                       NaN                    NaN             0.131575  ...
91                       NaN                    NaN             0.192957  ...
92                       NaN                    NaN             0.136203  ...
93                       NaN                    NaN             0.107298  ...
94                       NaN                    NaN             0.143083  ...
95                       NaN                    NaN             0.139844  ...
96                       NaN                    NaN             0.156253  ...
97                       NaN                    NaN             0.180997  ...
98                       NaN                    NaN             0.239782  ...

    male_population_18_44  male_population_45_64  male_population_65  \
69                    NaN                    NaN                 NaN
70                    NaN                    NaN                 NaN
71                    NaN                    NaN                 NaN
72                    NaN                    NaN                 NaN
73                    NaN                    NaN                 NaN
74                    NaN                    NaN                 NaN
75                    NaN                    NaN                 NaN
76                    NaN                    NaN                 NaN
77                    NaN                    NaN                 NaN
78                    NaN                    NaN                 NaN
79                    NaN                    NaN                 NaN
80                    NaN                    NaN                 NaN
81                    NaN                    NaN                 NaN
82                    NaN                    NaN                 NaN
83                    NaN                    NaN                 NaN
84                    NaN                    NaN                 NaN
85                    NaN                    NaN                 NaN
86                    NaN                    NaN                 NaN
87                    NaN                    NaN                 NaN
88                    NaN                    NaN                 NaN
89                    NaN                    NaN                 NaN
90                    NaN                    NaN                 NaN
91                    NaN                    NaN                 NaN
92                    NaN                    NaN                 NaN
93                    NaN                    NaN                 NaN
94                    NaN                    NaN                 NaN
95                    NaN                    NaN                 NaN
96                    NaN                    NaN                 NaN
97                    NaN                    NaN                 NaN
98                    NaN                    NaN                 NaN

    total_male_population  female_population_0_17  female_population_18_44  \
69                    NaN                     NaN                      NaN
70                    NaN                     NaN                      NaN
71                    NaN                     NaN                      NaN
72                    NaN                     NaN                      NaN
73                    NaN                     NaN                      NaN
74                    NaN                     NaN                      NaN
75                    NaN                     NaN                      NaN
76                    NaN                     NaN                      NaN
77                    NaN                     NaN                      NaN
78                    NaN                     NaN                      NaN
79                    NaN                     NaN                      NaN
80                    NaN                     NaN                      NaN
81                    NaN                     NaN                      NaN
82                    NaN                     NaN                      NaN
83                    NaN                     NaN                      NaN
84                    NaN                     NaN                      NaN
85                    NaN                     NaN                      NaN
86                    NaN                     NaN                      NaN
87                    NaN                     NaN                      NaN
88                    NaN                     NaN                      NaN
89                    NaN                     NaN                      NaN
90                    NaN                     NaN                      NaN
91                    NaN                     NaN                      NaN
92                    NaN                     NaN                      NaN
93                    NaN                     NaN                      NaN
94                    NaN                     NaN                      NaN
95                    NaN                     NaN                      NaN
96                    NaN                     NaN                      NaN
97                    NaN                     NaN                      NaN
98                    NaN                     NaN                      NaN

    female_population_45_64  female_population_65  total_female_population  \
69                      NaN                   NaN                      NaN
70                      NaN                   NaN                      NaN
71                      NaN                   NaN                      NaN
72                      NaN                   NaN                      NaN
73                      NaN                   NaN                      NaN
74                      NaN                   NaN                      NaN
75                      NaN                   NaN                      NaN
76                      NaN                   NaN                      NaN
77                      NaN                   NaN                      NaN
78                      NaN                   NaN                      NaN
79                      NaN                   NaN                      NaN
80                      NaN                   NaN                      NaN
81                      NaN                   NaN                      NaN
82                      NaN                   NaN                      NaN
83                      NaN                   NaN                      NaN
84                      NaN                   NaN                      NaN
85                      NaN                   NaN                      NaN
86                      NaN                   NaN                      NaN
87                      NaN                   NaN                      NaN
88                      NaN                   NaN                      NaN
89                      NaN                   NaN                      NaN
90                      NaN                   NaN                      NaN
91                      NaN                   NaN                      NaN
92                      NaN                   NaN                      NaN
93                      NaN                   NaN                      NaN
94                      NaN                   NaN                      NaN
95                      NaN                   NaN                      NaN
96                      NaN                   NaN                      NaN
97                      NaN                   NaN                      NaN
98                      NaN                   NaN                      NaN

    population_growth
69                NaN
70                NaN
71                NaN
72                NaN
73                NaN
74                NaN
75                NaN
76                NaN
77                NaN
78                NaN
79                NaN
80                NaN
81                NaN
82                NaN
83                NaN
84                NaN
85                NaN
86                NaN
87                NaN
88                NaN
89                NaN
90                NaN
91                NaN
92                NaN
93                NaN
94                NaN
95                NaN
96                NaN
97                NaN
98                NaN

[30 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of AZ      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
99                 4                 0               4000                 AZ
100                4                 1               4001                 AZ
101                4                 3               4003                 AZ
102                4                 5               4005                 AZ
103                4                 7               4007                 AZ
104                4                 9               4009                 AZ
105                4                11               4011                 AZ
106                4                12               4012                 AZ
107                4                13               4013                 AZ
108                4                15               4015                 AZ
109                4                17               4017                 AZ
110                4                19               4019                 AZ
111                4                21               4021                 AZ
112                4                23               4023                 AZ
113                4                25               4025                 AZ
114                4                27               4027                 AZ

                  name  premature_death  premature_death_black  \
99             Arizona      6981.691345                    NaN
100      Apache County     16294.298815                    NaN
101     Cochise County      7598.283620            5538.302294
102    Coconino County      8447.156279            8744.623980
103        Gila County     13956.748475                    NaN
104      Graham County      7833.688943                    NaN
105    Greenlee County      6963.086578                    NaN
106      La Paz County     13532.482868                    NaN
107    Maricopa County      6352.865845            9525.695641
108      Mohave County     10638.975113            7874.277032
109      Navajo County     12723.512277                    NaN
110        Pima County      7281.721710            9136.531904
111       Pinal County      6901.707361            8191.306245
112  Santa Cruz County      4892.288492                    NaN
113     Yavapai County      8042.676144            7702.095200
114        Yuma County      5834.212268            7116.428228

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
99                        NaN                    NaN             0.177577
100              10404.228851           10845.697132             0.261593
101               6367.909201            8684.752242             0.173963
102               5899.245486            5283.149261             0.159911
103              10225.564309           10560.953223             0.214607
104               7570.477754            7001.503105             0.213892
105               7368.316733            5823.283093             0.191635
106               6520.066275           15326.592785             0.224955
107               5501.687770            6197.326495             0.146343
108               6251.152877           11194.037128             0.208533
109               6454.826955            8454.105466             0.237944
110               6161.129324            7389.406025             0.160564
111               5667.691992            6566.406970             0.195743
112               4762.786302            6138.954026             0.253748
113               5998.772213            8364.841924             0.142813
114               4638.652301            7763.526502             0.259322

     ...  male_population_18_44  male_population_45_64  male_population_65  \
99   ...                    NaN                    NaN                 NaN
100  ...                    NaN                    NaN                 NaN
101  ...                    NaN                    NaN                 NaN
102  ...                    NaN                    NaN                 NaN
103  ...                    NaN                    NaN                 NaN
104  ...                    NaN                    NaN                 NaN
105  ...                    NaN                    NaN                 NaN
106  ...                    NaN                    NaN                 NaN
107  ...                    NaN                    NaN                 NaN
108  ...                    NaN                    NaN                 NaN
109  ...                    NaN                    NaN                 NaN
110  ...                    NaN                    NaN                 NaN
111  ...                    NaN                    NaN                 NaN
112  ...                    NaN                    NaN                 NaN
113  ...                    NaN                    NaN                 NaN
114  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
99                     NaN                     NaN                      NaN
100                    NaN                     NaN                      NaN
101                    NaN                     NaN                      NaN
102                    NaN                     NaN                      NaN
103                    NaN                     NaN                      NaN
104                    NaN                     NaN                      NaN
105                    NaN                     NaN                      NaN
106                    NaN                     NaN                      NaN
107                    NaN                     NaN                      NaN
108                    NaN                     NaN                      NaN
109                    NaN                     NaN                      NaN
110                    NaN                     NaN                      NaN
111                    NaN                     NaN                      NaN
112                    NaN                     NaN                      NaN
113                    NaN                     NaN                      NaN
114                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
99                       NaN                   NaN                      NaN
100                      NaN                   NaN                      NaN
101                      NaN                   NaN                      NaN
102                      NaN                   NaN                      NaN
103                      NaN                   NaN                      NaN
104                      NaN                   NaN                      NaN
105                      NaN                   NaN                      NaN
106                      NaN                   NaN                      NaN
107                      NaN                   NaN                      NaN
108                      NaN                   NaN                      NaN
109                      NaN                   NaN                      NaN
110                      NaN                   NaN                      NaN
111                      NaN                   NaN                      NaN
112                      NaN                   NaN                      NaN
113                      NaN                   NaN                      NaN
114                      NaN                   NaN                      NaN

     population_growth
99                 NaN
100                NaN
101                NaN
102                NaN
103                NaN
104                NaN
105                NaN
106                NaN
107                NaN
108                NaN
109                NaN
110                NaN
111                NaN
112                NaN
113                NaN
114                NaN

[16 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of AR      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
115                5                 0               5000                 AR
116                5                 1               5001                 AR
117                5                 3               5003                 AR
118                5                 5               5005                 AR
119                5                 7               5007                 AR
..               ...               ...                ...                ...
186                5               141               5141                 AR
187                5               143               5143                 AR
188                5               145               5145                 AR
189                5               147               5147                 AR
190                5               149               5149                 AR

                  name  premature_death  premature_death_black  \
115           Arkansas      9483.291218                    NaN
116    Arkansas County     11515.566309           12268.574383
117      Ashley County     10396.194773           15426.737210
118      Baxter County      9257.912334                    NaN
119      Benton County      6338.828691            5089.839351
..                 ...              ...                    ...
186   Van Buren County     10140.478223                    NaN
187  Washington County      7139.336779            9163.422412
188       White County      9650.479056           14134.028712
189    Woodruff County     11320.742105           11671.473417
190        Yell County     11020.463760                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
115                       NaN                    NaN             0.244723
116                       NaN           11923.719402             0.243595
117                       NaN            9132.897504             0.234931
118                       NaN                    NaN             0.202917
119               3314.464771            7040.880123             0.199078
..                        ...                    ...                  ...
186                       NaN                    NaN             0.213647
187               2788.813326            7513.753243             0.196730
188                       NaN            9620.406388             0.219365
189                       NaN           11797.657575             0.249086
190               5209.933729           12381.351405             0.245052

     ...  male_population_18_44  male_population_45_64  male_population_65  \
115  ...                    NaN                    NaN                 NaN
116  ...                    NaN                    NaN                 NaN
117  ...                    NaN                    NaN                 NaN
118  ...                    NaN                    NaN                 NaN
119  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
186  ...                    NaN                    NaN                 NaN
187  ...                    NaN                    NaN                 NaN
188  ...                    NaN                    NaN                 NaN
189  ...                    NaN                    NaN                 NaN
190  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
115                    NaN                     NaN                      NaN
116                    NaN                     NaN                      NaN
117                    NaN                     NaN                      NaN
118                    NaN                     NaN                      NaN
119                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
186                    NaN                     NaN                      NaN
187                    NaN                     NaN                      NaN
188                    NaN                     NaN                      NaN
189                    NaN                     NaN                      NaN
190                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
115                      NaN                   NaN                      NaN
116                      NaN                   NaN                      NaN
117                      NaN                   NaN                      NaN
118                      NaN                   NaN                      NaN
119                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
186                      NaN                   NaN                      NaN
187                      NaN                   NaN                      NaN
188                      NaN                   NaN                      NaN
189                      NaN                   NaN                      NaN
190                      NaN                   NaN                      NaN

     population_growth
115                NaN
116                NaN
117                NaN
118                NaN
119                NaN
..                 ...
186                NaN
187                NaN
188                NaN
189                NaN
190                NaN

[76 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of CA      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
191                6                 0               6000                 CA
192                6                 1               6001                 CA
193                6                 3               6003                 CA
194                6                 5               6005                 CA
195                6                 7               6007                 CA
196                6                 9               6009                 CA
197                6                11               6011                 CA
198                6                13               6013                 CA
199                6                15               6015                 CA
200                6                17               6017                 CA
201                6                19               6019                 CA
202                6                21               6021                 CA
203                6                23               6023                 CA
204                6                25               6025                 CA
205                6                27               6027                 CA
206                6                29               6029                 CA
207                6                31               6031                 CA
208                6                33               6033                 CA
209                6                35               6035                 CA
210                6                37               6037                 CA
211                6                39               6039                 CA
212                6                41               6041                 CA
213                6                43               6043                 CA
214                6                45               6045                 CA
215                6                47               6047                 CA
216                6                49               6049                 CA
217                6                51               6051                 CA
218                6                53               6053                 CA
219                6                55               6055                 CA
220                6                57               6057                 CA
221                6                59               6059                 CA
222                6                61               6061                 CA
223                6                63               6063                 CA
224                6                65               6065                 CA
225                6                67               6067                 CA
226                6                69               6069                 CA
227                6                71               6071                 CA
228                6                73               6073                 CA
229                6                75               6075                 CA
230                6                77               6077                 CA
231                6                79               6079                 CA
232                6                81               6081                 CA
233                6                83               6083                 CA
234                6                85               6085                 CA
235                6                87               6087                 CA
236                6                89               6089                 CA
237                6                91               6091                 CA
238                6                93               6093                 CA
239                6                95               6095                 CA
240                6                97               6097                 CA
241                6                99               6099                 CA
242                6               101               6101                 CA
243                6               103               6103                 CA
244                6               105               6105                 CA
245                6               107               6107                 CA
246                6               109               6109                 CA
247                6               111               6111                 CA
248                6               113               6113                 CA
249                6               115               6115                 CA

                       name  premature_death  premature_death_black  \
191              California      5264.359459                    NaN
192          Alameda County      4497.451781           10085.205383
193           Alpine County     35146.645203                    NaN
194           Amador County      6101.441276                    NaN
195            Butte County      7604.920265            7672.349382
196        Calaveras County      7329.345035                    NaN
197           Colusa County      5676.947661                    NaN
198     Contra Costa County      4643.071725            9198.428856
199        Del Norte County      8953.673110                    NaN
200        El Dorado County      5358.615983                    NaN
201           Fresno County      6944.910268           14207.408529
202            Glenn County      7566.306901                    NaN
203         Humboldt County      9087.166241           14312.063919
204         Imperial County      6040.029851            8521.593136
205             Inyo County      7913.340871                    NaN
206             Kern County      7822.443712           12496.391947
207            Kings County      6016.687013            5263.224681
208             Lake County     11578.018825           20455.995234
209           Lassen County      7294.800519                    NaN
210      Los Angeles County      5007.654971            9967.374392
211           Madera County      6643.203792            7056.026957
212            Marin County      3133.003305            6604.678285
213         Mariposa County      8610.428703                    NaN
214        Mendocino County      7756.274567                    NaN
215           Merced County      7117.500774           13497.076958
216            Modoc County     10361.559861                    NaN
217             Mono County      3935.125396                    NaN
218         Monterey County      5235.021523            6010.370883
219             Napa County      4547.882526            3445.726586
220           Nevada County      5712.776268                    NaN
221           Orange County      4158.295385            6219.531238
222           Placer County      4694.103575            4751.754049
223           Plumas County      8153.681384                    NaN
224        Riverside County      5777.981117            8513.689316
225       Sacramento County      6373.754544           10045.259581
226       San Benito County      5253.219930                    NaN
227   San Bernardino County      6709.359822           10668.449124
228        San Diego County      4611.350430            7656.381892
229    San Francisco County      4384.419376           13195.142782
230      San Joaquin County      7218.594399           13553.248558
231  San Luis Obispo County      5351.814750            3525.155856
232        San Mateo County      3469.797831            6414.302385
233    Santa Barbara County      5014.766945            7951.427642
234      Santa Clara County      3641.411394            6910.406001
235       Santa Cruz County      4699.148524            8358.011992
236           Shasta County      9004.601757            9904.903719
237           Sierra County      6497.394144                    NaN
238         Siskiyou County      9510.938321                    NaN
239           Solano County      6099.596116           10017.790724
240           Sonoma County      4822.955646            5467.095406
241       Stanislaus County      7247.984956           11702.091584
242           Sutter County      6973.209991            6327.520319
243           Tehama County      8122.455579                    NaN
244          Trinity County     11256.909302                    NaN
245           Tulare County      7303.142050           11603.491849
246         Tuolumne County      7653.113045                    NaN
247          Ventura County      4764.769764            6259.155758
248             Yolo County      5160.466687            7659.380982
249             Yuba County      9470.154220           13304.374716

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
191                       NaN                    NaN             0.175266
192               4219.739743            4343.441096             0.126865
193                       NaN                    NaN             0.169579
194               4350.225062            6633.374311             0.130682
195               5221.441399            8054.959309             0.162732
196               4782.556137            7674.705732             0.128432
197               4389.728744            6418.609321             0.194664
198               4000.865133            4572.802172             0.121434
199               3425.924626            9208.511364             0.175114
200               4154.959335            5778.024788             0.112931
201               6061.101534            7352.249653             0.241711
202               5442.812456            8871.421383             0.206870
203               6403.994580            8678.854071             0.164802
204               5142.690960           10010.706694             0.266998
205               7351.628990            6052.910796             0.141513
206               6254.935374            9368.209433             0.240440
207               5678.321496            6502.159035             0.217185
208               7846.908947           11799.559072             0.183435
209                       NaN                    NaN             0.153542
210               4558.827038            5109.289738             0.188094
211               5623.558113            8142.389715             0.228572
212               2702.290457            3248.306138             0.110284
213                       NaN                    NaN             0.139079
214               5412.085339            8391.857276             0.173876
215               5925.339368            8339.628039             0.246019
216                       NaN                    NaN             0.163343
217                       NaN                    NaN             0.142080
218               4995.778319            5366.603297             0.224479
219               3594.470845            5539.711146             0.140650
220               5229.123642            5757.480651             0.115877
221               3973.194233            4796.636631             0.152927
222               4020.561343            5003.995638             0.107369
223                       NaN                    NaN             0.137793
224               4777.491790            6836.149698             0.191615
225               5202.747263            6531.109012             0.154477
226               4662.070720            6390.744752             0.183479
227               5314.097238            8177.160055             0.197483
228               4021.591625            4896.227619             0.130695
229               4350.772124            4189.074888             0.118261
230               5838.135762            8142.005355             0.204122
231               4445.983595            5747.559972             0.131297
232               3270.209519            3762.560680             0.115260
233               4500.748164            5517.637823             0.176453
234               4272.186712            4082.756807             0.115807
235               4487.014831            4815.085702             0.163620
236               4973.880463            9227.348136             0.149393
237                       NaN                    NaN             0.135790
238               3989.990532           10655.202731             0.173119
239               4472.217056            6259.981571             0.148300
240               3764.456799            5177.615973             0.130199
241               5470.180324            8805.956419             0.188307
242               5161.061175            8854.436463             0.182411
243               4667.950865            9569.825923             0.187357
244                       NaN                    NaN             0.173542
245               6169.427043            9057.617216             0.266132
246               4866.226148            8631.714415             0.138436
247               4424.199336            5320.309800             0.149454
248               4417.387173            6007.758725             0.162209
249               5437.254898           10764.290553             0.181792

     ...  male_population_18_44  male_population_45_64  male_population_65  \
191  ...                    NaN                    NaN                 NaN
192  ...                    NaN                    NaN                 NaN
193  ...                    NaN                    NaN                 NaN
194  ...                    NaN                    NaN                 NaN
195  ...                    NaN                    NaN                 NaN
196  ...                    NaN                    NaN                 NaN
197  ...                    NaN                    NaN                 NaN
198  ...                    NaN                    NaN                 NaN
199  ...                    NaN                    NaN                 NaN
200  ...                    NaN                    NaN                 NaN
201  ...                    NaN                    NaN                 NaN
202  ...                    NaN                    NaN                 NaN
203  ...                    NaN                    NaN                 NaN
204  ...                    NaN                    NaN                 NaN
205  ...                    NaN                    NaN                 NaN
206  ...                    NaN                    NaN                 NaN
207  ...                    NaN                    NaN                 NaN
208  ...                    NaN                    NaN                 NaN
209  ...                    NaN                    NaN                 NaN
210  ...                    NaN                    NaN                 NaN
211  ...                    NaN                    NaN                 NaN
212  ...                    NaN                    NaN                 NaN
213  ...                    NaN                    NaN                 NaN
214  ...                    NaN                    NaN                 NaN
215  ...                    NaN                    NaN                 NaN
216  ...                    NaN                    NaN                 NaN
217  ...                    NaN                    NaN                 NaN
218  ...                    NaN                    NaN                 NaN
219  ...                    NaN                    NaN                 NaN
220  ...                    NaN                    NaN                 NaN
221  ...                    NaN                    NaN                 NaN
222  ...                    NaN                    NaN                 NaN
223  ...                    NaN                    NaN                 NaN
224  ...                    NaN                    NaN                 NaN
225  ...                    NaN                    NaN                 NaN
226  ...                    NaN                    NaN                 NaN
227  ...                    NaN                    NaN                 NaN
228  ...                    NaN                    NaN                 NaN
229  ...                    NaN                    NaN                 NaN
230  ...                    NaN                    NaN                 NaN
231  ...                    NaN                    NaN                 NaN
232  ...                    NaN                    NaN                 NaN
233  ...                    NaN                    NaN                 NaN
234  ...                    NaN                    NaN                 NaN
235  ...                    NaN                    NaN                 NaN
236  ...                    NaN                    NaN                 NaN
237  ...                    NaN                    NaN                 NaN
238  ...                    NaN                    NaN                 NaN
239  ...                    NaN                    NaN                 NaN
240  ...                    NaN                    NaN                 NaN
241  ...                    NaN                    NaN                 NaN
242  ...                    NaN                    NaN                 NaN
243  ...                    NaN                    NaN                 NaN
244  ...                    NaN                    NaN                 NaN
245  ...                    NaN                    NaN                 NaN
246  ...                    NaN                    NaN                 NaN
247  ...                    NaN                    NaN                 NaN
248  ...                    NaN                    NaN                 NaN
249  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
191                    NaN                     NaN                      NaN
192                    NaN                     NaN                      NaN
193                    NaN                     NaN                      NaN
194                    NaN                     NaN                      NaN
195                    NaN                     NaN                      NaN
196                    NaN                     NaN                      NaN
197                    NaN                     NaN                      NaN
198                    NaN                     NaN                      NaN
199                    NaN                     NaN                      NaN
200                    NaN                     NaN                      NaN
201                    NaN                     NaN                      NaN
202                    NaN                     NaN                      NaN
203                    NaN                     NaN                      NaN
204                    NaN                     NaN                      NaN
205                    NaN                     NaN                      NaN
206                    NaN                     NaN                      NaN
207                    NaN                     NaN                      NaN
208                    NaN                     NaN                      NaN
209                    NaN                     NaN                      NaN
210                    NaN                     NaN                      NaN
211                    NaN                     NaN                      NaN
212                    NaN                     NaN                      NaN
213                    NaN                     NaN                      NaN
214                    NaN                     NaN                      NaN
215                    NaN                     NaN                      NaN
216                    NaN                     NaN                      NaN
217                    NaN                     NaN                      NaN
218                    NaN                     NaN                      NaN
219                    NaN                     NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of CO      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
250                8                 0               8000                 CO
251                8                 1               8001                 CO
252                8                 3               8003                 CO
253                8                 5               8005                 CO
254                8                 7               8007                 CO
..               ...               ...                ...                ...
310                8               117               8117                 CO
311                8               119               8119                 CO
312                8               121               8121                 CO
313                8               123               8123                 CO
314                8               125               8125                 CO

                  name  premature_death  premature_death_black  \
250           Colorado      5887.236994                    NaN
251       Adams County      6436.163193            9518.023682
252     Alamosa County      8727.274129                    NaN
253    Arapahoe County      5344.289179            7629.044941
254   Archuleta County      5192.714494                    NaN
..                 ...              ...                    ...
310      Summit County      3364.877762                    NaN
311      Teller County      8389.027899                    NaN
312  Washington County      8047.807273                    NaN
313        Weld County      5886.340707            6714.568196
314        Yuma County      5828.766805                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
250                       NaN                    NaN             0.143188
251               5643.390911            6766.792394             0.148308
252               9773.674841            8386.120892             0.203566
253               4591.348140            5317.625073             0.119751
254                       NaN                    NaN             0.125862
..                        ...                    ...                  ...
310                       NaN                    NaN             0.102866
311                       NaN                    NaN             0.090574
312                       NaN                    NaN             0.124096
313               5695.113050            5940.324727             0.140077
314                       NaN                    NaN             0.148285

     ...  male_population_18_44  male_population_45_64  male_population_65  \
250  ...                    NaN                    NaN                 NaN
251  ...                    NaN                    NaN                 NaN
252  ...                    NaN                    NaN                 NaN
253  ...                    NaN                    NaN                 NaN
254  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
310  ...                    NaN                    NaN                 NaN
311  ...                    NaN                    NaN                 NaN
312  ...                    NaN                    NaN                 NaN
313  ...                    NaN                    NaN                 NaN
314  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
250                    NaN                     NaN                      NaN
251                    NaN                     NaN                      NaN
252                    NaN                     NaN                      NaN
253                    NaN                     NaN                      NaN
254                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
310                    NaN                     NaN                      NaN
311                    NaN                     NaN                      NaN
312                    NaN                     NaN                      NaN
313                    NaN                     NaN                      NaN
314                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
250                      NaN                   NaN                      NaN
251                      NaN                   NaN                      NaN
252                      NaN                   NaN                      NaN
253                      NaN                   NaN                      NaN
254                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
310                      NaN                   NaN                      NaN
311                      NaN                   NaN                      NaN
312                      NaN                   NaN                      NaN
313                      NaN                   NaN                      NaN
314                      NaN                   NaN                      NaN

     population_growth
250                NaN
251                NaN
252                NaN
253                NaN
254                NaN
..                 ...
310                NaN
311                NaN
312                NaN
313                NaN
314                NaN

[65 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of CT      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
315                9                 0               9000                 CT
316                9                 1               9001                 CT
317                9                 3               9003                 CT
318                9                 5               9005                 CT
319                9                 7               9007                 CT
320                9                 9               9009                 CT
321                9                11               9011                 CT
322                9                13               9013                 CT
323                9                15               9015                 CT

                  name  premature_death  premature_death_black  \
315        Connecticut      5581.043795                    NaN
316   Fairfield County      4478.412754            6976.947773
317    Hartford County      6001.875053            7869.195547
318  Litchfield County      5650.266195            7846.132298
319   Middlesex County      5433.804647            8456.457183
320   New Haven County      6179.252538            8778.712520
321  New London County      6229.708331            7548.213535
322     Tolland County      4664.369155            5724.481552
323     Windham County      6923.598080            7906.312761

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
315                       NaN                    NaN             0.138415
316               4113.762673            4349.104777             0.110722
317               6230.056930            5880.116308             0.128468
318               4103.902015            5632.177637             0.088349
319               4557.930140            5421.217383             0.101897
320               5080.232341            6192.170528             0.129225
321               4785.305083            6545.711554             0.121291
322               3068.092066            5047.299458             0.097589
323               5751.942515            7121.491806             0.128612

     ...  male_population_18_44  male_population_45_64  male_population_65  \
315  ...                    NaN                    NaN                 NaN
316  ...                    NaN                    NaN                 NaN
317  ...                    NaN                    NaN                 NaN
318  ...                    NaN                    NaN                 NaN
319  ...                    NaN                    NaN                 NaN
320  ...                    NaN                    NaN                 NaN
321  ...                    NaN                    NaN                 NaN
322  ...                    NaN                    NaN                 NaN
323  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
315                    NaN                     NaN                      NaN
316                    NaN                     NaN                      NaN
317                    NaN                     NaN                      NaN
318                    NaN                     NaN                      NaN
319                    NaN                     NaN                      NaN
320                    NaN                     NaN                      NaN
321                    NaN                     NaN                      NaN
322                    NaN                     NaN                      NaN
323                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
315                      NaN                   NaN                      NaN
316                      NaN                   NaN                      NaN
317                      NaN                   NaN                      NaN
318                      NaN                   NaN                      NaN
319                      NaN                   NaN                      NaN
320                      NaN                   NaN                      NaN
321                      NaN                   NaN                      NaN
322                      NaN                   NaN                      NaN
323                      NaN                   NaN                      NaN

     population_growth
315                NaN
316                NaN
317                NaN
318                NaN
319                NaN
320                NaN
321                NaN
322                NaN
323                NaN

[9 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of DE      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
324               10                 0              10000                 DE
325               10                 1              10001                 DE
326               10                 3              10003                 DE
327               10                 5              10005                 DE

                  name  premature_death  premature_death_black  \
324           Delaware      7616.472475                    NaN
325        Kent County      7986.251722            8703.545148
326  New Castle County      7441.065362           10047.973565
327      Sussex County      7965.092389           10468.477485

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
324                       NaN                    NaN             0.158368
325               4841.351513            8116.104159             0.168718
326               4436.822157            7148.126084             0.145941
327               2659.713023            8281.859723             0.164062

     ...  male_population_18_44  male_population_45_64  male_population_65  \
324  ...                    NaN                    NaN                 NaN
325  ...                    NaN                    NaN                 NaN
326  ...                    NaN                    NaN                 NaN
327  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
324                    NaN                     NaN                      NaN
325                    NaN                     NaN                      NaN
326                    NaN                     NaN                      NaN
327                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
324                      NaN                   NaN                      NaN
325                      NaN                   NaN                      NaN
326                      NaN                   NaN                      NaN
327                      NaN                   NaN                      NaN

     population_growth
324                NaN
325                NaN
326                NaN
327                NaN

[4 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of DC      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
328               11                 0              11000                 DC
329               11                 1              11001                 DC

                     name  premature_death  premature_death_black  \
328  District of Columbia      8132.374322           13789.210618
329  District of Columbia      8132.374322           13789.210618

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
328               3810.711838            2594.916115             0.130251
329               3810.711838            2594.916115             0.130251

     ...  male_population_18_44  male_population_45_64  male_population_65  \
328  ...                    NaN                    NaN                 NaN
329  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
328                    NaN                     NaN                      NaN
329                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
328                      NaN                   NaN                      NaN
329                      NaN                   NaN                      NaN

     population_growth
328                NaN
329                NaN

[2 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of FL      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
330               12                 0              12000                 FL
331               12                 1              12001                 FL
332               12                 3              12003                 FL
333               12                 5              12005                 FL
334               12                 7              12007                 FL
..               ...               ...                ...                ...
393               12               125              12125                 FL
394               12               127              12127                 FL
395               12               129              12129                 FL
396               12               131              12131                 FL
397               12               133              12133                 FL

                  name  premature_death  premature_death_black  \
330            Florida      7214.381935                    NaN
331     Alachua County      6894.309260           10919.258776
332       Baker County      9204.036172            9194.437359
333         Bay County      9437.006902           12390.003786
334    Bradford County     11007.125453            8627.133478
..                 ...              ...                    ...
393       Union County     17539.704673           16696.649037
394     Volusia County      9278.156883           10658.656135
395     Wakulla County      7590.081322            6947.617355
396      Walton County      6995.008165            6347.418905
397  Washington County      9981.215633            9660.540999

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
330                       NaN                    NaN             0.185047
331               3389.610293            6479.439225             0.193087
332                       NaN            9485.552924             0.199261
333               3806.676941            9503.520121             0.186601
334                       NaN           12181.252621             0.203488
..                        ...                    ...                  ...
393              13727.471151           18526.533885             0.237378
394               5556.112387            9892.973083             0.185535
395                       NaN            8276.004306             0.169304
396                       NaN            7394.943432             0.185691
397                       NaN           10608.933545             0.230069

     ...  male_population_18_44  male_population_45_64  male_population_65  \
330  ...                    NaN                    NaN                 NaN
331  ...                    NaN                    NaN                 NaN
332  ...                    NaN                    NaN                 NaN
333  ...                    NaN                    NaN                 NaN
334  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
393  ...                    NaN                    NaN                 NaN
394  ...                    NaN                    NaN                 NaN
395  ...                    NaN                    NaN                 NaN
396  ...                    NaN                    NaN                 NaN
397  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
330                    NaN                     NaN                      NaN
331                    NaN                     NaN                      NaN
332                    NaN                     NaN                      NaN
333                    NaN                     NaN                      NaN
334                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
393                    NaN                     NaN                      NaN
394                    NaN                     NaN                      NaN
395                    NaN                     NaN                      NaN
396                    NaN                     NaN                      NaN
397                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
330                      NaN                   NaN                      NaN
331                      NaN                   NaN                      NaN
332                      NaN                   NaN                      NaN
333                      NaN                   NaN                      NaN
334                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
393                      NaN                   NaN                      NaN
394                      NaN                   NaN                      NaN
395                      NaN                   NaN                      NaN
396                      NaN                   NaN                      NaN
397                      NaN                   NaN                      NaN

     population_growth
330                NaN
331                NaN
332                NaN
333                NaN
334                NaN
..                 ...
393                NaN
394                NaN
395                NaN
396                NaN
397                NaN

[68 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of GA      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
398               13                 0              13000                 GA
399               13                 1              13001                 GA
400               13                 3              13003                 GA
401               13                 5              13005                 GA
402               13                 7              13007                 GA
..               ...               ...                ...                ...
553               13               313              13313                 GA
554               13               315              13315                 GA
555               13               317              13317                 GA
556               13               319              13319                 GA
557               13               321              13321                 GA

                 name  premature_death  premature_death_black  \
398           Georgia      7718.314464                    NaN
399    Appling County     10749.968790           13064.558525
400   Atkinson County     10902.115783           15940.755311
401      Bacon County     11414.503045           17049.861973
402      Baker County     11668.528300           10261.772350
..                ...              ...                    ...
553  Whitfield County      7250.025672           10516.912577
554     Wilcox County      9848.361489           10509.359609
555     Wilkes County     11742.466460           14371.305498
556  Wilkinson County     11552.621976           13224.026470
557      Worth County      9847.799946           11241.095830

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
398                       NaN                    NaN             0.188002
399                       NaN           10749.439170             0.208603
400                       NaN           11917.416439             0.267664
401                       NaN           11364.007285             0.191576
402                       NaN           14480.894837             0.185125
..                        ...                    ...                  ...
553               3191.504658            9028.991833             0.227075
554                       NaN            9487.963905             0.208557
555                       NaN           11052.463538             0.225550
556                       NaN           10997.351617             0.198821
557                       NaN            9506.589861             0.175496

     ...  male_population_18_44  male_population_45_64  male_population_65  \
398  ...                    NaN                    NaN                 NaN
399  ...                    NaN                    NaN                 NaN
400  ...                    NaN                    NaN                 NaN
401  ...                    NaN                    NaN                 NaN
402  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
553  ...                    NaN                    NaN                 NaN
554  ...                    NaN                    NaN                 NaN
555  ...                    NaN                    NaN                 NaN
556  ...                    NaN                    NaN                 NaN
557  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
398                    NaN                     NaN                      NaN
399                    NaN                     NaN                      NaN
400                    NaN                     NaN                      NaN
401                    NaN                     NaN                      NaN
402                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
553                    NaN                     NaN                      NaN
554                    NaN                     NaN                      NaN
555                    NaN                     NaN                      NaN
556                    NaN                     NaN                      NaN
557                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
398                      NaN                   NaN                      NaN
399                      NaN                   NaN                      NaN
400                      NaN                   NaN                      NaN
401                      NaN                   NaN                      NaN
402                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
553                      NaN                   NaN                      NaN
554                      NaN                   NaN                      NaN
555                      NaN                   NaN                      NaN
556                      NaN                   NaN                      NaN
557                      NaN                   NaN                      NaN

     population_growth
398                NaN
399                NaN
400                NaN
401                NaN
402                NaN
..                 ...
553                NaN
554                NaN
555                NaN
556                NaN
557                NaN

[160 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of HI      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
558               15                 0              15000                 HI
559               15                 1              15001                 HI
560               15                 3              15003                 HI
561               15                 5              15005                 HI
562               15                 7              15007                 HI
563               15                 9              15009                 HI

                name  premature_death  premature_death_black  \
558           Hawaii      5753.118030                    NaN
559    Hawaii County      7307.576588            5437.639225
560  Honolulu County      5444.991448            6111.914561
561   Kalawao County              NaN                    NaN
562     Kauai County      6184.329279                    NaN
563      Maui County      5800.818635            7034.573273

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
558                       NaN                    NaN             0.140452
559               8105.823589            7190.683504             0.152508
560               5937.566269            5072.865704             0.123349
561                       NaN                    NaN             0.140171
562               6457.470303            5949.049314             0.127295
563               5410.955961            6291.669152             0.128272

     ...  male_population_18_44  male_population_45_64  male_population_65  \
558  ...                    NaN                    NaN                 NaN
559  ...                    NaN                    NaN                 NaN
560  ...                    NaN                    NaN                 NaN
561  ...                    NaN                    NaN                 NaN
562  ...                    NaN                    NaN                 NaN
563  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
558                    NaN                     NaN                      NaN
559                    NaN                     NaN                      NaN
560                    NaN                     NaN                      NaN
561                    NaN                     NaN                      NaN
562                    NaN                     NaN                      NaN
563                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
558                      NaN                   NaN                      NaN
559                      NaN                   NaN                      NaN
560                      NaN                   NaN                      NaN
561                      NaN                   NaN                      NaN
562                      NaN                   NaN                      NaN
563                      NaN                   NaN                      NaN

     population_growth
558                NaN
559                NaN
560                NaN
561                NaN
562                NaN
563                NaN

[6 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of ID      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
564               16                 0              16000                 ID
565               16                 1              16001                 ID
566               16                 3              16003                 ID
567               16                 5              16005                 ID
568               16                 7              16007                 ID
569               16                 9              16009                 ID
570               16                11              16011                 ID
571               16                13              16013                 ID
572               16                15              16015                 ID
573               16                17              16017                 ID
574               16                19              16019                 ID
575               16                21              16021                 ID
576               16                23              16023                 ID
577               16                25              16025                 ID
578               16                27              16027                 ID
579               16                29              16029                 ID
580               16                31              16031                 ID
581               16                33              16033                 ID
582               16                35              16035                 ID
583               16                37              16037                 ID
584               16                39              16039                 ID
585               16                41              16041                 ID
586               16                43              16043                 ID
587               16                45              16045                 ID
588               16                47              16047                 ID
589               16                49              16049                 ID
590               16                51              16051                 ID
591               16                53              16053                 ID
592               16                55              16055                 ID
593               16                57              16057                 ID
594               16                59              16059                 ID
595               16                61              16061                 ID
596               16                63              16063                 ID
597               16                65              16065                 ID
598               16                67              16067                 ID
599               16                69              16069                 ID
600               16                71              16071                 ID
601               16                73              16073                 ID
602               16                75              16075                 ID
603               16                77              16077                 ID
604               16                79              16079                 ID
605               16                81              16081                 ID
606               16                83              16083                 ID
607               16                85              16085                 ID
608               16                87              16087                 ID

                  name  premature_death  premature_death_black  \
564              Idaho      6250.783415                    NaN
565         Ada County      5027.391209             5507.03702
566       Adams County      4468.643114                    NaN
567     Bannock County      7926.158636                    NaN
568   Bear Lake County      6419.935083                    NaN
569     Benewah County      9976.874055                    NaN
570     Bingham County      8552.450869                    NaN
571      Blaine County      4393.597818                    NaN
572       Boise County      5420.377641                    NaN
573      Bonner County      6786.292443                    NaN
574  Bonneville County      7201.737625                    NaN
575    Boundary County      5957.458581                    NaN
576       Butte County      7564.326394                    NaN
577       Camas County              NaN                    NaN
578      Canyon County      6168.560821                    NaN
579     Caribou County      7552.154699                    NaN
580      Cassia County      8891.044975                    NaN
581       Clark County              NaN                    NaN
582  Clearwater County     10805.846793                    NaN
583      Custer County      7808.043342                    NaN
584      Elmore County      6673.202745                    NaN
585    Franklin County      7444.100912                    NaN
586     Fremont County      5974.224636                    NaN
587         Gem County      7629.151992                    NaN
588     Gooding County      9729.675188                    NaN
589       Idaho County      7522.927219                    NaN
590   Jefferson County      5473.337257                    NaN
591      Jerome County      7635.392911                    NaN
592    Kootenai County      6023.056420                    NaN
593       Latah County      4893.079472                    NaN
594       Lemhi County      9074.297406                    NaN
595       Lewis County      6763.805783                    NaN
596     Lincoln County      5202.947591                    NaN
597     Madison County      4132.659000                    NaN
598    Minidoka County      7117.233956                    NaN
599   Nez Perce County      7020.859971                    NaN
600      Oneida County      5419.443155                    NaN
601      Owyhee County     10431.865365                    NaN
602     Payette County      7789.429211                    NaN
603       Power County      7459.439957                    NaN
604    Shoshone County      9638.359972                    NaN
605       Teton County      4021.813425                    NaN
606  Twin Falls County      7208.888850                    NaN
607      Valley County      6216.894381                    NaN
608  Washington County      5518.215736                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
564                       NaN                    NaN             0.152998
565               4153.355663            5148.146961             0.116468
566                       NaN                    NaN             0.162673
567               6879.594921            7515.080674             0.169050
568                       NaN                    NaN             0.142714
569                       NaN                    NaN             0.164596
570               6250.621592            8258.954738             0.190418
571                       NaN                    NaN             0.136130
572                       NaN                    NaN             0.140786
573                       NaN                    NaN             0.127038
574               3823.219936            7714.218329             0.150190
575                       NaN                    NaN             0.161945
576                       NaN                    NaN             0.153451
577                       NaN                    NaN             0.178031
578               4613.613045            6730.302947             0.186066
579                       NaN                    NaN             0.133991
580               9223.811448            8670.200212             0.181063
581                       NaN                    NaN             0.274661
582                       NaN                    NaN             0.147455
583                       NaN                    NaN             0.146662
584                       NaN                    NaN             0.169114
585                       NaN                    NaN             0.143428
586                       NaN                    NaN             0.157024
587                       NaN                    NaN             0.191401
588               8310.690738            9648.836386             0.189429
589                       NaN                    NaN             0.144740
590                       NaN                    NaN             0.151114
591               5043.023422            8902.898771             0.181494
592               3868.799563            6140.440194             0.153643
593                       NaN                    NaN             0.139936
594                       NaN                    NaN             0.168360
595                       NaN                    NaN             0.159046
596                       NaN                    NaN             0.189254
597                       NaN                    NaN             0.180486
598               6348.771678            7205.803606             0.202761
599                       NaN                    NaN             0.153017
600                       NaN                    NaN             0.141405
601                       NaN                    NaN             0.207558
602                       NaN                    NaN             0.182734
603                       NaN                    NaN             0.208248
604                       NaN                    NaN             0.160245
605                       NaN                    NaN             0.137878
606               4146.198006            7756.134528             0.158028
607                       NaN                    NaN             0.130795
608                       NaN                    NaN             0.199429

     ...  male_population_18_44  male_population_45_64  male_population_65  \
564  ...                    NaN                    NaN                 NaN
565  ...                    NaN                    NaN                 NaN
566  ...                    NaN                    NaN                 NaN
567  ...                    NaN                    NaN                 NaN
568  ...                    NaN                    NaN                 NaN
569  ...                    NaN                    NaN                 NaN
570  ...                    NaN                    NaN                 NaN
571  ...                    NaN                    NaN                 NaN
572  ...                    NaN                    NaN                 NaN
573  ...                    NaN                    NaN                 NaN
574  ...                    NaN                    NaN                 NaN
575  ...                    NaN                    NaN                 NaN
576  ...                    NaN                    NaN                 NaN
577  ...                    NaN                    NaN                 NaN
578  ...                    NaN                    NaN                 NaN
579  ...                    NaN                    NaN                 NaN
580  ...                    NaN                    NaN                 NaN
581  ...                    NaN                    NaN                 NaN
582  ...                    NaN                    NaN                 NaN
583  ...                    NaN                    NaN                 NaN
584  ...                    NaN                    NaN                 NaN
585  ...                    NaN                    NaN                 NaN
586  ...                    NaN                    NaN                 NaN
587  ...                    NaN                    NaN                 NaN
588  ...                    NaN                    NaN                 NaN
589  ...                    NaN                    NaN                 NaN
590  ...                    NaN                    NaN                 NaN
591  ...                    NaN                    NaN                 NaN
592  ...                    NaN                    NaN                 NaN
593  ...                    NaN                    NaN                 NaN
594  ...                    NaN                    NaN                 NaN
595  ...                    NaN                    NaN                 NaN
596  ...                    NaN                    NaN                 NaN
597  ...                    NaN                    NaN                 NaN
598  ...                    NaN                    NaN                 NaN
599  ...                    NaN                    NaN                 NaN
600  ...                    NaN                    NaN                 NaN
601  ...                    NaN                    NaN                 NaN
602  ...                    NaN                    NaN                 NaN
603  ...                    NaN                    NaN                 NaN
604  ...                    NaN                    NaN                 NaN
605  ...                    NaN                    NaN                 NaN
606  ...                    NaN                    NaN                 NaN
607  ...                    NaN                    NaN                 NaN
608  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
564                    NaN                     NaN                      NaN
565                    NaN                     NaN                      NaN
566                    NaN                     NaN                      NaN
567                    NaN                     NaN                      NaN
568                    NaN                     NaN                      NaN
569                    NaN                     NaN                      NaN
570                    NaN                     NaN                      NaN
571                    NaN                     NaN                      NaN
572                    NaN                     NaN                      NaN
573                    NaN                     NaN                      NaN
574                    NaN                     NaN                      NaN
575                    NaN                     NaN                      NaN
576                    NaN                     NaN                      NaN
577                    NaN                     NaN                      NaN
578                    NaN                     NaN                      NaN
579                    NaN                     NaN                      NaN
580                    NaN                     NaN                      NaN
581                    NaN                     NaN                      NaN
582                    NaN                     NaN                      NaN
583                    NaN                     NaN                      NaN
584                    NaN                     NaN                      NaN
585                    NaN                     NaN                      NaN
586                    NaN                     NaN                      NaN
587                    NaN                     NaN                      NaN
588                    NaN                     NaN                      NaN
589                    NaN                     NaN                      NaN
590                    NaN                     NaN                      NaN
591                    NaN                     NaN                      NaN
592                    NaN                     NaN                      NaN
593                    NaN                     NaN                      NaN
594                    NaN                     NaN                      NaN
595                    NaN                     NaN                      NaN
596                    NaN                     NaN                      NaN
597                    NaN                     NaN                      NaN
598                    NaN                     NaN                      NaN
599                    NaN                     NaN                      NaN
600                    NaN                     NaN                      NaN
601                    NaN                     NaN                      NaN
602                    NaN                     NaN                      NaN
603                    NaN                     NaN                      NaN
604                    NaN                     NaN                      NaN
605                    NaN                     NaN                      NaN
606                    NaN                     NaN                      NaN
607                    NaN                     NaN                      NaN
608                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
564                      NaN                   NaN                      NaN
565                      NaN                   NaN                      NaN
566                      NaN                   NaN                      NaN
567                      NaN                   NaN                      NaN
568                      NaN                   NaN                      NaN
569                      NaN                   NaN                      NaN
570                      NaN                   NaN                      NaN
571                      NaN                   NaN                      NaN
572                      NaN                   NaN                      NaN
573                      NaN                   NaN                      NaN
574                      NaN                   NaN                      NaN
575                      NaN                   NaN                      NaN
576                      NaN                   NaN                      NaN
577                      NaN                   NaN                      NaN
578                      NaN                   NaN                      NaN
579                      NaN                   NaN                      NaN
580                      NaN                   NaN                      NaN
581                      NaN                   NaN                      NaN
582                      NaN                   NaN                      NaN
583                      NaN                   NaN                      NaN
584                      NaN                   NaN                      NaN
585                      NaN                   NaN                      NaN
586                      NaN                   NaN                      NaN
587                      NaN                   NaN                      NaN
588                      NaN                   NaN                      NaN
589                      NaN                   NaN                      NaN
590                      NaN                   NaN                      NaN
591                      NaN                   NaN                      NaN
592                      NaN                   NaN                      NaN
593                      NaN                   NaN                      NaN
594                      NaN                   NaN                      NaN
595                      NaN                   NaN                      NaN
596                      NaN                   NaN                      NaN
597                      NaN                   NaN                      NaN
598                      NaN                   NaN                      NaN
599                      NaN                   NaN                      NaN
600                      NaN                   NaN                      NaN
601                      NaN                   NaN                      NaN
602                      NaN                   NaN                      NaN
603                      NaN                   NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]

state of IL      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
609               17                 0              17000                 IL
610               17                 1              17001                 IL
611               17                 3              17003                 IL
612               17                 5              17005                 IL
613               17                 7              17007                 IL
..               ...               ...                ...                ...
707               17               195              17195                 IL
708               17               197              17197                 IL
709               17               199              17199                 IL
710               17               201              17201                 IL
711               17               203              17203                 IL

                  name  premature_death  premature_death_black  \
609           Illinois      6567.712451                    NaN
610       Adams County      7333.632965           10112.973237
611   Alexander County     10354.508617           13732.970521
612        Bond County      7535.008095                    NaN
613       Boone County      5112.982317                    NaN
..                 ...              ...                    ...
707   Whiteside County      7314.578557                    NaN
708        Will County      5629.676323            8496.597372
709  Williamson County      7978.630028            8852.125243
710   Winnebago County      8988.889764           14603.350331
711    Woodford County      5691.463974                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
609                       NaN                    NaN             0.172349
610                       NaN            7317.031386             0.135849
611                       NaN            8682.661820             0.273164
612                       NaN                    NaN             0.167973
613               3123.531325            5683.938284             0.161571
..                        ...                    ...                  ...
707               3865.958409            7835.153335             0.161035
708               3770.702286            5770.149250             0.142692
709                       NaN            8127.762700             0.150355
710               5143.748455            8727.967058             0.174500
711                       NaN                    NaN             0.124907

     ...  male_population_18_44  male_population_45_64  male_population_65  \
609  ...                    NaN                    NaN                 NaN
610  ...                    NaN                    NaN                 NaN
611  ...                    NaN                    NaN                 NaN
612  ...                    NaN                    NaN                 NaN
613  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
707  ...                    NaN                    NaN                 NaN
708  ...                    NaN                    NaN                 NaN
709  ...                    NaN                    NaN                 NaN
710  ...                    NaN                    NaN                 NaN
711  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
609                    NaN                     NaN                      NaN
610                    NaN                     NaN                      NaN
611                    NaN                     NaN                      NaN
612                    NaN                     NaN                      NaN
613                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
707                    NaN                     NaN                      NaN
708                    NaN                     NaN                      NaN
709                    NaN                     NaN                      NaN
710                    NaN                     NaN                      NaN
711                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
609                      NaN                   NaN                      NaN
610                      NaN                   NaN                      NaN
611                      NaN                   NaN                      NaN
612                      NaN                   NaN                      NaN
613                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
707                      NaN                   NaN                      NaN
708                      NaN                   NaN                      NaN
709                      NaN                   NaN                      NaN
710                      NaN                   NaN                      NaN
711                      NaN                   NaN                      NaN

     population_growth
609                NaN
610                NaN
611                NaN
612                NaN
613                NaN
..                 ...
707                NaN
708                NaN
709                NaN
710                NaN
711                NaN

[103 rows x 155 columns]

/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of IN      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
712               18                 0              18000                 IN
713               18                 1              18001                 IN
714               18                 3              18003                 IN
715               18                 5              18005                 IN
716               18                 7              18007                 IN
..               ...               ...                ...                ...
800               18               175              18175                 IN
801               18               177              18177                 IN
802               18               179              18179                 IN
803               18               181              18181                 IN
804               18               183              18183                 IN

                   name  premature_death  premature_death_black  \
712             Indiana      8237.549540                    NaN
713        Adams County      6936.836661                    NaN
714        Allen County      8171.891308           13930.037999
715  Bartholomew County      7698.721319           17574.246190
716       Benton County      6087.502405                    NaN
..                  ...              ...                    ...
800   Washington County     10819.109233                    NaN
801        Wayne County     11323.993706           18016.521271
802        Wells County      6093.639070                    NaN
803        White County      7105.581534                    NaN
804      Whitley County      6498.819849                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
712                       NaN                    NaN             0.176724
713                       NaN                    NaN             0.178301
714               5500.040233            7535.144430             0.145957
715                       NaN            7851.090353             0.155316
716                       NaN                    NaN             0.170476
..                        ...                    ...                  ...
800                       NaN                    NaN             0.161626
801                       NaN           11108.116293             0.195841
802                       NaN                    NaN             0.148055
803                       NaN                    NaN             0.158184
804                       NaN                    NaN             0.135610

     ...  male_population_18_44  male_population_45_64  male_population_65  \
712  ...                    NaN                    NaN                 NaN
713  ...                    NaN                    NaN                 NaN
714  ...                    NaN                    NaN                 NaN
715  ...                    NaN                    NaN                 NaN
716  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
800  ...                    NaN                    NaN                 NaN
801  ...                    NaN                    NaN                 NaN
802  ...                    NaN                    NaN                 NaN
803  ...                    NaN                    NaN                 NaN
804  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
712                    NaN                     NaN                      NaN
713                    NaN                     NaN                      NaN
714                    NaN                     NaN                      NaN
715                    NaN                     NaN                      NaN
716                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
800                    NaN                     NaN                      NaN
801                    NaN                     NaN                      NaN
802                    NaN                     NaN                      NaN
803                    NaN                     NaN                      NaN
804                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
712                      NaN                   NaN                      NaN
713                      NaN                   NaN                      NaN
714                      NaN                   NaN                      NaN
715                      NaN                   NaN                      NaN
716                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
800                      NaN                   NaN                      NaN
801                      NaN                   NaN                      NaN
802                      NaN                   NaN                      NaN
803                      NaN                   NaN                      NaN
804                      NaN                   NaN                      NaN

     population_growth
712                NaN
713                NaN
714                NaN
715                NaN
716                NaN
..                 ...
800                NaN
801                NaN
802                NaN
803                NaN
804                NaN

[93 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of IA      state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
805               19                 0              19000                 IA
806               19                 1              19001                 IA
807               19                 3              19003                 IA
808               19                 5              19005                 IA
809               19                 7              19007                 IA
..               ...               ...                ...                ...
900               19               189              19189                 IA
901               19               191              19191                 IA
902               19               193              19193                 IA
903               19               195              19195                 IA
904               19               197              19197                 IA

                  name  premature_death  premature_death_black  \
805               Iowa      6165.904949                    NaN
806       Adair County      6458.887892                    NaN
807       Adams County      8880.545559                    NaN
808   Allamakee County      5651.431630                    NaN
809   Appanoose County      9713.517352                    NaN
..                 ...              ...                    ...
900   Winnebago County      6106.221065                    NaN
901  Winneshiek County      4458.226578                    NaN
902    Woodbury County      6965.499063              7960.6558
903       Worth County      7859.362938                    NaN
904      Wright County      6589.906662                    NaN

     premature_death_hispanic  premature_death_white  poor_or_fair_health  \
805                       NaN                    NaN             0.131404
806                       NaN                    NaN             0.117151
807                       NaN                    NaN             0.119337
808                       NaN                    NaN             0.124522
809                       NaN                    NaN             0.147220
..                        ...                    ...                  ...
900                       NaN                    NaN             0.126326
901                       NaN                    NaN             0.104195
902               3600.074847            7297.325547             0.159531
903                       NaN                    NaN             0.119533
904                       NaN                    NaN             0.150777

     ...  male_population_18_44  male_population_45_64  male_population_65  \
805  ...                    NaN                    NaN                 NaN
806  ...                    NaN                    NaN                 NaN
807  ...                    NaN                    NaN                 NaN
808  ...                    NaN                    NaN                 NaN
809  ...                    NaN                    NaN                 NaN
..   ...                    ...                    ...                 ...
900  ...                    NaN                    NaN                 NaN
901  ...                    NaN                    NaN                 NaN
902  ...                    NaN                    NaN                 NaN
903  ...                    NaN                    NaN                 NaN
904  ...                    NaN                    NaN                 NaN

     total_male_population  female_population_0_17  female_population_18_44  \
805                    NaN                     NaN                      NaN
806                    NaN                     NaN                      NaN
807                    NaN                     NaN                      NaN
808                    NaN                     NaN                      NaN
809                    NaN                     NaN                      NaN
..                     ...                     ...                      ...
900                    NaN                     NaN                      NaN
901                    NaN                     NaN                      NaN
902                    NaN                     NaN                      NaN
903                    NaN                     NaN                      NaN
904                    NaN                     NaN                      NaN

     female_population_45_64  female_population_65  total_female_population  \
805                      NaN                   NaN                      NaN
806                      NaN                   NaN                      NaN
807                      NaN                   NaN                      NaN
808                      NaN                   NaN                      NaN
809                      NaN                   NaN                      NaN
..                       ...                   ...                      ...
900                      NaN                   NaN                      NaN
901                      NaN                   NaN                      NaN
902                      NaN                   NaN                      NaN
903                      NaN                   NaN                      NaN
904                      NaN                   NaN                      NaN

     population_growth
805                NaN
806                NaN
807                NaN
808                NaN
809                NaN
..                 ...
900                NaN
901                NaN
902                NaN
903                NaN
904                NaN

[100 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of KS       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
905                20                 0              20000                 KS
906                20                 1              20001                 KS
907                20                 3              20003                 KS
908                20                 5              20005                 KS
909                20                 7              20007                 KS
...               ...               ...                ...                ...
1006               20               201              20201                 KS
1007               20               203              20203                 KS
1008               20               205              20205                 KS
1009               20               207              20207                 KS
1010               20               209              20209                 KS

                   name  premature_death  premature_death_black  \
905              Kansas      6943.728397                    NaN
906        Allen County      7302.075097                    NaN
907     Anderson County      8362.597883                    NaN
908     Atchison County      9029.329452           18098.331264
909       Barber County      8687.569385                    NaN
...                 ...              ...                    ...
1006  Washington County      6798.354410                    NaN
1007     Wichita County              NaN                    NaN
1008      Wilson County     10092.098027                    NaN
1009     Woodson County      7696.811479                    NaN
1010   Wyandotte County      9229.962872           13651.578745

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
905                        NaN                    NaN             0.150038
906                        NaN                    NaN             0.162085
907                        NaN                    NaN             0.151582
908                        NaN            8570.925102             0.161156
909                        NaN                    NaN             0.146081
...                        ...                    ...                  ...
1006                       NaN                    NaN             0.118815
1007                       NaN                    NaN             0.184874
1008                       NaN                    NaN             0.171435
1009                       NaN                    NaN             0.174282
1010               5761.903101            8751.118691             0.209758

      ...  male_population_18_44  male_population_45_64  male_population_65  \
905   ...                    NaN                    NaN                 NaN
906   ...                    NaN                    NaN                 NaN
907   ...                    NaN                    NaN                 NaN
908   ...                    NaN                    NaN                 NaN
909   ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1006  ...                    NaN                    NaN                 NaN
1007  ...                    NaN                    NaN                 NaN
1008  ...                    NaN                    NaN                 NaN
1009  ...                    NaN                    NaN                 NaN
1010  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
905                     NaN                     NaN                      NaN
906                     NaN                     NaN                      NaN
907                     NaN                     NaN                      NaN
908                     NaN                     NaN                      NaN
909                     NaN                     NaN                      NaN
...                     ...                     ...                      ...
1006                    NaN                     NaN                      NaN
1007                    NaN                     NaN                      NaN
1008                    NaN                     NaN                      NaN
1009                    NaN                     NaN                      NaN
1010                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
905                       NaN                   NaN                      NaN
906                       NaN                   NaN                      NaN
907                       NaN                   NaN                      NaN
908                       NaN                   NaN                      NaN
909                       NaN                   NaN                      NaN
...                       ...                   ...                      ...
1006                      NaN                   NaN                      NaN
1007                      NaN                   NaN                      NaN
1008                      NaN                   NaN                      NaN
1009                      NaN                   NaN                      NaN
1010                      NaN                   NaN                      NaN

      population_growth
905                 NaN
906                 NaN
907                 NaN
908                 NaN
909                 NaN
...                 ...
1006                NaN
1007                NaN
1008                NaN
1009                NaN
1010                NaN

[106 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of KY       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1011               21                 0              21000                 KY
1012               21                 1              21001                 KY
1013               21                 3              21003                 KY
1014               21                 5              21005                 KY
1015               21                 7              21007                 KY
...               ...               ...                ...                ...
1127               21               231              21231                 KY
1128               21               233              21233                 KY
1129               21               235              21235                 KY
1130               21               237              21237                 KY
1131               21               239              21239                 KY

                 name  premature_death  premature_death_black  \
1011         Kentucky      9715.625916                    NaN
1012     Adair County      9140.796987                    NaN
1013     Allen County     10513.474627                    NaN
1014  Anderson County      9655.723017                    NaN
1015   Ballard County      9656.848827                    NaN
...               ...              ...                    ...
1127     Wayne County     11380.924724                    NaN
1128   Webster County     12363.742283                    NaN
1129   Whitley County     15358.844751                    NaN
1130     Wolfe County     13456.757205                    NaN
1131  Woodford County      8546.713375            9514.954461

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1011                       NaN                    NaN             0.212539
1012                       NaN                    NaN             0.225437
1013                       NaN                    NaN             0.199336
1014                       NaN                    NaN             0.172630
1015                       NaN                    NaN             0.197271
...                        ...                    ...                  ...
1127                       NaN                    NaN             0.267728
1128                       NaN                    NaN             0.226991
1129                       NaN                    NaN             0.245360
1130                       NaN                    NaN             0.301096
1131                       NaN            8697.812029             0.166907

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1011  ...                    NaN                    NaN                 NaN
1012  ...                    NaN                    NaN                 NaN
1013  ...                    NaN                    NaN                 NaN
1014  ...                    NaN                    NaN                 NaN
1015  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1127  ...                    NaN                    NaN                 NaN
1128  ...                    NaN                    NaN                 NaN
1129  ...                    NaN                    NaN                 NaN
1130  ...                    NaN                    NaN                 NaN
1131  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1011                    NaN                     NaN                      NaN
1012                    NaN                     NaN                      NaN
1013                    NaN                     NaN                      NaN
1014                    NaN                     NaN                      NaN
1015                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1127                    NaN                     NaN                      NaN
1128                    NaN                     NaN                      NaN
1129                    NaN                     NaN                      NaN
1130                    NaN                     NaN                      NaN
1131                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1011                      NaN                   NaN                      NaN
1012                      NaN                   NaN                      NaN
1013                      NaN                   NaN                      NaN
1014                      NaN                   NaN                      NaN
1015                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1127                      NaN                   NaN                      NaN
1128                      NaN                   NaN                      NaN
1129                      NaN                   NaN                      NaN
1130                      NaN                   NaN                      NaN
1131                      NaN                   NaN                      NaN

      population_growth
1011                NaN
1012                NaN
1013                NaN
1014                NaN
1015                NaN
...                 ...
1127                NaN
1128                NaN
1129                NaN
1130                NaN
1131                NaN

[121 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of LA       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1132               22                 0              22000                 LA
1133               22                 1              22001                 LA
1134               22                 3              22003                 LA
1135               22                 5              22005                 LA
1136               22                 7              22007                 LA
...               ...               ...                ...                ...
1192               22               119              22119                 LA
1193               22               121              22121                 LA
1194               22               123              22123                 LA
1195               22               125              22125                 LA
1196               22               127              22127                 LA

                         name  premature_death  premature_death_black  \
1132                Louisiana      9532.277471                    NaN
1133            Acadia Parish     10194.322673           15525.216935
1134             Allen Parish      9691.701375            9766.089275
1135         Ascension Parish      6428.672344            8620.972506
1136        Assumption Parish      9191.690675           15070.130090
...                       ...              ...                    ...
1192           Webster Parish     11651.352878           12932.475591
1193  West Baton Rouge Parish      9240.727843           11004.544801
1194      West Carroll Parish     11279.404966           17224.846887
1195    West Feliciana Parish      8373.178725            9651.321368
1196              Winn Parish     11528.588730           10815.184797

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1132                       NaN                    NaN             0.210505
1133                       NaN            8947.167721             0.219611
1134                       NaN            9675.485750             0.188831
1135               2997.755625            6094.706857             0.161595
1136                       NaN            6629.340067             0.196123
...                        ...                    ...                  ...
1192                       NaN           10781.749256             0.212820
1193                       NaN            8585.426861             0.194852
1194                       NaN           10508.766126             0.209201
1195                       NaN            7499.831616             0.211103
1196                       NaN           12223.798241             0.231095

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1132  ...                    NaN                    NaN                 NaN
1133  ...                    NaN                    NaN                 NaN
1134  ...                    NaN                    NaN                 NaN
1135  ...                    NaN                    NaN                 NaN
1136  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1192  ...                    NaN                    NaN                 NaN
1193  ...                    NaN                    NaN                 NaN
1194  ...                    NaN                    NaN                 NaN
1195  ...                    NaN                    NaN                 NaN
1196  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1132                    NaN                     NaN                      NaN
1133                    NaN                     NaN                      NaN
1134                    NaN                     NaN                      NaN
1135                    NaN                     NaN                      NaN
1136                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1192                    NaN                     NaN                      NaN
1193                    NaN                     NaN                      NaN
1194                    NaN                     NaN                      NaN
1195                    NaN                     NaN                      NaN
1196                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1132                      NaN                   NaN                      NaN
1133                      NaN                   NaN                      NaN
1134                      NaN                   NaN                      NaN
1135                      NaN                   NaN                      NaN
1136                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1192                      NaN                   NaN                      NaN
1193                      NaN                   NaN                      NaN
1194                      NaN                   NaN                      NaN
1195                      NaN                   NaN                      NaN
1196                      NaN                   NaN                      NaN

      population_growth
1132                NaN
1133                NaN
1134                NaN
1135                NaN
1136                NaN
...                 ...
1192                NaN
1193                NaN
1194                NaN
1195                NaN
1196                NaN

[65 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of ME       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1197               23                 0              23000                 ME
1198               23                 1              23001                 ME
1199               23                 3              23003                 ME
1200               23                 5              23005                 ME
1201               23                 7              23007                 ME
1202               23                 9              23009                 ME
1203               23                11              23011                 ME
1204               23                13              23013                 ME
1205               23                15              23015                 ME
1206               23                17              23017                 ME
1207               23                19              23019                 ME
1208               23                21              23021                 ME
1209               23                23              23023                 ME
1210               23                25              23025                 ME
1211               23                27              23027                 ME
1212               23                29              23029                 ME
1213               23                31              23031                 ME

                     name  premature_death  premature_death_black  \
1197                Maine      6994.302193                    NaN
1198  Androscoggin County      7299.490847            6916.189354
1199     Aroostook County      8535.662491                    NaN
1200    Cumberland County      5766.190842            7210.920732
1201      Franklin County      7204.314805                    NaN
1202       Hancock County      6133.644393                    NaN
1203      Kennebec County      7321.661295                    NaN
1204          Knox County      7296.642194                    NaN
1205       Lincoln County      6575.870721                    NaN
1206        Oxford County      6731.998909                    NaN
1207     Penobscot County      7671.131627                    NaN
1208   Piscataquis County      8251.552900                    NaN
1209     Sagadahoc County      6545.277808                    NaN
1210      Somerset County      9128.257396                    NaN
1211         Waldo County      6892.109923                    NaN
1212    Washington County      9700.116351                    NaN
1213          York County      6865.483367                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1197                       NaN                    NaN             0.153903
1198                       NaN            7318.217799             0.143839
1199                       NaN                    NaN             0.184830
1200               3796.911239            5789.417853             0.100712
1201                       NaN                    NaN             0.136248
1202                       NaN                    NaN             0.123831
1203                       NaN                    NaN             0.139489
1204                       NaN                    NaN             0.107172
1205                       NaN                    NaN             0.100749
1206                       NaN                    NaN             0.145274
1207                       NaN                    NaN             0.141696
1208                       NaN                    NaN             0.159962
1209                       NaN                    NaN             0.099857
1210                       NaN                    NaN             0.155549
1211                       NaN                    NaN             0.145976
1212                       NaN                    NaN             0.147454
1213                       NaN                    NaN             0.128799

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1197  ...                    NaN                    NaN                 NaN
1198  ...                    NaN                    NaN                 NaN
1199  ...                    NaN                    NaN                 NaN
1200  ...                    NaN                    NaN                 NaN
1201  ...                    NaN                    NaN                 NaN
1202  ...                    NaN                    NaN                 NaN
1203  ...                    NaN                    NaN                 NaN
1204  ...                    NaN                    NaN                 NaN
1205  ...                    NaN                    NaN                 NaN
1206  ...                    NaN                    NaN                 NaN
1207  ...                    NaN                    NaN                 NaN
1208  ...                    NaN                    NaN                 NaN
1209  ...                    NaN                    NaN                 NaN
1210  ...                    NaN                    NaN                 NaN
1211  ...                    NaN                    NaN                 NaN
1212  ...                    NaN                    NaN                 NaN
1213  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1197                    NaN                     NaN                      NaN
1198                    NaN                     NaN                      NaN
1199                    NaN                     NaN                      NaN
1200                    NaN                     NaN                      NaN
1201                    NaN                     NaN                      NaN
1202                    NaN                     NaN                      NaN
1203                    NaN                     NaN                      NaN
1204                    NaN                     NaN                      NaN
1205                    NaN                     NaN                      NaN
1206                    NaN                     NaN                      NaN
1207                    NaN                     NaN                      NaN
1208                    NaN                     NaN                      NaN
1209                    NaN                     NaN                      NaN
1210                    NaN                     NaN                      NaN
1211                    NaN                     NaN                      NaN
1212                    NaN                     NaN                      NaN
1213                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1197                      NaN                   NaN                      NaN
1198                      NaN                   NaN                      NaN
1199                      NaN                   NaN                      NaN
1200                      NaN                   NaN                      NaN
1201                      NaN                   NaN                      NaN
1202                      NaN                   NaN                      NaN
1203                      NaN                   NaN                      NaN
1204                      NaN                   NaN                      NaN
1205                      NaN                   NaN                      NaN
1206                      NaN                   NaN                      NaN
1207                      NaN                   NaN                      NaN
1208                      NaN                   NaN                      NaN
1209                      NaN                   NaN                      NaN
1210                      NaN                   NaN                      NaN
1211                      NaN                   NaN                      NaN
1212                      NaN                   NaN                      NaN
1213                      NaN                   NaN                      NaN

      population_growth
1197                NaN
1198                NaN
1199                NaN
1200                NaN
1201                NaN
1202                NaN
1203                NaN
1204                NaN
1205                NaN
1206                NaN
1207                NaN
1208                NaN
1209                NaN
1210                NaN
1211                NaN
1212                NaN
1213                NaN

[17 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MD       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1214               24                 0              24000                 MD
1215               24                 1              24001                 MD
1216               24                 3              24003                 MD
1217               24                 5              24005                 MD
1218               24                 9              24009                 MD
1219               24                11              24011                 MD
1220               24                13              24013                 MD
1221               24                15              24015                 MD
1222               24                17              24017                 MD
1223               24                19              24019                 MD
1224               24                21              24021                 MD
1225               24                23              24023                 MD
1226               24                25              24025                 MD
1227               24                27              24027                 MD
1228               24                29              24029                 MD
1229               24                31              24031                 MD
1230               24                33              24033                 MD
1231               24                35              24035                 MD
1232               24                37              24037                 MD
1233               24                39              24039                 MD
1234               24                41              24041                 MD
1235               24                43              24043                 MD
1236               24                45              24045                 MD
1237               24                47              24047                 MD
1238               24               510              24510                 MD

                        name  premature_death  premature_death_black  \
1214                Maryland      7066.943924                    NaN
1215         Allegany County      9006.730637            6093.281089
1216     Anne Arundel County      6498.404193            7781.418231
1217        Baltimore County      7783.000141            8991.294203
1218          Calvert County      6799.986113            9390.713069
1219         Caroline County      8966.586407            9797.818318
1220          Carroll County      6327.990999            7245.422615
1221            Cecil County      9211.873665           13446.860827
1222          Charles County      7400.542115            7131.963620
1223       Dorchester County      9337.407328           12544.595811
1224        Frederick County      5736.571309            7624.081246
1225          Garrett County      7469.540069                    NaN
1226          Harford County      6476.822517            8936.884385
1227           Howard County      4221.617829            5572.509761
1228             Kent County      7078.957166           10375.590895
1229       Montgomery County      4099.393145            5799.647968
1230  Prince George's County      6862.371343            7963.575662
1231     Queen Anne's County      6893.349866           11990.888528
1232       St. Mary's County      6487.681612            8944.714868
1233         Somerset County     10811.405571           10903.351111
1234           Talbot County      6464.081535           10841.966031
1235       Washington County      8306.166606            9682.860579
1236         Wicomico County      8970.048055           11683.352924
1237        Worcester County      9472.276142           14497.178046
1238          Baltimore city     13243.912455           16049.660307

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1214                       NaN                    NaN             0.139370
1215                       NaN            9774.405791             0.174220
1216               3310.128684            6692.385837             0.111762
1217               3862.738158            7973.053634             0.127449
1218                       NaN            6506.893211             0.113396
1219                       NaN            9503.953967             0.177586
1220                       NaN            6449.680600             0.108126
1221               6172.576732            9127.522254             0.141756
1222               4202.353914            8238.192183             0.128894
1223                       NaN            8632.513331             0.179363
1224               2618.294293            6093.311308             0.117511
1225                       NaN                    NaN             0.163770
1226               3628.023632            6384.855058             0.134874
1227               2727.658716            4379.451331             0.093926
1228                       NaN            6918.764831             0.136750
1229               3396.903265            4137.092228             0.097455
1230               3963.925766            6534.715220             0.148422
1231                       NaN            6749.694528             0.112652
1232                       NaN            6306.149121             0.113329
1233                       NaN           11831.749326             0.223733
1234                       NaN            6139.552985             0.123378
1235                       NaN            8556.860898             0.146463
1236               6870.904889            8301.044083             0.164428
1237                       NaN            8552.999914             0.148701
1238               4662.459738            9476.321604             0.189357

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1214  ...                    NaN                    NaN                 NaN
1215  ...                    NaN                    NaN                 NaN
1216  ...                    NaN                    NaN                 NaN
1217  ...                    NaN                    NaN                 NaN
1218  ...                    NaN                    NaN                 NaN
1219  ...                    NaN                    NaN                 NaN
1220  ...                    NaN                    NaN                 NaN
1221  ...                    NaN                    NaN                 NaN
1222  ...                    NaN                    NaN                 NaN
1223  ...                    NaN                    NaN                 NaN
1224  ...                    NaN                    NaN                 NaN
1225  ...                    NaN                    NaN                 NaN
1226  ...                    NaN                    NaN                 NaN
1227  ...                    NaN                    NaN                 NaN
1228  ...                    NaN                    NaN                 NaN
1229  ...                    NaN                    NaN                 NaN
1230  ...                    NaN                    NaN                 NaN
1231  ...                    NaN                    NaN                 NaN
1232  ...                    NaN                    NaN                 NaN
1233  ...                    NaN                    NaN                 NaN
1234  ...                    NaN                    NaN                 NaN
1235  ...                    NaN                    NaN                 NaN
1236  ...                    NaN                    NaN                 NaN
1237  ...                    NaN                    NaN                 NaN
1238  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1214                    NaN                     NaN                      NaN
1215                    NaN                     NaN                      NaN
1216                    NaN                     NaN                      NaN
1217                    NaN                     NaN                      NaN
1218                    NaN                     NaN                      NaN
1219                    NaN                     NaN                      NaN
1220                    NaN                     NaN                      NaN
1221                    NaN                     NaN                      NaN
1222                    NaN                     NaN                      NaN
1223                    NaN                     NaN                      NaN
1224                    NaN                     NaN                      NaN
1225                    NaN                     NaN                      NaN
1226                    NaN                     NaN                      NaN
1227                    NaN                     NaN                      NaN
1228                    NaN                     NaN                      NaN
1229                    NaN                     NaN                      NaN
1230                    NaN                     NaN                      NaN
1231                    NaN                     NaN                      NaN
1232                    NaN                     NaN                      NaN
1233                    NaN                     NaN                      NaN
1234                    NaN                     NaN                      NaN
1235                    NaN                     NaN                      NaN
1236                    NaN                     NaN                      NaN
1237                    NaN                     NaN                      NaN
1238                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1214                      NaN                   NaN                      NaN
1215                      NaN                   NaN                      NaN
1216                      NaN                   NaN                      NaN
1217                      NaN                   NaN                      NaN
1218                      NaN                   NaN                      NaN
1219                      NaN                   NaN                      NaN
1220                      NaN                   NaN                      NaN
1221                      NaN                   NaN                      NaN
1222                      NaN                   NaN                      NaN
1223                      NaN                   NaN                      NaN
1224                      NaN                   NaN                      NaN
1225                      NaN                   NaN                      NaN
1226                      NaN                   NaN                      NaN
1227                      NaN                   NaN                      NaN
1228                      NaN                   NaN                      NaN
1229                      NaN                   NaN                      NaN
1230                      NaN                   NaN                      NaN
1231                      NaN                   NaN                      NaN
1232                      NaN                   NaN                      NaN
1233                      NaN                   NaN                      NaN
1234                      NaN                   NaN                      NaN
1235                      NaN                   NaN                      NaN
1236                      NaN                   NaN                      NaN
1237                      NaN                   NaN                      NaN
1238                      NaN                   NaN                      NaN

      population_growth
1214                NaN
1215                NaN
1216                NaN
1217                NaN
1218                NaN
1219                NaN
1220                NaN
1221                NaN
1222                NaN
1223                NaN
1224                NaN
1225                NaN
1226                NaN
1227                NaN
1228                NaN
1229                NaN
1230                NaN
1231                NaN
1232                NaN
1233                NaN
1234                NaN
1235                NaN
1236                NaN
1237                NaN
1238                NaN

[25 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MA       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1239               25                 0              25000                 MA
1240               25                 1              25001                 MA
1241               25                 3              25003                 MA
1242               25                 5              25005                 MA
1243               25                 7              25007                 MA
1244               25                 9              25009                 MA
1245               25                11              25011                 MA
1246               25                13              25013                 MA
1247               25                15              25015                 MA
1248               25                17              25017                 MA
1249               25                19              25019                 MA
1250               25                21              25021                 MA
1251               25                23              25023                 MA
1252               25                25              25025                 MA
1253               25                27              25027                 MA

                   name  premature_death  premature_death_black  \
1239      Massachusetts      5712.511275                    NaN
1240  Barnstable County      7397.904314            9787.653248
1241   Berkshire County      7414.272255           12642.436164
1242     Bristol County      7250.181492            7347.984413
1243       Dukes County      5348.598086                    NaN
1244       Essex County      5990.266671            7136.573931
1245    Franklin County      6458.454975                    NaN
1246     Hampden County      6971.984722            9722.889370
1247   Hampshire County      4965.848862            4677.662457
1248   Middlesex County      4495.478954            5263.469743
1249   Nantucket County      4041.335355                    NaN
1250     Norfolk County      4858.022074            5159.918422
1251    Plymouth County      6432.556502            5064.335546
1252     Suffolk County      5766.568453            7697.994449
1253   Worcester County      6473.694509            6179.333806

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1239                       NaN                    NaN             0.137683
1240               5079.086753            6838.399779             0.103682
1241               3529.765371            7155.615697             0.136717
1242               6748.089897            7088.595813             0.147285
1243                       NaN                    NaN             0.117877
1244               5027.493199            6264.133411             0.137383
1245                       NaN                    NaN             0.134297
1246               7392.624857            6551.781345             0.183868
1247               5724.054001            4972.218486             0.112093
1248               3920.492642            4835.254197             0.112576
1249                       NaN                    NaN             0.123161
1250               3351.300997            5314.057474             0.104445
1251               5325.153896            6752.219185             0.121782
1252               4763.413683            5915.772951             0.166244
1253               5892.099576            6354.550608             0.140746

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1239  ...                    NaN                    NaN                 NaN
1240  ...                    NaN                    NaN                 NaN
1241  ...                    NaN                    NaN                 NaN
1242  ...                    NaN                    NaN                 NaN
1243  ...                    NaN                    NaN                 NaN
1244  ...                    NaN                    NaN                 NaN
1245  ...                    NaN                    NaN                 NaN
1246  ...                    NaN                    NaN                 NaN
1247  ...                    NaN                    NaN                 NaN
1248  ...                    NaN                    NaN                 NaN
1249  ...                    NaN                    NaN                 NaN
1250  ...                    NaN                    NaN                 NaN
1251  ...                    NaN                    NaN                 NaN
1252  ...                    NaN                    NaN                 NaN
1253  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1239                    NaN                     NaN                      NaN
1240                    NaN                     NaN                      NaN
1241                    NaN                     NaN                      NaN
1242                    NaN                     NaN                      NaN
1243                    NaN                     NaN                      NaN
1244                    NaN                     NaN                      NaN
1245                    NaN                     NaN                      NaN
1246                    NaN                     NaN                      NaN
1247                    NaN                     NaN                      NaN
1248                    NaN                     NaN                      NaN
1249                    NaN                     NaN                      NaN
1250                    NaN                     NaN                      NaN
1251                    NaN                     NaN                      NaN
1252                    NaN                     NaN                      NaN
1253                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1239                      NaN                   NaN                      NaN
1240                      NaN                   NaN                      NaN
1241                      NaN                   NaN                      NaN
1242                      NaN                   NaN                      NaN
1243                      NaN                   NaN                      NaN
1244                      NaN                   NaN                      NaN
1245                      NaN                   NaN                      NaN
1246                      NaN                   NaN                      NaN
1247                      NaN                   NaN                      NaN
1248                      NaN                   NaN                      NaN
1249                      NaN                   NaN                      NaN
1250                      NaN                   NaN                      NaN
1251                      NaN                   NaN                      NaN
1252                      NaN                   NaN                      NaN
1253                      NaN                   NaN                      NaN

      population_growth
1239                NaN
1240                NaN
1241                NaN
1242                NaN
1243                NaN
1244                NaN
1245                NaN
1246                NaN
1247                NaN
1248                NaN
1249                NaN
1250                NaN
1251                NaN
1252                NaN
1253                NaN

[15 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\

state of MI       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1254               26                 0              26000                 MI
1255               26                 1              26001                 MI
1256               26                 3              26003                 MI
1257               26                 5              26005                 MI
1258               26                 7              26007                 MI
...               ...               ...                ...                ...
1333               26               157              26157                 MI
1334               26               159              26159                 MI
1335               26               161              26161                 MI
1336               26               163              26163                 MI
1337               26               165              26165                 MI

                  name  premature_death  premature_death_black  \
1254          Michigan      7553.001031                    NaN
1255     Alcona County     10747.181609                    NaN
1256      Alger County      7049.162239                    NaN
1257    Allegan County      6174.887946                    NaN
1258     Alpena County      7187.322518                    NaN
...                ...              ...                    ...
1333    Tuscola County      7406.506297                    NaN
1334  Van Buren County      8096.806563           13638.204905
1335  Washtenaw County      5018.033552            9322.130592
1336      Wayne County     10478.539198           14121.455303
1337    Wexford County      8034.689884                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1254                       NaN                    NaN             0.173588
1255                       NaN                    NaN             0.155692
1256                       NaN                    NaN             0.150821
1257               4085.045665            6227.124368             0.150653
1258                       NaN                    NaN             0.161498
...                        ...                    ...                  ...
1333                       NaN                    NaN             0.158758
1334               5538.650371            8072.817920             0.173644
1335               3447.074291            4806.221007             0.114678
1336               7988.007104            8318.226228             0.188361
1337                       NaN                    NaN             0.163605

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1254  ...                    NaN                    NaN                 NaN
1255  ...                    NaN                    NaN                 NaN
1256  ...                    NaN                    NaN                 NaN
1257  ...                    NaN                    NaN                 NaN
1258  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1333  ...                    NaN                    NaN                 NaN
1334  ...                    NaN                    NaN                 NaN
1335  ...                    NaN                    NaN                 NaN
1336  ...                    NaN                    NaN                 NaN
1337  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1254                    NaN                     NaN                      NaN
1255                    NaN                     NaN                      NaN
1256                    NaN                     NaN                      NaN
1257                    NaN                     NaN                      NaN
1258                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1333                    NaN                     NaN                      NaN
1334                    NaN                     NaN                      NaN
1335                    NaN                     NaN                      NaN
1336                    NaN                     NaN                      NaN
1337                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1254                      NaN                   NaN                      NaN
1255                      NaN                   NaN                      NaN
1256                      NaN                   NaN                      NaN
1257                      NaN                   NaN                      NaN
1258                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1333                      NaN                   NaN                      NaN
1334                      NaN                   NaN                      NaN
1335                      NaN                   NaN                      NaN
1336                      NaN                   NaN                      NaN
1337                      NaN                   NaN                      NaN

      population_growth
1254                NaN
1255                NaN
1256                NaN
1257                NaN
1258                NaN
...                 ...
1333                NaN
1334                NaN
1335                NaN
1336                NaN
1337                NaN

[84 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MN       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1338               27                 0              27000                 MN
1339               27                 1              27001                 MN
1340               27                 3              27003                 MN
1341               27                 5              27005                 MN
1342               27                 7              27007                 MN
...               ...               ...                ...                ...
1421               27               165              27165                 MN
1422               27               167              27167                 MN
1423               27               169              27169                 MN
1424               27               171              27171                 MN
1425               27               173              27173                 MN

                        name  premature_death  premature_death_black  \
1338               Minnesota      5257.912551                    NaN
1339           Aitkin County      9092.549521                    NaN
1340            Anoka County      5008.510854             7164.29929
1341           Becker County      6447.689266                    NaN
1342         Beltrami County      8457.142206                    NaN
...                      ...              ...                    ...
1421         Watonwan County      7370.692766                    NaN
1422           Wilkin County      6649.008705                    NaN
1423           Winona County      5798.836677                    NaN
1424           Wright County      4035.794100                    NaN
1425  Yellow Medicine County      6884.632248                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1338                       NaN                    NaN             0.120167
1339                       NaN                    NaN             0.134269
1340               5061.736334            4851.905116             0.101555
1341                       NaN                    NaN             0.142610
1342                       NaN                    NaN             0.158033
...                        ...                    ...                  ...
1421                       NaN                    NaN             0.151619
1422                       NaN                    NaN             0.115563
1423                       NaN                    NaN             0.119263
1424                       NaN                    NaN             0.103517
1425                       NaN                    NaN             0.122978

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1338  ...                    NaN                    NaN                 NaN
1339  ...                    NaN                    NaN                 NaN
1340  ...                    NaN                    NaN                 NaN
1341  ...                    NaN                    NaN                 NaN
1342  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1421  ...                    NaN                    NaN                 NaN
1422  ...                    NaN                    NaN                 NaN
1423  ...                    NaN                    NaN                 NaN
1424  ...                    NaN                    NaN                 NaN
1425  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1338                    NaN                     NaN                      NaN
1339                    NaN                     NaN                      NaN
1340                    NaN                     NaN                      NaN
1341                    NaN                     NaN                      NaN
1342                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1421                    NaN                     NaN                      NaN
1422                    NaN                     NaN                      NaN
1423                    NaN                     NaN                      NaN
1424                    NaN                     NaN                      NaN
1425                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1338                      NaN                   NaN                      NaN
1339                      NaN                   NaN                      NaN
1340                      NaN                   NaN                      NaN
1341                      NaN                   NaN                      NaN
1342                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1421                      NaN                   NaN                      NaN
1422                      NaN                   NaN                      NaN
1423                      NaN                   NaN                      NaN
1424                      NaN                   NaN                      NaN
1425                      NaN                   NaN                      NaN

      population_growth
1338                NaN
1339                NaN
1340                NaN
1341                NaN
1342                NaN
...                 ...
1421                NaN
1422                NaN
1423                NaN
1424                NaN
1425                NaN

[88 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MS       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1426               28                 0              28000                 MS
1427               28                 1              28001                 MS
1428               28                 3              28003                 MS
1429               28                 5              28005                 MS
1430               28                 7              28007                 MS
...               ...               ...                ...                ...
1504               28               155              28155                 MS
1505               28               157              28157                 MS
1506               28               159              28159                 MS
1507               28               161              28161                 MS
1508               28               163              28163                 MS

                  name  premature_death  premature_death_black  \
1426       Mississippi     10376.163457                    NaN
1427      Adams County     11098.737567           14450.245573
1428     Alcorn County     11859.819225           17594.572519
1429      Amite County      9556.453363           11163.528436
1430     Attala County     13886.004519           17041.143488
...                ...              ...                    ...
1504    Webster County      9901.896909           14086.546508
1505  Wilkinson County     14915.698021           14793.461372
1506    Winston County     11721.875164           12805.733897
1507  Yalobusha County     11552.363893           11919.439390
1508      Yazoo County     12545.156546           15256.990203

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1426                       NaN                    NaN             0.222107
1427                       NaN            8867.054406             0.252348
1428                       NaN           11090.638461             0.206829
1429                       NaN            8587.046380             0.233394
1430                       NaN           11610.239485             0.223945
...                        ...                    ...                  ...
1504                       NaN            8781.139722             0.203296
1505                       NaN           17104.347854             0.287746
1506                       NaN           10730.162979             0.269750
1507                       NaN           11629.788147             0.237355
1508                       NaN           10271.138522             0.271460

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1426  ...                    NaN                    NaN                 NaN
1427  ...                    NaN                    NaN                 NaN
1428  ...                    NaN                    NaN                 NaN
1429  ...                    NaN                    NaN                 NaN
1430  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1504  ...                    NaN                    NaN                 NaN
1505  ...                    NaN                    NaN                 NaN
1506  ...                    NaN                    NaN                 NaN
1507  ...                    NaN                    NaN                 NaN
1508  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1426                    NaN                     NaN                      NaN
1427                    NaN                     NaN                      NaN
1428                    NaN                     NaN                      NaN
1429                    NaN                     NaN                      NaN
1430                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1504                    NaN                     NaN                      NaN
1505                    NaN                     NaN                      NaN
1506                    NaN                     NaN                      NaN
1507                    NaN                     NaN                      NaN
1508                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1426                      NaN                   NaN                      NaN
1427                      NaN                   NaN                      NaN
1428                      NaN                   NaN                      NaN
1429                      NaN                   NaN                      NaN
1430                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1504                      NaN                   NaN                      NaN
1505                      NaN                   NaN                      NaN
1506                      NaN                   NaN                      NaN
1507                      NaN                   NaN                      NaN
1508                      NaN                   NaN                      NaN

      population_growth
1426                NaN
1427                NaN
1428                NaN
1429                NaN
1430                NaN
...                 ...
1504                NaN
1505                NaN
1506                NaN
1507                NaN
1508                NaN

[83 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MO       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1509               29                 0              29000                 MO
1510               29                 1              29001                 MO
1511               29                 3              29003                 MO
1512               29                 5              29005                 MO
1513               29                 7              29007                 MO
...               ...               ...                ...                ...
1620               29               223              29223                 MO
1621               29               225              29225                 MO
1622               29               227              29227                 MO
1623               29               229              29229                 MO
1624               29               510              29510                 MO

                 name  premature_death  premature_death_black  \
1509         Missouri      8190.098356                    NaN
1510     Adair County      8362.577513                    NaN
1511    Andrew County      6425.364529                    NaN
1512  Atchison County      8293.721570                    NaN
1513   Audrain County      7428.216494           10308.442690
...               ...              ...                    ...
1620     Wayne County     10338.815424                    NaN
1621   Webster County      7747.667445                    NaN
1622     Worth County     15833.712572                    NaN
1623    Wright County     10453.327288                    NaN
1624   St. Louis city     12680.579721           18360.707387

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1509                       NaN                    NaN             0.185001
1510                       NaN                    NaN             0.200800
1511                       NaN                    NaN             0.148489
1512                       NaN                    NaN             0.162465
1513                       NaN            7247.911997             0.180285
...                        ...                    ...                  ...
1620                       NaN                    NaN             0.229688
1621                       NaN                    NaN             0.207978
1622                       NaN                    NaN             0.182972
1623                       NaN                    NaN             0.238901
1624               3894.228692            8430.159818             0.240037

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1509  ...                    NaN                    NaN                 NaN
1510  ...                    NaN                    NaN                 NaN
1511  ...                    NaN                    NaN                 NaN
1512  ...                    NaN                    NaN                 NaN
1513  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1620  ...                    NaN                    NaN                 NaN
1621  ...                    NaN                    NaN                 NaN
1622  ...                    NaN                    NaN                 NaN
1623  ...                    NaN                    NaN                 NaN
1624  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1509                    NaN                     NaN                      NaN
1510                    NaN                     NaN                      NaN
1511                    NaN                     NaN                      NaN
1512                    NaN                     NaN                      NaN
1513                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1620                    NaN                     NaN                      NaN
1621                    NaN                     NaN                      NaN
1622                    NaN                     NaN                      NaN
1623                    NaN                     NaN                      NaN
1624                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1509                      NaN                   NaN                      NaN
1510                      NaN                   NaN                      NaN
1511                      NaN                   NaN                      NaN
1512                      NaN                   NaN                      NaN
1513                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1620                      NaN                   NaN                      NaN
1621                      NaN                   NaN                      NaN
1622                      NaN                   NaN                      NaN
1623                      NaN                   NaN                      NaN
1624                      NaN                   NaN                      NaN

      population_growth
1509                NaN
1510                NaN
1511                NaN
1512                NaN
1513                NaN
...                 ...
1620                NaN
1621                NaN
1622                NaN
1623                NaN
1624                NaN

[116 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of MT       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1625               30                 0              30000                 MT
1626               30                 1              30001                 MT
1627               30                 3              30003                 MT
1628               30                 5              30005                 MT
1629               30                 7              30007                 MT
1630               30                 9              30009                 MT
1631               30                11              30011                 MT
1632               30                13              30013                 MT
1633               30                15              30015                 MT
1634               30                17              30017                 MT
1635               30                19              30019                 MT
1636               30                21              30021                 MT
1637               30                23              30023                 MT
1638               30                25              30025                 MT
1639               30                27              30027                 MT
1640               30                29              30029                 MT
1641               30                31              30031                 MT
1642               30                33              30033                 MT
1643               30                35              30035                 MT
1644               30                37              30037                 MT
1645               30                39              30039                 MT
1646               30                41              30041                 MT
1647               30                43              30043                 MT
1648               30                45              30045                 MT
1649               30                47              30047                 MT
1650               30                49              30049                 MT
1651               30                51              30051                 MT
1652               30                53              30053                 MT
1653               30                55              30055                 MT
1654               30                57              30057                 MT
1655               30                59              30059                 MT
1656               30                61              30061                 MT
1657               30                63              30063                 MT
1658               30                65              30065                 MT
1659               30                67              30067                 MT
1660               30                69              30069                 MT
1661               30                71              30071                 MT
1662               30                73              30073                 MT
1663               30                75              30075                 MT
1664               30                77              30077                 MT
1665               30                79              30079                 MT
1666               30                81              30081                 MT
1667               30                83              30083                 MT
1668               30                85              30085                 MT
1669               30                87              30087                 MT
1670               30                89              30089                 MT
1671               30                91              30091                 MT
1672               30                93              30093                 MT
1673               30                95              30095                 MT
1674               30                97              30097                 MT
1675               30                99              30099                 MT
1676               30               101              30101                 MT
1677               30               103              30103                 MT
1678               30               105              30105                 MT
1679               30               107              30107                 MT
1680               30               109              30109                 MT
1681               30               111              30111                 MT

                        name  premature_death  premature_death_black  \
1625                 Montana      7540.776328                    NaN
1626       Beaverhead County      5391.815950                    NaN
1627         Big Horn County     20972.879964                    NaN
1628           Blaine County     13489.187383                    NaN
1629       Broadwater County      5812.993359                    NaN
1630           Carbon County      7425.590797                    NaN
1631           Carter County              NaN                    NaN
1632          Cascade County      7825.374592                    NaN
1633         Chouteau County      6963.518329                    NaN
1634           Custer County      5731.930922                    NaN
1635          Daniels County      8625.726720                    NaN
1636           Dawson County      5818.406927                    NaN
1637       Deer Lodge County     11356.606772                    NaN
1638           Fallon County      8947.145116                    NaN
1639           Fergus County      7059.452470                    NaN
1640         Flathead County      6696.497237                    NaN
1641         Gallatin County      4341.565181                    NaN
1642         Garfield County      9512.355042                    NaN
1643          Glacier County     18477.056304                    NaN
1644    Golden Valley County              NaN                    NaN
1645          Granite County      6940.193098                    NaN
1646             Hill County     10139.621864                    NaN
1647        Jefferson County      5735.498363                    NaN
1648     Judith Basin County              NaN                    NaN
1649             Lake County      9492.936778                    NaN
1650  Lewis and Clark County      6897.102883                    NaN
1651          Liberty County              NaN                    NaN
1652          Lincoln County      8903.617711                    NaN
1653           McCone County      8953.029527                    NaN
1654          Madison County      4922.921715                    NaN
1655          Meagher County      3888.005485                    NaN
1656          Mineral County     13768.213203                    NaN
1657         Missoula County      6322.890176                    NaN
1658      Musselshell County      7611.920151                    NaN
1659             Park County      7910.622742                    NaN
1660        Petroleum County              NaN                    NaN
1661         Phillips County      5961.141653                    NaN
1662          Pondera County      7220.878743                    NaN
1663     Powder River County              NaN                    NaN
1664           Powell County      6577.948958                    NaN
1665          Prairie County      8278.628922                    NaN
1666          Ravalli County      6349.459367                    NaN
1667         Richland County      6230.694248                    NaN
1668        Roosevelt County     19955.035893                    NaN
1669          Rosebud County     13686.827126                    NaN
1670          Sanders County     11135.643519                    NaN
1671         Sheridan County      5597.100342                    NaN
1672       Silver Bow County      9578.196228                    NaN
1673       Stillwater County      5778.254948                    NaN
1674      Sweet Grass County      5658.711979                    NaN
1675            Teton County      8073.325972                    NaN
1676            Toole County     10288.337073                    NaN
1677         Treasure County              NaN                    NaN
1678           Valley County      7895.117852                    NaN
1679        Wheatland County      7703.267966                    NaN
1680           Wibaux County              NaN                    NaN
1681      Yellowstone County      7568.322226           18350.873811

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1625                       NaN                    NaN             0.139490
1626                       NaN                    NaN             0.138403
1627                       NaN                    NaN             0.255614
1628                       NaN                    NaN             0.213171
1629                       NaN                    NaN             0.128891
1630                       NaN                    NaN             0.113829
1631                       NaN                    NaN             0.120215
1632               7312.269999            7314.523634             0.146511
1633                       NaN                    NaN             0.174547
1634                       NaN                    NaN             0.117243
1635                       NaN                    NaN             0.107141
1636                       NaN                    NaN             0.126657
1637                       NaN                    NaN             0.176628
1638                       NaN                    NaN             0.109892
1639                       NaN                    NaN             0.154912
1640                       NaN                    NaN             0.134179
1641                       NaN                    NaN             0.118742
1642                       NaN                    NaN             0.128143
1643                       NaN                    NaN             0.230532
1644                       NaN                    NaN             0.140388
1645                       NaN                    NaN             0.128975
1646                       NaN                    NaN             0.176408
1647                       NaN                    NaN             0.106526
1648                       NaN                    NaN             0.124460
1649                       NaN                    NaN             0.163876
1650                       NaN                    NaN             0.113737
1651                       NaN                    NaN             0.127032
1652                       NaN                    NaN             0.159998
1653                       NaN                    NaN             0.117277
1654                       NaN                    NaN             0.110182
1655                       NaN                    NaN             0.155298
1656                       NaN                    NaN             0.148220
1657                       NaN                    NaN             0.138689
1658                       NaN                    NaN             0.158660
1659                       NaN                    NaN             0.126495
1660                       NaN                    NaN             0.149304
1661                       NaN                    NaN             0.164842
1662                       NaN                    NaN             0.166050
1663                       NaN                    NaN             0.131898
1664                       NaN                    NaN             0.131937
1665                       NaN                    NaN             0.136900
1666                       NaN                    NaN             0.144936
1667                       NaN                    NaN             0.122035
1668                       NaN                    NaN             0.244576
1669                       NaN                    NaN             0.189514
1670                       NaN                    NaN             0.170942
1671                       NaN                    NaN             0.114182
1672                       NaN                    NaN             0.166971
1673                       NaN                    NaN             0.114217
1674                       NaN                    NaN             0.119168
1675                       NaN                    NaN             0.124360
1676                       NaN                    NaN             0.137790
1677                       NaN                    NaN             0.166620
1678                       NaN                    NaN             0.143339
1679                       NaN                    NaN             0.145921
1680                       NaN                    NaN             0.147180
1681              10188.483054            6916.009341             0.139898

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1625  ...                    NaN                    NaN                 NaN
1626  ...                    NaN                    NaN                 NaN
1627  ...                    NaN                    NaN                 NaN
1628  ...                    NaN                    NaN                 NaN
1629  ...                    NaN                    NaN                 NaN
1630  ...                    NaN                    NaN                 NaN
1631  ...                    NaN                    NaN                 NaN
1632  ...                    NaN                    NaN                 NaN
1633  ...                    NaN                    NaN                 NaN
1634  ...                    NaN                    NaN                 NaN
1635  ...                    NaN                    NaN                 NaN
1636  ...                    NaN                    NaN                 NaN
1637  ...                    NaN                    NaN                 NaN
1638  ...                    NaN                    NaN                 NaN
1639  ...                    NaN                    NaN                 NaN
1640  ...                    NaN                    NaN                 NaN
1641  ...                    NaN                    NaN                 NaN
1642  ...                    NaN                    NaN                 NaN
1643  ...                    NaN                    NaN                 NaN
1644  ...                    NaN                    NaN                 NaN
1645  ...                    NaN                    NaN                 NaN
1646  ...                    NaN                    NaN                 NaN
1647  ...                    NaN                    NaN                 NaN
1648  ...                    NaN                    NaN                 NaN
1649  ...                    NaN                    NaN                 NaN
1650  ...                    NaN                    NaN                 NaN
1651  ...                    NaN                    NaN                 NaN
1652  ...                    NaN                    NaN                 NaN
1653  ...                    NaN                    NaN                 NaN
1654  ...                    NaN                    NaN                 NaN
1655  ...                    NaN                    NaN                 NaN
1656  ...                    NaN                    NaN                 NaN
1657  ...                    NaN                    NaN                 NaN
1658  ...                    NaN                    NaN                 NaN
1659  ...                    NaN                    NaN                 NaN
1660  ...                    NaN                    NaN                 NaN
1661  ...                    NaN                    NaN                 NaN
1662  ...                    NaN                    NaN                 NaN
1663  ...                    NaN                    NaN                 NaN
1664  ...                    NaN                    NaN                 NaN
1665  ...                    NaN                    NaN                 NaN
1666  ...                    NaN                    NaN                 NaN
1667  ...                    NaN                    NaN                 NaN
1668  ...                    NaN                    NaN                 NaN
1669  ...                    NaN                    NaN                 NaN
1670  ...                    NaN                    NaN                 NaN
1671  ...                    NaN                    NaN                 NaN
1672  ...                    NaN                    NaN                 NaN
1673  ...                    NaN                    NaN                 NaN
1674  ...                    NaN                    NaN                 NaN
1675  ...                    NaN                    NaN                 NaN
1676  ...                    NaN                    NaN                 NaN
1677  ...                    NaN                    NaN                 NaN
1678  ...                    NaN                    NaN                 NaN
1679  ...                    NaN                    NaN                 NaN
1680  ...                    NaN                    NaN                 NaN
1681  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1625                    NaN                     NaN                      NaN
1626                    NaN                     NaN                      NaN
1627                    NaN                     NaN                      NaN
1628                    NaN                     NaN                      NaN
1629                    NaN                     NaN                      NaN
1630                    NaN                     NaN                      NaN
1631                    NaN                     NaN                      NaN
1632                    NaN                     NaN                      NaN
1633                    NaN                     NaN                      NaN
1634                    NaN                     NaN                      NaN
1635                    NaN                     NaN                      NaN
1636                    NaN                     NaN                      NaN
1637                    NaN                     NaN                      NaN
1638                    NaN                     NaN                      NaN
1639                    NaN                     NaN                      NaN
1640                    NaN                     NaN                      NaN
1641                    NaN                     NaN                      NaN
1642                    NaN                     NaN                      NaN
1643                    NaN                     NaN                      NaN
1644                    NaN                     NaN                      NaN
1645                    NaN                     NaN                      NaN
1646                    NaN                     NaN                      NaN
1647                    NaN                     NaN                      NaN
1648                    NaN                     NaN                      NaN
1649                    NaN                     NaN                      NaN
1650                    NaN                     NaN                      NaN
1651                    NaN                     NaN                      NaN
1652                    NaN                     NaN                      NaN
1653                    NaN                     NaN                      NaN
1654                    NaN                     NaN                      NaN
1655                    NaN                     NaN                      NaN
1656                    NaN                     NaN                      NaN
1657                    NaN                     NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NE       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1682               31                 0              31000                 NE
1683               31                 1              31001                 NE
1684               31                 3              31003                 NE
1685               31                 5              31005                 NE
1686               31                 7              31007                 NE
...               ...               ...                ...                ...
1771               31               177              31177                 NE
1772               31               179              31179                 NE
1773               31               181              31181                 NE
1774               31               183              31183                 NE
1775               31               185              31185                 NE

                   name  premature_death  premature_death_black  \
1682           Nebraska      6060.454543                    NaN
1683       Adams County      6832.042385                    NaN
1684    Antelope County      6553.831660                    NaN
1685      Arthur County              NaN                    NaN
1686      Banner County              NaN                    NaN
...                 ...              ...                    ...
1771  Washington County      4725.544003                    NaN
1772       Wayne County      3146.110285                    NaN
1773     Webster County     11351.128446                    NaN
1774     Wheeler County              NaN                    NaN
1775        York County      7539.848420                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1682                       NaN                    NaN             0.141967
1683                       NaN                    NaN             0.153019
1684                       NaN                    NaN             0.134072
1685                       NaN                    NaN             0.128437
1686                       NaN                    NaN             0.141624
...                        ...                    ...                  ...
1771                       NaN                    NaN             0.114622
1772                       NaN                    NaN             0.142642
1773                       NaN                    NaN             0.137004
1774                       NaN                    NaN             0.125153
1775                       NaN                    NaN             0.129766

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1682  ...                    NaN                    NaN                 NaN
1683  ...                    NaN                    NaN                 NaN
1684  ...                    NaN                    NaN                 NaN
1685  ...                    NaN                    NaN                 NaN
1686  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1771  ...                    NaN                    NaN                 NaN
1772  ...                    NaN                    NaN                 NaN
1773  ...                    NaN                    NaN                 NaN
1774  ...                    NaN                    NaN                 NaN
1775  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1682                    NaN                     NaN                      NaN
1683                    NaN                     NaN                      NaN
1684                    NaN                     NaN                      NaN
1685                    NaN                     NaN                      NaN
1686                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1771                    NaN                     NaN                      NaN
1772                    NaN                     NaN                      NaN
1773                    NaN                     NaN                      NaN
1774                    NaN                     NaN                      NaN
1775                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1682                      NaN                   NaN                      NaN
1683                      NaN                   NaN                      NaN
1684                      NaN                   NaN                      NaN
1685                      NaN                   NaN                      NaN
1686                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1771                      NaN                   NaN                      NaN
1772                      NaN                   NaN                      NaN
1773                      NaN                   NaN                      NaN
1774                      NaN                   NaN                      NaN
1775                      NaN                   NaN                      NaN

      population_growth
1682                NaN
1683                NaN
1684                NaN
1685                NaN
1686                NaN
...                 ...
1771                NaN
1772                NaN
1773                NaN
1774                NaN
1775                NaN

[94 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NV       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1776               32                 0              32000                 NV
1777               32                 1              32001                 NV
1778               32                 3              32003                 NV
1779               32                 5              32005                 NV
1780               32                 7              32007                 NV
1781               32                 9              32009                 NV
1782               32                11              32011                 NV
1783               32                13              32013                 NV
1784               32                15              32015                 NV
1785               32                17              32017                 NV
1786               32                19              32019                 NV
1787               32                21              32021                 NV
1788               32                23              32023                 NV
1789               32                27              32027                 NV
1790               32                29              32029                 NV
1791               32                31              32031                 NV
1792               32                33              32033                 NV
1793               32               510              32510                 NV

                   name  premature_death  premature_death_black  \
1776             Nevada      7275.921605                    NaN
1777   Churchill County      8007.451469                    NaN
1778       Clark County      7145.161007           11594.204898
1779     Douglas County      5889.430607                    NaN
1780        Elko County      7289.894740                    NaN
1781   Esmeralda County              NaN                    NaN
1782      Eureka County              NaN                    NaN
1783    Humboldt County      8844.332139                    NaN
1784      Lander County      8785.270578                    NaN
1785     Lincoln County      6152.343510                    NaN
1786        Lyon County      8346.504390                    NaN
1787     Mineral County     10933.851141                    NaN
1788         Nye County     11691.092258                    NaN
1789    Pershing County      5871.511148                    NaN
1790      Storey County      5728.489881                    NaN
1791      Washoe County      7089.039609           12202.109325
1792  White Pine County      8319.219291                    NaN
1793        Carson City     10423.678470                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1776                       NaN                    NaN             0.205235
1777               7633.806950            8000.031639             0.166872
1778               4533.706189            8126.754119             0.185580
1779               5113.694809            5849.753324             0.133880
1780               4184.700897            7868.065973             0.156249
1781                       NaN                    NaN             0.233263
1782                       NaN                    NaN             0.135981
1783                       NaN                    NaN             0.164396
1784                       NaN                    NaN             0.157626
1785                       NaN                    NaN             0.148909
1786               4041.433389            9423.733624             0.179799
1787                       NaN                    NaN             0.199309
1788               6291.099602           13092.659269             0.194439
1789                       NaN                    NaN             0.174585
1790                       NaN                    NaN             0.127330
1791               4490.640487            7868.340858             0.155822
1792                       NaN                    NaN             0.174489
1793               5886.622340           11794.301376             0.188485

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1776  ...                    NaN                    NaN                 NaN
1777  ...                    NaN                    NaN                 NaN
1778  ...                    NaN                    NaN                 NaN
1779  ...                    NaN                    NaN                 NaN
1780  ...                    NaN                    NaN                 NaN
1781  ...                    NaN                    NaN                 NaN
1782  ...                    NaN                    NaN                 NaN
1783  ...                    NaN                    NaN                 NaN
1784  ...                    NaN                    NaN                 NaN
1785  ...                    NaN                    NaN                 NaN
1786  ...                    NaN                    NaN                 NaN
1787  ...                    NaN                    NaN                 NaN
1788  ...                    NaN                    NaN                 NaN
1789  ...                    NaN                    NaN                 NaN
1790  ...                    NaN                    NaN                 NaN
1791  ...                    NaN                    NaN                 NaN
1792  ...                    NaN                    NaN                 NaN
1793  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1776                    NaN                     NaN                      NaN
1777                    NaN                     NaN                      NaN
1778                    NaN                     NaN                      NaN
1779                    NaN                     NaN                      NaN
1780                    NaN                     NaN                      NaN
1781                    NaN                     NaN                      NaN
1782                    NaN                     NaN                      NaN
1783                    NaN                     NaN                      NaN
1784                    NaN                     NaN                      NaN
1785                    NaN                     NaN                      NaN
1786                    NaN                     NaN                      NaN
1787                    NaN                     NaN                      NaN
1788                    NaN                     NaN                      NaN
1789                    NaN                     NaN                      NaN
1790                    NaN                     NaN                      NaN
1791                    NaN                     NaN                      NaN
1792                    NaN                     NaN                      NaN
1793                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1776                      NaN                   NaN                      NaN
1777                      NaN                   NaN                      NaN
1778                      NaN                   NaN                      NaN
1779                      NaN                   NaN                      NaN
1780                      NaN                   NaN                      NaN
1781                      NaN                   NaN                      NaN
1782                      NaN                   NaN                      NaN
1783                      NaN                   NaN                      NaN
1784                      NaN                   NaN                      NaN
1785                      NaN                   NaN                      NaN
1786                      NaN                   NaN                      NaN
1787                      NaN                   NaN                      NaN
1788                      NaN                   NaN                      NaN
1789                      NaN                   NaN                      NaN
1790                      NaN                   NaN                      NaN
1791                      NaN                   NaN                      NaN
1792                      NaN                   NaN                      NaN
1793                      NaN                   NaN                      NaN

      population_growth
1776                NaN
1777                NaN
1778                NaN
1779                NaN
1780                NaN
1781                NaN
1782                NaN
1783                NaN
1784                NaN
1785                NaN
1786                NaN
1787                NaN
1788                NaN
1789                NaN
1790                NaN
1791                NaN
1792                NaN
1793                NaN

[18 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NH       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1794               33                 0              33000                 NH
1795               33                 1              33001                 NH
1796               33                 3              33003                 NH
1797               33                 5              33005                 NH
1798               33                 7              33007                 NH
1799               33                 9              33009                 NH
1800               33                11              33011                 NH
1801               33                13              33013                 NH
1802               33                15              33015                 NH
1803               33                17              33017                 NH
1804               33                19              33019                 NH

                     name  premature_death  premature_death_black  \
1794        New Hampshire      6460.382908                    NaN
1795       Belknap County      7211.083498                    NaN
1796       Carroll County      7520.713945                    NaN
1797      Cheshire County      6747.021458                    NaN
1798          Coos County      8402.001071                    NaN
1799       Grafton County      5428.159787                    NaN
1800  Hillsborough County      6816.415639            6191.909301
1801     Merrimack County      6407.702968                    NaN
1802    Rockingham County      5623.944725            4957.469632
1803     Strafford County      7010.437403                    NaN
1804      Sullivan County      6671.510413                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1794                       NaN                    NaN             0.135785
1795                       NaN                    NaN             0.114694
1796                       NaN                    NaN             0.133610
1797                       NaN                    NaN             0.122140
1798                       NaN                    NaN             0.142669
1799                       NaN                    NaN             0.120809
1800               4718.379160            7224.601436             0.125731
1801                       NaN                    NaN             0.117464
1802               2608.278855            5797.479816             0.104381
1803                       NaN                    NaN             0.148874
1804                       NaN                    NaN             0.139349

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1794  ...                    NaN                    NaN                 NaN
1795  ...                    NaN                    NaN                 NaN
1796  ...                    NaN                    NaN                 NaN
1797  ...                    NaN                    NaN                 NaN
1798  ...                    NaN                    NaN                 NaN
1799  ...                    NaN                    NaN                 NaN
1800  ...                    NaN                    NaN                 NaN
1801  ...                    NaN                    NaN                 NaN
1802  ...                    NaN                    NaN                 NaN
1803  ...                    NaN                    NaN                 NaN
1804  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1794                    NaN                     NaN                      NaN
1795                    NaN                     NaN                      NaN
1796                    NaN                     NaN                      NaN
1797                    NaN                     NaN                      NaN
1798                    NaN                     NaN                      NaN
1799                    NaN                     NaN                      NaN
1800                    NaN                     NaN                      NaN
1801                    NaN                     NaN                      NaN
1802                    NaN                     NaN                      NaN
1803                    NaN                     NaN                      NaN
1804                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1794                      NaN                   NaN                      NaN
1795                      NaN                   NaN                      NaN
1796                      NaN                   NaN                      NaN
1797                      NaN                   NaN                      NaN
1798                      NaN                   NaN                      NaN
1799                      NaN                   NaN                      NaN
1800                      NaN                   NaN                      NaN
1801                      NaN                   NaN                      NaN
1802                      NaN                   NaN                      NaN
1803                      NaN                   NaN                      NaN
1804                      NaN                   NaN                      NaN

      population_growth
1794                NaN
1795                NaN
1796                NaN
1797                NaN
1798                NaN
1799                NaN
1800                NaN
1801                NaN
1802                NaN
1803                NaN
1804                NaN

[11 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NJ       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1805               34                 0              34000                 NJ
1806               34                 1              34001                 NJ
1807               34                 3              34003                 NJ
1808               34                 5              34005                 NJ
1809               34                 7              34007                 NJ
1810               34                 9              34009                 NJ
1811               34                11              34011                 NJ
1812               34                13              34013                 NJ
1813               34                15              34015                 NJ
1814               34                17              34017                 NJ
1815               34                19              34019                 NJ
1816               34                21              34021                 NJ
1817               34                23              34023                 NJ
1818               34                25              34025                 NJ
1819               34                27              34027                 NJ
1820               34                29              34029                 NJ
1821               34                31              34031                 NJ
1822               34                33              34033                 NJ
1823               34                35              34035                 NJ
1824               34                37              34037                 NJ
1825               34                39              34039                 NJ
1826               34                41              34041                 NJ

                   name  premature_death  premature_death_black  \
1805         New Jersey      5743.197958                    NaN
1806    Atlantic County      8541.215977           14290.342756
1807      Bergen County      3835.655474            5853.197983
1808  Burlington County      6301.710803            7763.950858
1809      Camden County      8245.652856           12456.745682
1810    Cape May County      8616.968311           10719.890894
1811  Cumberland County      9449.372792           12026.517987
1812       Essex County      7239.891824           11166.133441
1813  Gloucester County      6931.305097            9733.112812
1814      Hudson County      5064.378407           10699.832002
1815   Hunterdon County      4498.662487            6043.901551
1816      Mercer County      6066.189369           10925.686374
1817   Middlesex County      4568.775109            5908.579388
1818    Monmouth County      5281.434985            9990.718231
1819      Morris County      4023.785028            5711.893118
1820       Ocean County      6804.565753           10205.826924
1821     Passaic County      5536.243734           11609.636093
1822       Salem County      8835.989199           15762.655369
1823    Somerset County      4359.466577            7430.705987
1824      Sussex County      6422.484638            8473.780963
1825       Union County      5210.697056            8340.594037
1826      Warren County      6978.278756            8629.394552

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1805                       NaN                    NaN             0.165485
1806               5953.781070            8844.937783             0.186305
1807               2658.707440            4604.568416             0.134118
1808               3470.761549            6492.063337             0.127541
1809               7514.631420            7425.678353             0.179561
1810               7249.280671            8617.471730             0.147915
1811               7633.204145            9549.581974             0.231549
1812               5152.503594            4778.264118             0.209189
1813               5456.935615            6837.293239             0.155061
1814               4037.430391            5894.574874             0.207432
1815               2508.644489            4745.308499             0.105846
1816               4491.754272            5519.222999             0.145254
1817               3863.921734            6001.253614             0.158119
1818               4296.068454            5203.316913             0.128718
1819               3090.755007            4358.886879             0.111012
1820               4491.999837            7031.892126             0.142363
1821               4023.850669            5929.488220             0.212849
1822               5400.817311            7944.965289             0.177794
1823               3358.257012            4733.502749             0.111432
1824               4166.508125            6706.290670             0.117809
1825               3580.277116            5145.116009             0.168884
1826               5019.241761            7233.082588             0.148994

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1805  ...                    NaN                    NaN                 NaN
1806  ...                    NaN                    NaN                 NaN
1807  ...                    NaN                    NaN                 NaN
1808  ...                    NaN                    NaN                 NaN
1809  ...                    NaN                    NaN                 NaN
1810  ...                    NaN                    NaN                 NaN
1811  ...                    NaN                    NaN                 NaN
1812  ...                    NaN                    NaN                 NaN
1813  ...                    NaN                    NaN                 NaN
1814  ...                    NaN                    NaN                 NaN
1815  ...                    NaN                    NaN                 NaN
1816  ...                    NaN                    NaN                 NaN
1817  ...                    NaN                    NaN                 NaN
1818  ...                    NaN                    NaN                 NaN
1819  ...                    NaN                    NaN                 NaN
1820  ...                    NaN                    NaN                 NaN
1821  ...                    NaN                    NaN                 NaN
1822  ...                    NaN                    NaN                 NaN
1823  ...                    NaN                    NaN                 NaN
1824  ...                    NaN                    NaN                 NaN
1825  ...                    NaN                    NaN                 NaN
1826  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1805                    NaN                     NaN                      NaN
1806                    NaN                     NaN                      NaN
1807                    NaN                     NaN                      NaN
1808                    NaN                     NaN                      NaN
1809                    NaN                     NaN                      NaN
1810                    NaN                     NaN                      NaN
1811                    NaN                     NaN                      NaN
1812                    NaN                     NaN                      NaN
1813                    NaN                     NaN                      NaN
1814                    NaN                     NaN                      NaN
1815                    NaN                     NaN                      NaN
1816                    NaN                     NaN                      NaN
1817                    NaN                     NaN                      NaN
1818                    NaN                     NaN                      NaN
1819                    NaN                     NaN                      NaN
1820                    NaN                     NaN                      NaN
1821                    NaN                     NaN                      NaN
1822                    NaN                     NaN                      NaN
1823                    NaN                     NaN                      NaN
1824                    NaN                     NaN                      NaN
1825                    NaN                     NaN                      NaN
1826                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1805                      NaN                   NaN                      NaN
1806                      NaN                   NaN                      NaN
1807                      NaN                   NaN                      NaN
1808                      NaN                   NaN                      NaN
1809                      NaN                   NaN                      NaN
1810                      NaN                   NaN                      NaN
1811                      NaN                   NaN                      NaN
1812                      NaN                   NaN                      NaN
1813                      NaN                   NaN                      NaN
1814                      NaN                   NaN                      NaN
1815                      NaN                   NaN                      NaN
1816                      NaN                   NaN                      NaN
1817                      NaN                   NaN                      NaN
1818                      NaN                   NaN                      NaN
1819                      NaN                   NaN                      NaN
1820                      NaN                   NaN                      NaN
1821                      NaN                   NaN                      NaN
1822                      NaN                   NaN                      NaN
1823                      NaN                   NaN                      NaN
1824                      NaN                   NaN                      NaN
1825                      NaN                   NaN                      NaN
1826                      NaN                   NaN                      NaN

      population_growth
1805                NaN
1806                NaN
1807                NaN
1808                NaN
1809                NaN
1810                NaN
1811                NaN
1812                NaN
1813                NaN
1814                NaN
1815                NaN
1816                NaN
1817                NaN
1818                NaN
1819                NaN
1820                NaN
1821                NaN
1822                NaN
1823                NaN
1824                NaN
1825                NaN
1826                NaN

[22 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NM       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1827               35                 0              35000                 NM
1828               35                 1              35001                 NM
1829               35                 3              35003                 NM
1830               35                 5              35005                 NM
1831               35                 6              35006                 NM
1832               35                 7              35007                 NM
1833               35                 9              35009                 NM
1834               35                11              35011                 NM
1835               35                13              35013                 NM
1836               35                15              35015                 NM
1837               35                17              35017                 NM
1838               35                19              35019                 NM
1839               35                21              35021                 NM
1840               35                23              35023                 NM
1841               35                25              35025                 NM
1842               35                27              35027                 NM
1843               35                28              35028                 NM
1844               35                29              35029                 NM
1845               35                31              35031                 NM
1846               35                33              35033                 NM
1847               35                35              35035                 NM
1848               35                37              35037                 NM
1849               35                39              35039                 NM
1850               35                41              35041                 NM
1851               35                43              35043                 NM
1852               35                45              35045                 NM
1853               35                47              35047                 NM
1854               35                49              35049                 NM
1855               35                51              35051                 NM
1856               35                53              35053                 NM
1857               35                55              35055                 NM
1858               35                57              35057                 NM
1859               35                59              35059                 NM
1860               35                61              35061                 NM

                   name  premature_death  premature_death_black  \
1827         New Mexico      8799.841598                    NaN
1828  Bernalillo County      8098.048866            9341.645120
1829      Catron County      8304.018177                    NaN
1830      Chaves County      9905.061410           14404.210369
1831      Cibola County     10697.646374                    NaN
1832      Colfax County     10003.607825                    NaN
1833       Curry County      9105.064419           14509.041070
1834      DeBaca County     14021.405991                    NaN
1835    Dona Ana County      6880.075188            7894.388571
1836        Eddy County     10267.602783                    NaN
1837       Grant County      9206.179124                    NaN
1838   Guadalupe County     11746.225058                    NaN
1839     Harding County              NaN                    NaN
1840     Hidalgo County      8937.127056                    NaN
1841         Lea County      9076.703917           15930.752199
1842     Lincoln County     11736.167695                    NaN
1843  Los Alamos County      4370.988757                    NaN
1844        Luna County     10170.662142                    NaN
1845    McKinley County     15257.189933                    NaN
1846        Mora County     12250.735512                    NaN
1847       Otero County      8728.205792            8455.900205
1848        Quay County     12247.851296                    NaN
1849  Rio Arriba County     15556.899599                    NaN
1850   Roosevelt County      8262.914484                    NaN
1851    Sandoval County      7060.925409            7193.351494
1852    San Juan County     11302.045374                    NaN
1853  San Miguel County     10311.796422                    NaN
1854    Santa Fe County      7239.574328                    NaN
1855      Sierra County     12966.810842                    NaN
1856     Socorro County     10202.103942                    NaN
1857        Taos County      9389.161760                    NaN
1858    Torrance County      9770.642431                    NaN
1859       Union County      5303.146650                    NaN
1860    Valencia County      9022.805013                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1827                       NaN                    NaN             0.208309
1828               8451.168223            7323.900639             0.185427
1829                       NaN                    NaN             0.164162
1830               9115.609312           11135.983484             0.224842
1831               7254.602027            9284.948355             0.240052
1832              11520.280647            8937.604304             0.219017
1833               8629.592682            8890.085036             0.213645
1834                       NaN                    NaN             0.209586
1835               6713.758470            7001.884079             0.232384
1836               9325.986128           11279.196771             0.173540
1837               8092.414649           11171.721165             0.213916
1838                       NaN                    NaN             0.239232
1839                       NaN                    NaN             0.191645
1840               8760.592217            8151.941857             0.240416
1841               7121.255363           10650.003881             0.208735
1842              10580.490829           12073.610162             0.166332
1843                       NaN                    NaN             0.097999
1844               8092.311998           14771.698745             0.276724
1845              10279.515078            9036.874246             0.261603
1846                       NaN                    NaN             0.347382
1847               6861.160156            9088.772480             0.204128
1848              13663.926147           10783.959572             0.210140
1849              15103.204060           13476.888729             0.269754
1850               8720.105160            7419.464089             0.213511
1851               6151.905779            5518.744215             0.169514
1852               6938.419405            8312.624775             0.193344
1853              10400.716391            9733.739685             0.293643
1854               7985.453255            5844.556128             0.146361
1855              12334.095036           12668.405631             0.217589
1856              11144.715558            8721.481593             0.251431
1857              10190.409725            7200.853993             0.225909
1858              10004.994366            9427.195351             0.234182
1859               8383.142699            3086.341107             0.197990
1860               8953.320444            8763.331582             0.221024

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1827  ...                    NaN                    NaN                 NaN
1828  ...                    NaN                    NaN                 NaN
1829  ...                    NaN                    NaN                 NaN
1830  ...                    NaN                    NaN                 NaN
1831  ...                    NaN                    NaN                 NaN
1832  ...                    NaN                    NaN                 NaN
1833  ...                    NaN                    NaN                 NaN
1834  ...                    NaN                    NaN                 NaN
1835  ...                    NaN                    NaN                 NaN
1836  ...                    NaN                    NaN                 NaN
1837  ...                    NaN                    NaN                 NaN
1838  ...                    NaN                    NaN                 NaN
1839  ...                    NaN                    NaN                 NaN
1840  ...                    NaN                    NaN                 NaN
1841  ...                    NaN                    NaN                 NaN
1842  ...                    NaN                    NaN                 NaN
1843  ...                    NaN                    NaN                 NaN
1844  ...                    NaN                    NaN                 NaN
1845  ...                    NaN                    NaN                 NaN
1846  ...                    NaN                    NaN                 NaN
1847  ...                    NaN                    NaN                 NaN
1848  ...                    NaN                    NaN                 NaN
1849  ...                    NaN                    NaN                 NaN
1850  ...                    NaN                    NaN                 NaN
1851  ...                    NaN                    NaN                 NaN
1852  ...                    NaN                    NaN                 NaN
1853  ...                    NaN                    NaN                 NaN
1854  ...                    NaN                    NaN                 NaN
1855  ...                    NaN                    NaN                 NaN
1856  ...                    NaN                    NaN                 NaN
1857  ...                    NaN                    NaN                 NaN
1858  ...                    NaN                    NaN                 NaN
1859  ...                    NaN                    NaN                 NaN
1860  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1827                    NaN                     NaN                      NaN
1828                    NaN                     NaN                      NaN
1829                    NaN                     NaN                      NaN
1830                    NaN                     NaN                      NaN
1831                    NaN                     NaN                      NaN
1832                    NaN                     NaN                      NaN
1833                    NaN                     NaN                      NaN
1834                    NaN                     NaN                      NaN
1835                    NaN                     NaN                      NaN
1836                    NaN                     NaN                      NaN
1837                    NaN                     NaN                      NaN
1838                    NaN                     NaN                      NaN
1839                    NaN                     NaN                      NaN
1840                    NaN                     NaN                      NaN
1841                    NaN                     NaN                      NaN
1842                    NaN                     NaN                      NaN
1843                    NaN                     NaN                      NaN
1844                    NaN                     NaN                      NaN
1845                    NaN                     NaN                      NaN
1846                    NaN                     NaN                      NaN
1847                    NaN                     NaN                      NaN
1848                    NaN                     NaN                      NaN
1849                    NaN                     NaN                      NaN
1850                    NaN                     NaN                      NaN
1851                    NaN                     NaN                      NaN
1852                    NaN                     NaN                      NaN
1853                    NaN                     NaN                      NaN
1854                    NaN                     NaN                      NaN
1855                    NaN                     NaN                      NaN
1856                    NaN                     NaN                      NaN
1857                    NaN                     NaN                      NaN
1858                    NaN                     NaN                      NaN
1859                    NaN                     NaN                      NaN
1860                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1827                      NaN                   NaN                      NaN
1828                      NaN                   NaN                      NaN
1829                      NaN                   NaN                      NaN
1830                      NaN                   NaN                      NaN
1831                      NaN                   NaN                      NaN
1832                      NaN                   NaN                      NaN
1833                      NaN                   NaN                      NaN
1834                      NaN                   NaN                      NaN
1835                      NaN                   NaN                      NaN
1836                      NaN                   NaN                      NaN
1837                      NaN                   NaN                      NaN
1838                      NaN                   NaN                      NaN
1839                      NaN                   NaN                      NaN
1840                      NaN                   NaN                      NaN
1841                      NaN                   NaN                      NaN
1842                      NaN                   NaN                      NaN
1843                      NaN                   NaN                      NaN
1844                      NaN                   NaN                      NaN
1845                      NaN                   NaN                      NaN
1846                      NaN                   NaN                      NaN
1847                      NaN                   NaN                      NaN
1848                      NaN                   NaN                      NaN
1849                      NaN                   NaN                      NaN
1850                      NaN                   NaN                      NaN
1851                      NaN                   NaN                      NaN
1852                      NaN                   NaN                      NaN
1853                      NaN                   NaN                      NaN
1854                      NaN                   NaN                      NaN
1855                      NaN                   NaN                      NaN
1856                      NaN                   NaN                      NaN
1857                      NaN                   NaN                      NaN
1858                      NaN                   NaN                      NaN
1859                      NaN                   NaN                      NaN
1860                      NaN                   NaN                      NaN

      population_growth
1827                NaN
1828                NaN
1829                NaN
1830                NaN
1831                NaN
1832                NaN
1833                NaN
1834                NaN
1835                NaN
1836                NaN
1837                NaN
1838                NaN
1839                NaN
1840                NaN
1841                NaN
1842                NaN
1843                NaN
1844                NaN
1845                NaN
1846                NaN
1847                NaN
1848                NaN
1849                NaN
1850                NaN
1851                NaN
1852                NaN
1853                NaN
1854                NaN
1855                NaN
1856                NaN
1857                NaN
1858                NaN
1859                NaN
1860                NaN

[34 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NY       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1861               36                 0              36000                 NY
1862               36                 1              36001                 NY
1863               36                 3              36003                 NY
1864               36                 5              36005                 NY
1865               36                 7              36007                 NY
...               ...               ...                ...                ...
1919               36               115              36115                 NY
1920               36               117              36117                 NY
1921               36               119              36119                 NY
1922               36               121              36121                 NY
1923               36               123              36123                 NY

                    name  premature_death  premature_death_black  \
1861            New York      5427.815967                    NaN
1862       Albany County      5690.437960            8849.761761
1863     Allegany County      6617.281692                    NaN
1864        Bronx County      6650.653237            8212.283298
1865       Broome County      7609.167680           10722.194239
...                  ...              ...                    ...
1919   Washington County      6609.146990                    NaN
1920        Wayne County      7112.301777           16976.668038
1921  Westchester County      4144.305550            6855.794051
1922      Wyoming County      6255.493591                    NaN
1923        Yates County      6583.428279                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1861                       NaN                    NaN             0.161051
1862               5100.106601            5492.257616             0.134795
1863                       NaN                    NaN             0.149084
1864               5524.116442            7749.080350             0.268377
1865               6966.875198            7600.208478             0.172002
...                        ...                    ...                  ...
1919                       NaN                    NaN             0.142760
1920                       NaN            6956.401400             0.162759
1921               3038.636973            4055.682939             0.142811
1922                       NaN                    NaN             0.161984
1923                       NaN                    NaN             0.128683

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1861  ...                    NaN                    NaN                 NaN
1862  ...                    NaN                    NaN                 NaN
1863  ...                    NaN                    NaN                 NaN
1864  ...                    NaN                    NaN                 NaN
1865  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
1919  ...                    NaN                    NaN                 NaN
1920  ...                    NaN                    NaN                 NaN
1921  ...                    NaN                    NaN                 NaN
1922  ...                    NaN                    NaN                 NaN
1923  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1861                    NaN                     NaN                      NaN
1862                    NaN                     NaN                      NaN
1863                    NaN                     NaN                      NaN
1864                    NaN                     NaN                      NaN
1865                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
1919                    NaN                     NaN                      NaN
1920                    NaN                     NaN                      NaN
1921                    NaN                     NaN                      NaN
1922                    NaN                     NaN                      NaN
1923                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1861                      NaN                   NaN                      NaN
1862                      NaN                   NaN                      NaN
1863                      NaN                   NaN                      NaN
1864                      NaN                   NaN                      NaN
1865                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
1919                      NaN                   NaN                      NaN
1920                      NaN                   NaN                      NaN
1921                      NaN                   NaN                      NaN
1922                      NaN                   NaN                      NaN
1923                      NaN                   NaN                      NaN

      population_growth
1861                NaN
1862                NaN
1863                NaN
1864                NaN
1865                NaN
...                 ...
1919                NaN
1920                NaN
1921                NaN
1922                NaN
1923                NaN

[63 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of NC       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
1924               37                 0              37000                 NC
1925               37                 1              37001                 NC
1926               37                 3              37003                 NC
1927               37                 5              37005                 NC
1928               37                 7              37007                 NC
...               ...               ...                ...                ...
2020               37               191              37191                 NC
2021               37               193              37193                 NC
2022               37               195              37195                 NC
2023               37               197              37197                 NC
2024               37               199              37199                 NC

                  name  premature_death  premature_death_black  \
1924    North Carolina      7611.233154                    NaN
1925   Alamance County      7833.424570           10945.899742
1926  Alexander County      8854.341333            8028.680078
1927  Alleghany County      8192.516474                    NaN
1928      Anson County     10903.792402           13147.909358
...                ...              ...                    ...
2020      Wayne County      8914.638277           12106.602939
2021     Wilkes County      9447.502234           12365.092688
2022     Wilson County      9909.509196           12412.745206
2023     Yadkin County      8148.981398            9848.191234
2024     Yancey County      7903.535832                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
1924                       NaN                    NaN             0.175660
1925               3432.564793            7594.311030             0.196462
1926                       NaN            8833.543511             0.172967
1927                       NaN                    NaN             0.188724
1928                       NaN            9088.246312             0.228831
...                        ...                    ...                  ...
2020               5352.905986            7585.642832             0.209564
2021                       NaN            9485.918573             0.185148
2022               5455.174602            8791.953253             0.209086
2023                       NaN            8602.671585             0.181430
2024                       NaN                    NaN             0.169864

      ...  male_population_18_44  male_population_45_64  male_population_65  \
1924  ...                    NaN                    NaN                 NaN
1925  ...                    NaN                    NaN                 NaN
1926  ...                    NaN                    NaN                 NaN
1927  ...                    NaN                    NaN                 NaN
1928  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2020  ...                    NaN                    NaN                 NaN
2021  ...                    NaN                    NaN                 NaN
2022  ...                    NaN                    NaN                 NaN
2023  ...                    NaN                    NaN                 NaN
2024  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
1924                    NaN                     NaN                      NaN
1925                    NaN                     NaN                      NaN
1926                    NaN                     NaN                      NaN
1927                    NaN                     NaN                      NaN
1928                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2020                    NaN                     NaN                      NaN
2021                    NaN                     NaN                      NaN
2022                    NaN                     NaN                      NaN
2023                    NaN                     NaN                      NaN
2024                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
1924                      NaN                   NaN                      NaN
1925                      NaN                   NaN                      NaN
1926                      NaN                   NaN                      NaN
1927                      NaN                   NaN                      NaN
1928                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2020                      NaN                   NaN                      NaN
2021                      NaN                   NaN                      NaN
2022                      NaN                   NaN                      NaN
2023                      NaN                   NaN                      NaN
2024                      NaN                   NaN                      NaN

      population_growth
1924                NaN
1925                NaN
1926                NaN
1927                NaN
1928                NaN
...                 ...
2020                NaN
2021                NaN
2022                NaN
2023                NaN
2024                NaN

[101 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of ND       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2025               38                 0              38000                 ND
2026               38                 1              38001                 ND
2027               38                 3              38003                 ND
2028               38                 5              38005                 ND
2029               38                 7              38007                 ND
2030               38                 9              38009                 ND
2031               38                11              38011                 ND
2032               38                13              38013                 ND
2033               38                15              38015                 ND
2034               38                17              38017                 ND
2035               38                19              38019                 ND
2036               38                21              38021                 ND
2037               38                23              38023                 ND
2038               38                25              38025                 ND
2039               38                27              38027                 ND
2040               38                29              38029                 ND
2041               38                31              38031                 ND
2042               38                33              38033                 ND
2043               38                35              38035                 ND
2044               38                37              38037                 ND
2045               38                39              38039                 ND
2046               38                41              38041                 ND
2047               38                43              38043                 ND
2048               38                45              38045                 ND
2049               38                47              38047                 ND
2050               38                49              38049                 ND
2051               38                51              38051                 ND
2052               38                53              38053                 ND
2053               38                55              38055                 ND
2054               38                57              38057                 ND
2055               38                59              38059                 ND
2056               38                61              38061                 ND
2057               38                63              38063                 ND
2058               38                65              38065                 ND
2059               38                67              38067                 ND
2060               38                69              38069                 ND
2061               38                71              38071                 ND
2062               38                73              38073                 ND
2063               38                75              38075                 ND
2064               38                77              38077                 ND
2065               38                79              38079                 ND
2066               38                81              38081                 ND
2067               38                83              38083                 ND
2068               38                85              38085                 ND
2069               38                87              38087                 ND
2070               38                89              38089                 ND
2071               38                91              38091                 ND
2072               38                93              38093                 ND
2073               38                95              38095                 ND
2074               38                97              38097                 ND
2075               38                99              38099                 ND
2076               38               101              38101                 ND
2077               38               103              38103                 ND
2078               38               105              38105                 ND

                      name  premature_death  premature_death_black  \
2025          North Dakota      6679.190265                    NaN
2026          Adams County      8627.131706                    NaN
2027         Barnes County      6581.125323                    NaN
2028         Benson County     16817.785215                    NaN
2029       Billings County              NaN                    NaN
2030      Bottineau County      9947.453494                    NaN
2031         Bowman County      4033.188352                    NaN
2032          Burke County      5755.250996                    NaN
2033       Burleigh County      5992.923352                    NaN
2034           Cass County      5461.957241            8923.077841
2035       Cavalier County      7541.420130                    NaN
2036         Dickey County      5227.559921                    NaN
2037         Divide County      9839.552626                    NaN
2038           Dunn County     10816.752774                    NaN
2039           Eddy County      7267.279203                    NaN
2040         Emmons County      6694.906119                    NaN
2041         Foster County      8635.702311                    NaN
2042  Golden Valley County      8245.958980                    NaN
2043    Grand Forks County      5739.935323                    NaN
2044          Grant County      4824.865229                    NaN
2045         Griggs County      6476.493068                    NaN
2046      Hettinger County      5048.364083                    NaN
2047         Kidder County      5285.482845                    NaN
2048        LaMoure County      6259.019970                    NaN
2049          Logan County      9153.736081                    NaN
2050        McHenry County      7792.813190                    NaN
2051       McIntosh County      5881.336197                    NaN
2052       McKenzie County      9388.777482                    NaN
2053         McLean County      9021.349856                    NaN
2054         Mercer County      6628.063044                    NaN
2055         Morton County      7161.620516                    NaN
2056      Mountrail County     13214.185732                    NaN
2057         Nelson County      8015.880523                    NaN
2058         Oliver County              NaN                    NaN
2059        Pembina County      6342.643444                    NaN
2060         Pierce County      6263.835280                    NaN
2061         Ramsey County      8093.499076                    NaN
2062         Ransom County      8665.758500                    NaN
2063       Renville County      5649.606021                    NaN
2064       Richland County      7504.628099                    NaN
2065        Rolette County     13622.824212                    NaN
2066        Sargent County      6417.415760                    NaN
2067       Sheridan County              NaN                    NaN
2068          Sioux County     26337.366030                    NaN
2069          Slope County              NaN                    NaN
2070          Stark County      6185.702383                    NaN
2071         Steele County      5983.234863                    NaN
2072       Stutsman County      7488.474495                    NaN
2073         Towner County      6140.387708                    NaN
2074         Traill County      8509.587728                    NaN
2075          Walsh County      8090.243044                    NaN
2076           Ward County      5579.987351                    NaN
2077          Wells County      6700.223748                    NaN
2078       Williams County      6810.453388                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2025                       NaN                    NaN             0.143112
2026                       NaN                    NaN             0.124584
2027                       NaN                    NaN             0.123970
2028                       NaN                    NaN             0.253279
2029                       NaN                    NaN             0.117218
2030                       NaN                    NaN             0.132153
2031                       NaN                    NaN             0.108017
2032                       NaN                    NaN             0.133554
2033                       NaN                    NaN             0.120279
2034               7232.906781            5090.383136             0.121513
2035                       NaN                    NaN             0.111565
2036                       NaN                    NaN             0.123764
2037                       NaN                    NaN             0.120382
2038                       NaN                    NaN             0.129168
2039                       NaN                    NaN             0.139515
2040                       NaN                    NaN             0.131040
2041                       NaN                    NaN             0.128226
2042                       NaN                    NaN             0.133484
2043                       NaN                    NaN             0.142291
2044                       NaN                    NaN             0.139001
2045                       NaN                    NaN             0.110572
2046                       NaN                    NaN             0.121973
2047                       NaN                    NaN             0.121038
2048                       NaN                    NaN             0.125520
2049                       NaN                    NaN             0.109881
2050                       NaN                    NaN             0.125698
2051                       NaN                    NaN             0.140097
2052                       NaN                    NaN             0.143512
2053                       NaN                    NaN             0.125085
2054                       NaN                    NaN             0.111587
2055                       NaN                    NaN             0.113421
2056                       NaN                    NaN             0.140704
2057                       NaN                    NaN             0.128360
2058                       NaN                    NaN             0.110737
2059                       NaN                    NaN             0.130007
2060                       NaN                    NaN             0.144067
2061                       NaN                    NaN             0.130789
2062                       NaN                    NaN             0.126695
2063                       NaN                    NaN             0.120143
2064                       NaN                    NaN             0.128077
2065                       NaN                    NaN             0.265947
2066                       NaN                    NaN             0.119825
2067                       NaN                    NaN             0.153660
2068                       NaN                    NaN             0.321230
2069                       NaN                    NaN             0.123549
2070                       NaN                    NaN             0.112073
2071                       NaN                    NaN             0.111555
2072                       NaN                    NaN             0.132056
2073                       NaN                    NaN             0.146584
2074                       NaN                    NaN             0.114494
2075                       NaN                    NaN             0.148329
2076               7595.379198            5184.786374             0.135586
2077                       NaN                    NaN             0.127076
2078                       NaN                    NaN             0.123068

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2025  ...                    NaN                    NaN                 NaN
2026  ...                    NaN                    NaN                 NaN
2027  ...                    NaN                    NaN                 NaN
2028  ...                    NaN                    NaN                 NaN
2029  ...                    NaN                    NaN                 NaN
2030  ...                    NaN                    NaN                 NaN
2031  ...                    NaN                    NaN                 NaN
2032  ...                    NaN                    NaN                 NaN
2033  ...                    NaN                    NaN                 NaN
2034  ...                    NaN                    NaN                 NaN
2035  ...                    NaN                    NaN                 NaN
2036  ...                    NaN                    NaN                 NaN
2037  ...                    NaN                    NaN                 NaN
2038  ...                    NaN                    NaN                 NaN
2039  ...                    NaN                    NaN                 NaN
2040  ...                    NaN                    NaN                 NaN
2041  ...                    NaN                    NaN                 NaN
2042  ...                    NaN                    NaN                 NaN
2043  ...                    NaN                    NaN                 NaN
2044  ...                    NaN                    NaN                 NaN
2045  ...                    NaN                    NaN                 NaN
2046  ...                    NaN                    NaN                 NaN
2047  ...                    NaN                    NaN                 NaN
2048  ...                    NaN                    NaN                 NaN
2049  ...                    NaN                    NaN                 NaN
2050  ...                    NaN                    NaN                 NaN
2051  ...                    NaN                    NaN                 NaN
2052  ...                    NaN                    NaN                 NaN
2053  ...                    NaN                    NaN                 NaN
2054  ...                    NaN                    NaN                 NaN
2055  ...                    NaN                    NaN                 NaN
2056  ...                    NaN                    NaN                 NaN
2057  ...                    NaN                    NaN                 NaN
2058  ...                    NaN                    NaN                 NaN
2059  ...                    NaN                    NaN                 NaN
2060  ...                    NaN                    NaN                 NaN
2061  ...                    NaN                    NaN                 NaN
2062  ...                    NaN                    NaN                 NaN
2063  ...                    NaN                    NaN                 NaN
2064  ...                    NaN                    NaN                 NaN
2065  ...                    NaN                    NaN                 NaN
2066  ...                    NaN                    NaN                 NaN
2067  ...                    NaN                    NaN                 NaN
2068  ...                    NaN                    NaN                 NaN
2069  ...                    NaN                    NaN                 NaN
2070  ...                    NaN                    NaN                 NaN
2071  ...                    NaN                    NaN                 NaN
2072  ...                    NaN                    NaN                 NaN
2073  ...                    NaN                    NaN                 NaN
2074  ...                    NaN                    NaN                 NaN
2075  ...                    NaN                    NaN                 NaN
2076  ...                    NaN                    NaN                 NaN
2077  ...                    NaN                    NaN                 NaN
2078  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2025                    NaN                     NaN                      NaN
2026                    NaN                     NaN                      NaN
2027                    NaN                     NaN                      NaN
2028                    NaN                     NaN                      NaN
2029                    NaN                     NaN                      NaN
2030                    NaN                     NaN                      NaN
2031                    NaN                     NaN                      NaN
2032                    NaN                     NaN                      NaN
2033                    NaN                     NaN                      NaN
2034                    NaN                     NaN                      NaN
2035                    NaN                     NaN                      NaN
2036                    NaN                     NaN                      NaN
2037                    NaN                     NaN                      NaN
2038                    NaN                     NaN                      NaN
2039                    NaN                     NaN                      NaN
2040                    NaN                     NaN                      NaN
2041                    NaN                     NaN                      NaN
2042                    NaN                     NaN                      NaN
2043                    NaN                     NaN                      NaN
2044                    NaN                     NaN                      NaN
2045                    NaN                     NaN                      NaN
2046                    NaN                     NaN                      NaN
2047                    NaN                     NaN                      NaN
2048                    NaN                     NaN                      NaN
2049                    NaN                     NaN                      NaN
2050                    NaN                     NaN                      NaN
2051                    NaN                     NaN                      NaN
2052                    NaN                     NaN                      NaN
2053                    NaN                     NaN                      NaN
2054                    NaN                     NaN                      NaN
2055                    NaN                     NaN                      NaN
2056                    NaN                     NaN                      NaN
2057                    NaN                     NaN                      NaN
2058                    NaN                     NaN                      NaN
2059                    NaN                     NaN                      NaN
2060                    NaN                     NaN                      NaN
2061                    NaN                     NaN                      NaN
2062                    NaN                     NaN                      NaN
2063                    NaN                     NaN                      NaN
2064                    NaN                     NaN                      NaN
2065                    NaN                     NaN                      NaN
2066                    NaN                     NaN                      NaN
2067                    NaN                     NaN                      NaN
2068                    NaN                     NaN                      NaN
2069                    NaN                     NaN                      NaN
2070                    NaN                     NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of OH       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2079               39                 0              39000                 OH
2080               39                 1              39001                 OH
2081               39                 3              39003                 OH
2082               39                 5              39005                 OH
2083               39                 7              39007                 OH
...               ...               ...                ...                ...
2163               39               167              39167                 OH
2164               39               169              39169                 OH
2165               39               171              39171                 OH
2166               39               173              39173                 OH
2167               39               175              39175                 OH

                   name  premature_death  premature_death_black  \
2079               Ohio      8491.560531                    NaN
2080       Adams County     12469.382097                    NaN
2081       Allen County      9033.479946           13089.069915
2082     Ashland County      7305.284349                    NaN
2083   Ashtabula County      9578.901815           10774.018785
...                 ...              ...                    ...
2163  Washington County      8809.036760                    NaN
2164       Wayne County      7464.892555           10581.531517
2165    Williams County      7448.820963                    NaN
2166        Wood County      5894.844502            5930.816411
2167     Wyandot County      6736.306266                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2079                       NaN                    NaN             0.170421
2080                       NaN                    NaN             0.228399
2081                       NaN            8435.890572             0.174577
2082                       NaN                    NaN             0.157794
2083                       NaN            9742.491638             0.176739
...                        ...                    ...                  ...
2163                       NaN                    NaN             0.182723
2164                       NaN            7588.937298             0.149966
2165                       NaN                    NaN             0.163088
2166               4544.855733            6102.979995             0.156684
2167                       NaN                    NaN             0.159316

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2079  ...                    NaN                    NaN                 NaN
2080  ...                    NaN                    NaN                 NaN
2081  ...                    NaN                    NaN                 NaN
2082  ...                    NaN                    NaN                 NaN
2083  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2163  ...                    NaN                    NaN                 NaN
2164  ...                    NaN                    NaN                 NaN
2165  ...                    NaN                    NaN                 NaN
2166  ...                    NaN                    NaN                 NaN
2167  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2079                    NaN                     NaN                      NaN
2080                    NaN                     NaN                      NaN
2081                    NaN                     NaN                      NaN
2082                    NaN                     NaN                      NaN
2083                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2163                    NaN                     NaN                      NaN
2164                    NaN                     NaN                      NaN
2165                    NaN                     NaN                      NaN
2166                    NaN                     NaN                      NaN
2167                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2079                      NaN                   NaN                      NaN
2080                      NaN                   NaN                      NaN
2081                      NaN                   NaN                      NaN
2082                      NaN                   NaN                      NaN
2083                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2163                      NaN                   NaN                      NaN
2164                      NaN                   NaN                      NaN
2165                      NaN                   NaN                      NaN
2166                      NaN                   NaN                      NaN
2167                      NaN                   NaN                      NaN

      population_growth
2079                NaN
2080                NaN
2081                NaN
2082                NaN
2083                NaN
...                 ...
2163                NaN
2164                NaN
2165                NaN
2166                NaN
2167                NaN

[89 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of OK       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2168               40                 0              40000                 OK
2169               40                 1              40001                 OK
2170               40                 3              40003                 OK
2171               40                 5              40005                 OK
2172               40                 7              40007                 OK
...               ...               ...                ...                ...
2241               40               145              40145                 OK
2242               40               147              40147                 OK
2243               40               149              40149                 OK
2244               40               151              40151                 OK
2245               40               153              40153                 OK

                   name  premature_death  premature_death_black  \
2168           Oklahoma      9331.451575                    NaN
2169       Adair County     12281.743972                    NaN
2170     Alfalfa County      5747.969475                    NaN
2171       Atoka County      9675.943250                    NaN
2172      Beaver County      8581.906301                    NaN
...                 ...              ...                    ...
2241     Wagoner County      7072.727740            7264.834739
2242  Washington County      8279.098388           13740.988129
2243     Washita County     10676.742216                    NaN
2244       Woods County      9654.286584                    NaN
2245    Woodward County      8757.578039                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2168                       NaN                    NaN             0.196221
2169                       NaN                    NaN             0.278696
2170                       NaN                    NaN             0.164138
2171                       NaN                    NaN             0.223362
2172                       NaN                    NaN             0.178327
...                        ...                    ...                  ...
2241               5697.459607            6900.362323             0.164078
2242               8162.355516            8266.287387             0.156927
2243                       NaN                    NaN             0.170450
2244                       NaN                    NaN             0.153122
2245                       NaN                    NaN             0.166765

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2168  ...                    NaN                    NaN                 NaN
2169  ...                    NaN                    NaN                 NaN
2170  ...                    NaN                    NaN                 NaN
2171  ...                    NaN                    NaN                 NaN
2172  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2241  ...                    NaN                    NaN                 NaN
2242  ...                    NaN                    NaN                 NaN
2243  ...                    NaN                    NaN                 NaN
2244  ...                    NaN                    NaN                 NaN
2245  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2168                    NaN                     NaN                      NaN
2169                    NaN                     NaN                      NaN
2170                    NaN                     NaN                      NaN
2171                    NaN                     NaN                      NaN
2172                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2241                    NaN                     NaN                      NaN
2242                    NaN                     NaN                      NaN
2243                    NaN                     NaN                      NaN
2244                    NaN                     NaN                      NaN
2245                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2168                      NaN                   NaN                      NaN
2169                      NaN                   NaN                      NaN
2170                      NaN                   NaN                      NaN
2171                      NaN                   NaN                      NaN
2172                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2241                      NaN                   NaN                      NaN
2242                      NaN                   NaN                      NaN
2243                      NaN                   NaN                      NaN
2244                      NaN                   NaN                      NaN
2245                      NaN                   NaN                      NaN

      population_growth
2168                NaN
2169                NaN
2170                NaN
2171                NaN
2172                NaN
...                 ...
2241                NaN
2242                NaN
2243                NaN
2244                NaN
2245                NaN

[78 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of OR       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2246               41                 0              41000                 OR
2247               41                 1              41001                 OR
2248               41                 3              41003                 OR
2249               41                 5              41005                 OR
2250               41                 7              41007                 OR
2251               41                 9              41009                 OR
2252               41                11              41011                 OR
2253               41                13              41013                 OR
2254               41                15              41015                 OR
2255               41                17              41017                 OR
2256               41                19              41019                 OR
2257               41                21              41021                 OR
2258               41                23              41023                 OR
2259               41                25              41025                 OR
2260               41                27              41027                 OR
2261               41                29              41029                 OR
2262               41                31              41031                 OR
2263               41                33              41033                 OR
2264               41                35              41035                 OR
2265               41                37              41037                 OR
2266               41                39              41039                 OR
2267               41                41              41041                 OR
2268               41                43              41043                 OR
2269               41                45              41045                 OR
2270               41                47              41047                 OR
2271               41                49              41049                 OR
2272               41                51              41051                 OR
2273               41                53              41053                 OR
2274               41                55              41055                 OR
2275               41                57              41057                 OR
2276               41                59              41059                 OR
2277               41                61              41061                 OR
2278               41                63              41063                 OR
2279               41                65              41065                 OR
2280               41                67              41067                 OR
2281               41                69              41069                 OR
2282               41                71              41071                 OR

                   name  premature_death  premature_death_black  \
2246             Oregon      6049.232318                    NaN
2247       Baker County      7421.911533                    NaN
2248      Benton County      4317.025760                    NaN
2249   Clackamas County      5263.382619            8018.070891
2250     Clatsop County      7644.584651                    NaN
2251    Columbia County      6174.975697                    NaN
2252        Coos County      9048.356952                    NaN
2253       Crook County      7663.978097                    NaN
2254       Curry County      8853.101506                    NaN
2255   Deschutes County      4892.576924                    NaN
2256     Douglas County      9229.672876                    NaN
2257     Gilliam County      9241.987873                    NaN
2258       Grant County      8125.912694                    NaN
2259      Harney County      9286.531432                    NaN
2260  Hood River County      4329.457230                    NaN
2261     Jackson County      7071.671409            7096.092260
2262   Jefferson County      8492.008661                    NaN
2263   Josephine County      9126.249317                    NaN
2264     Klamath County      9184.553835                    NaN
2265        Lake County      6428.160785                    NaN
2266        Lane County      6430.048703            9188.081695
2267     Lincoln County      8861.622222                    NaN
2268        Linn County      6704.574849                    NaN
2269     Malheur County      8151.303575                    NaN
2270      Marion County      6329.450127            8305.679664
2271      Morrow County      6002.460313                    NaN
2272   Multnomah County      5911.788181           10527.666551
2273        Polk County      6088.523460                    NaN
2274     Sherman County      8851.445713                    NaN
2275   Tillamook County      7078.876993                    NaN
2276    Umatilla County      7022.931416                    NaN
2277       Union County      7492.520649                    NaN
2278     Wallowa County      7096.497823                    NaN
2279       Wasco County      7426.601313                    NaN
2280  Washington County      4108.891717            5688.504408
2281     Wheeler County              NaN                    NaN
2282     Yamhill County      6271.003771                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2246                       NaN                    NaN             0.158222
2247                       NaN                    NaN             0.138787
2248                       NaN                    NaN             0.132467
2249               3436.690873            5512.044638             0.103718
2250                       NaN                    NaN             0.143010
2251                       NaN                    NaN             0.128689
2252               5860.649045            9196.406873             0.172150
2253                       NaN                    NaN             0.154936
2254                       NaN                    NaN             0.150298
2255               3435.278505            4977.600169             0.138214
2256               6110.712831            9505.863976             0.152707
2257                       NaN                    NaN             0.143053
2258                       NaN                    NaN             0.141793
2259                       NaN                    NaN             0.146077
2260               3573.826694            4694.401790             0.157164
2261               4210.944659            7528.141111             0.133009
2262                       NaN                    NaN             0.190537
2263               5784.982940            9426.949294             0.170930
2264               4822.640901            9511.397818             0.171883
2265                       NaN                    NaN             0.171515
2266               4074.194922            6656.917053             0.139072
2267               4162.668195            9404.023244             0.165663
2268               3913.200528            7012.299072             0.153212
2269               5633.835750            9906.078653             0.205363
2270               4270.365717            7030.342833             0.171904
2271                       NaN                    NaN             0.173508
2272               4082.886496            5813.602724             0.135686
2273               4328.709464            6371.078970             0.147099
2274                       NaN                    NaN             0.139937
2275                       NaN                    NaN             0.145391
2276               4766.806720            7254.561642             0.176820
2277                       NaN                    NaN             0.165655
2278                       NaN                    NaN             0.135853
2279                       NaN                    NaN             0.149079
2280               2986.037747            4410.635316             0.119551
2281                       NaN                    NaN             0.162920
2282               3893.017727            6739.089552             0.149800

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2246  ...                    NaN                    NaN                 NaN
2247  ...                    NaN                    NaN                 NaN
2248  ...                    NaN                    NaN                 NaN
2249  ...                    NaN                    NaN                 NaN
2250  ...                    NaN                    NaN                 NaN
2251  ...                    NaN                    NaN                 NaN
2252  ...                    NaN                    NaN                 NaN
2253  ...                    NaN                    NaN                 NaN
2254  ...                    NaN                    NaN                 NaN
2255  ...                    NaN                    NaN                 NaN
2256  ...                    NaN                    NaN                 NaN
2257  ...                    NaN                    NaN                 NaN
2258  ...                    NaN                    NaN                 NaN
2259  ...                    NaN                    NaN                 NaN
2260  ...                    NaN                    NaN                 NaN
2261  ...                    NaN                    NaN                 NaN
2262  ...                    NaN                    NaN                 NaN
2263  ...                    NaN                    NaN                 NaN
2264  ...                    NaN                    NaN                 NaN
2265  ...                    NaN                    NaN                 NaN
2266  ...                    NaN                    NaN                 NaN
2267  ...                    NaN                    NaN                 NaN
2268  ...                    NaN                    NaN                 NaN
2269  ...                    NaN                    NaN                 NaN
2270  ...                    NaN                    NaN                 NaN
2271  ...                    NaN                    NaN                 NaN
2272  ...                    NaN                    NaN                 NaN
2273  ...                    NaN                    NaN                 NaN
2274  ...                    NaN                    NaN                 NaN
2275  ...                    NaN                    NaN                 NaN
2276  ...                    NaN                    NaN                 NaN
2277  ...                    NaN                    NaN                 NaN
2278  ...                    NaN                    NaN                 NaN
2279  ...                    NaN                    NaN                 NaN
2280  ...                    NaN                    NaN                 NaN
2281  ...                    NaN                    NaN                 NaN
2282  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2246                    NaN                     NaN                      NaN
2247                    NaN                     NaN                      NaN
2248                    NaN                     NaN                      NaN
2249                    NaN                     NaN                      NaN
2250                    NaN                     NaN                      NaN
2251                    NaN                     NaN                      NaN
2252                    NaN                     NaN                      NaN
2253                    NaN                     NaN                      NaN
2254                    NaN                     NaN                      NaN
2255                    NaN                     NaN                      NaN
2256                    NaN                     NaN                      NaN
2257                    NaN                     NaN                      NaN
2258                    NaN                     NaN                      NaN
2259                    NaN                     NaN                      NaN
2260                    NaN                     NaN                      NaN
2261                    NaN                     NaN                      NaN
2262                    NaN                     NaN                      NaN
2263                    NaN                     NaN                      NaN
2264                    NaN                     NaN                      NaN
2265                    NaN                     NaN                      NaN
2266                    NaN                     NaN                      NaN
2267                    NaN                     NaN                      NaN
2268                    NaN                     NaN                      NaN
2269                    NaN                     NaN                      NaN
2270                    NaN                     NaN                      NaN
2271                    NaN                     NaN                      NaN
2272                    NaN                     NaN                      NaN
2273                    NaN                     NaN                      NaN
2274                    NaN                     NaN                      NaN
2275                    NaN                     NaN                      NaN
2276                    NaN                     NaN                      NaN
2277                    NaN                     NaN                      NaN
2278                    NaN                     NaN                      NaN
2279                    NaN                     NaN                      NaN
2280                    NaN                     NaN                      NaN
2281                    NaN                     NaN                      NaN
2282                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2246                      NaN                   NaN                      NaN
2247                      NaN                   NaN                      NaN
2248                      NaN                   NaN                      NaN
2249                      NaN                   NaN                      NaN
2250                      NaN                   NaN                      NaN
2251                      NaN                   NaN                      NaN
2252                      NaN                   NaN                      NaN
2253                      NaN                   NaN                      NaN
2254                      NaN                   NaN                      NaN
2255                      NaN                   NaN                      NaN
2256                      NaN                   NaN                      NaN
2257                      NaN                   NaN                      NaN
2258                      NaN                   NaN                      NaN
2259                      NaN                   NaN                      NaN
2260                      NaN                   NaN                      NaN
2261                      NaN                   NaN                      NaN
2262                      NaN                   NaN                      NaN
2263                      NaN                   NaN                      NaN
2264                      NaN                   NaN                      NaN
2265                      NaN                   NaN                      NaN
2266                      NaN                   NaN                      NaN
2267                      NaN                   NaN                      NaN
2268                      NaN                   NaN                      NaN
2269                      NaN                   NaN                      NaN
2270                      NaN                   NaN                      NaN
2271                      NaN                   NaN                      NaN
2272                      NaN                   NaN                      NaN
2273                      NaN                   NaN                      NaN
2274                      NaN                   NaN                      NaN
2275                      NaN                   NaN                      NaN
2276                      NaN                   NaN                      NaN
2277                      NaN                   NaN                      NaN
2278                      NaN                   NaN                      NaN
2279                      NaN                   NaN                      NaN
2280                      NaN                   NaN                      NaN
2281                      NaN                   NaN                      NaN
2282                      NaN                   NaN                      NaN

      population_growth
2246                NaN
2247                NaN
2248                NaN
2249                NaN
2250                NaN
2251                NaN
2252                NaN
2253                NaN
2254                NaN
2255                NaN
2256                NaN
2257                NaN
2258                NaN
2259                NaN
2260                NaN
2261                NaN
2262                NaN
2263                NaN
2264                NaN
2265                NaN
2266                NaN
2267                NaN
2268                NaN
2269                NaN
2270                NaN
2271                NaN
2272                NaN
2273                NaN
2274                NaN
2275                NaN
2276                NaN
2277                NaN
2278                NaN
2279                NaN
2280                NaN
2281                NaN
2282                NaN

[37 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of PA       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2283               42                 0              42000                 PA
2284               42                 1              42001                 PA
2285               42                 3              42003                 PA
2286               42                 5              42005                 PA
2287               42                 7              42007                 PA
...               ...               ...                ...                ...
2346               42               125              42125                 PA
2347               42               127              42127                 PA
2348               42               129              42129                 PA
2349               42               131              42131                 PA
2350               42               133              42133                 PA

                     name  premature_death  premature_death_black  \
2283         Pennsylvania      7483.098711                    NaN
2284         Adams County      6068.281007            5887.047122
2285     Allegheny County      7994.541214           14119.515520
2286     Armstrong County      9597.369863                    NaN
2287        Beaver County      8820.957620           14958.745713
...                   ...              ...                    ...
2346    Washington County      8881.677709           14797.372220
2347         Wayne County      7496.856284                    NaN
2348  Westmoreland County      8257.805311           14420.956948
2349       Wyoming County      9234.013790                    NaN
2350          York County      7035.539466           10328.664525

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2283                       NaN                    NaN             0.150616
2284               3236.323822            6309.579526             0.132441
2285               3382.673350            7134.957725             0.137426
2286                       NaN                    NaN             0.136655
2287                       NaN            8407.493256             0.136751
...                        ...                    ...                  ...
2346                       NaN            8813.941949             0.124723
2347                       NaN                    NaN             0.147185
2348               5634.958617            8116.406430             0.122823
2349                       NaN                    NaN             0.130599
2350               6884.667534            6889.713627             0.130855

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2283  ...                    NaN                    NaN                 NaN
2284  ...                    NaN                    NaN                 NaN
2285  ...                    NaN                    NaN                 NaN
2286  ...                    NaN                    NaN                 NaN
2287  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2346  ...                    NaN                    NaN                 NaN
2347  ...                    NaN                    NaN                 NaN
2348  ...                    NaN                    NaN                 NaN
2349  ...                    NaN                    NaN                 NaN
2350  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2283                    NaN                     NaN                      NaN
2284                    NaN                     NaN                      NaN
2285                    NaN                     NaN                      NaN
2286                    NaN                     NaN                      NaN
2287                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2346                    NaN                     NaN                      NaN
2347                    NaN                     NaN                      NaN
2348                    NaN                     NaN                      NaN
2349                    NaN                     NaN                      NaN
2350                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2283                      NaN                   NaN                      NaN
2284                      NaN                   NaN                      NaN
2285                      NaN                   NaN                      NaN
2286                      NaN                   NaN                      NaN
2287                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2346                      NaN                   NaN                      NaN
2347                      NaN                   NaN                      NaN
2348                      NaN                   NaN                      NaN
2349                      NaN                   NaN                      NaN
2350                      NaN                   NaN                      NaN

      population_growth
2283                NaN
2284                NaN
2285                NaN
2286                NaN
2287                NaN
...                 ...
2346                NaN
2347                NaN
2348                NaN
2349                NaN
2350                NaN

[68 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of RI       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2351               44                 0              44000                 RI
2352               44                 1              44001                 RI
2353               44                 3              44003                 RI
2354               44                 5              44005                 RI
2355               44                 7              44007                 RI
2356               44                 9              44009                 RI

                   name  premature_death  premature_death_black  \
2351       Rhode Island      6123.109508                    NaN
2352     Bristol County      4172.822384                    NaN
2353        Kent County      6535.376024            7189.184771
2354     Newport County      5336.723199            8544.810005
2355  Providence County      6448.310786            7571.590638
2356  Washington County      5264.947662                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2351                       NaN                    NaN             0.148401
2352                       NaN                    NaN             0.102098
2353                       NaN            6863.190997             0.119076
2354                       NaN            5044.434770             0.110118
2355               4270.743509            6997.365742             0.165021
2356                       NaN                    NaN             0.112581

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2351  ...                    NaN                    NaN                 NaN
2352  ...                    NaN                    NaN                 NaN
2353  ...                    NaN                    NaN                 NaN
2354  ...                    NaN                    NaN                 NaN
2355  ...                    NaN                    NaN                 NaN
2356  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2351                    NaN                     NaN                      NaN
2352                    NaN                     NaN                      NaN
2353                    NaN                     NaN                      NaN
2354                    NaN                     NaN                      NaN
2355                    NaN                     NaN                      NaN
2356                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2351                      NaN                   NaN                      NaN
2352                      NaN                   NaN                      NaN
2353                      NaN                   NaN                      NaN
2354                      NaN                   NaN                      NaN
2355                      NaN                   NaN                      NaN
2356                      NaN                   NaN                      NaN

      population_growth
2351                NaN
2352                NaN
2353                NaN
2354                NaN
2355                NaN
2356                NaN

[6 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of SC       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2357               45                 0              45000                 SC
2358               45                 1              45001                 SC
2359               45                 3              45003                 SC
2360               45                 5              45005                 SC
2361               45                 7              45007                 SC
2362               45                 9              45009                 SC
2363               45                11              45011                 SC
2364               45                13              45013                 SC
2365               45                15              45015                 SC
2366               45                17              45017                 SC
2367               45                19              45019                 SC
2368               45                21              45021                 SC
2369               45                23              45023                 SC
2370               45                25              45025                 SC
2371               45                27              45027                 SC
2372               45                29              45029                 SC
2373               45                31              45031                 SC
2374               45                33              45033                 SC
2375               45                35              45035                 SC
2376               45                37              45037                 SC
2377               45                39              45039                 SC
2378               45                41              45041                 SC
2379               45                43              45043                 SC
2380               45                45              45045                 SC
2381               45                47              45047                 SC
2382               45                49              45049                 SC
2383               45                51              45051                 SC
2384               45                53              45053                 SC
2385               45                55              45055                 SC
2386               45                57              45057                 SC
2387               45                59              45059                 SC
2388               45                61              45061                 SC
2389               45                63              45063                 SC
2390               45                65              45065                 SC
2391               45                67              45067                 SC
2392               45                69              45069                 SC
2393               45                71              45071                 SC
2394               45                73              45073                 SC
2395               45                75              45075                 SC
2396               45                77              45077                 SC
2397               45                79              45079                 SC
2398               45                81              45081                 SC
2399               45                83              45083                 SC
2400               45                85              45085                 SC
2401               45                87              45087                 SC
2402               45                89              45089                 SC
2403               45                91              45091                 SC

                     name  premature_death  premature_death_black  \
2357       South Carolina      8678.136326                    NaN
2358     Abbeville County      9517.898548           12506.617420
2359         Aiken County      8987.440807           10865.918245
2360     Allendale County     11249.709261           12929.539019
2361      Anderson County      9385.874663           10508.987258
2362       Bamberg County     12054.009135           14334.455321
2363      Barnwell County     11082.966425           13570.225208
2364      Beaufort County      5709.048170           11201.062763
2365      Berkeley County      7512.777500            8126.658415
2366       Calhoun County     11289.425825           15427.165272
2367    Charleston County      7189.749228           12332.498668
2368      Cherokee County     10413.262988           11833.435099
2369       Chester County     11108.790379           12331.517182
2370  Chesterfield County     10964.328284           11450.166989
2371     Clarendon County      9744.866717           11421.195233
2372      Colleton County     12825.246678           13181.809471
2373    Darlington County     12045.520541           13356.538024
2374        Dillon County     13827.210499           14077.699336
2375    Dorchester County      7502.914690            9319.151317
2376     Edgefield County      7630.783454            8808.287507
2377     Fairfield County     12062.719714           13995.688589
2378      Florence County     10458.461712           12380.162046
2379    Georgetown County     10407.437435           12182.808278
2380    Greenville County      7419.608933           10337.911917
2381     Greenwood County      9354.929823           11370.338043
2382       Hampton County     11057.122796           12452.208825
2383         Horry County      9645.129179           11935.289892
2384        Jasper County      9441.937568           10999.365360
2385       Kershaw County      9503.139367           11119.205626
2386     Lancaster County      8724.157021           11776.803241
2387       Laurens County     10762.518659           13200.609278
2388           Lee County     13912.814404           15614.971206
2389     Lexington County      7714.521400            8840.868255
2390     McCormick County     11823.697604           11816.468147
2391        Marion County     13422.738422           14290.847254
2392      Marlboro County     14613.556968           13677.903830
2393      Newberry County      9183.765288           12614.151100
2394        Oconee County      9191.781595            8242.803020
2395    Orangeburg County     11181.816907           11834.495725
2396       Pickens County      8418.841743           11825.871663
2397      Richland County      8030.745753            9998.231455
2398        Saluda County      6993.240191            9880.777194
2399   Spartanburg County      9412.766678           10714.076250
2400        Sumter County      9563.507908           11907.099896
2401         Union County     10806.598502           10225.064798
2402  Williamsburg County     12911.261790           14586.970083
2403          York County      7155.168478            9074.315680

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2357                       NaN                    NaN             0.190677
2358                       NaN            8276.161112             0.206688
2359               3530.884382            8802.802116             0.168756
2360                       NaN            6755.035246             0.281820
2361               3023.786923            9527.016691             0.177000
2362                       NaN            9222.222197             0.241417
2363                       NaN            9918.197892             0.228952
2364               2216.383252            4737.069785             0.125913
2365               5070.609195            7695.013666             0.174149
2366                       NaN            8037.246700             0.192691
2367               4358.351047            5353.641565             0.149875
2368                       NaN           10446.973948             0.211713
2369                       NaN           10810.423612             0.214597
2370                       NaN           11352.049485             0.248862
2371                       NaN            8344.955845             0.219702
2372                       NaN           12965.391708             0.224451
2373                       NaN           11231.813289             0.211875
2374                       NaN           14536.828226             0.286375
2375               4281.010226            7045.959901             0.158374
2376                       NaN            7598.469168             0.180067
2377                       NaN            8775.026955             0.223767
2378                       NaN            9317.772000             0.218636
2379                       NaN           10283.378653             0.175798
2380               3430.413796            7241.547658             0.165471
2381                       NaN            8991.189062             0.217966
2382                       NaN            9682.051376             0.212606
2383               4750.934614            9781.826971             0.164361
2384                       NaN            9485.799790             0.232459
2385                       NaN            9215.152487             0.181469
2386                       NaN            8262.107879             0.161579
2387                       NaN           10109.200287             0.216055
2388                       NaN           10264.726484             0.273640
2389               4569.210266            7811.223159             0.164879
2390                       NaN           13990.655155             0.197681
2391                       NaN           12404.416492             0.259985
2392                       NaN           17921.723329             0.247164
2393                       NaN            8462.071300             0.178302
2394                       NaN            9649.929698             0.150828
2395                       NaN           10546.473810             0.210313
2396                       NaN            8412.371427             0.171718
2397               4957.890115            6443.850774             0.151173
2398                       NaN            6513.313975             0.215263
2399               4140.541428            9733.116896             0.184753
2400                       NaN            8077.602752             0.226845
2401                       NaN           11298.399036             0.208892
2402                       NaN           10671.964374             0.251252
2403               3434.593522            7004.517313             0.163079

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2357  ...                    NaN                    NaN                 NaN
2358  ...                    NaN                    NaN                 NaN
2359  ...                    NaN                    NaN                 NaN
2360  ...                    NaN                    NaN                 NaN
2361  ...                    NaN                    NaN                 NaN
2362  ...                    NaN                    NaN                 NaN
2363  ...                    NaN                    NaN                 NaN
2364  ...                    NaN                    NaN                 NaN
2365  ...                    NaN                    NaN                 NaN
2366  ...                    NaN                    NaN                 NaN
2367  ...                    NaN                    NaN                 NaN
2368  ...                    NaN                    NaN                 NaN
2369  ...                    NaN                    NaN                 NaN
2370  ...                    NaN                    NaN                 NaN
2371  ...                    NaN                    NaN                 NaN
2372  ...                    NaN                    NaN                 NaN
2373  ...                    NaN                    NaN                 NaN
2374  ...                    NaN                    NaN                 NaN
2375  ...                    NaN                    NaN                 NaN
2376  ...                    NaN                    NaN                 NaN
2377  ...                    NaN                    NaN                 NaN
2378  ...                    NaN                    NaN                 NaN
2379  ...                    NaN                    NaN                 NaN
2380  ...                    NaN                    NaN                 NaN
2381  ...                    NaN                    NaN                 NaN
2382  ...                    NaN                    NaN                 NaN
2383  ...                    NaN                    NaN                 NaN
2384  ...                    NaN                    NaN                 NaN
2385  ...                    NaN                    NaN                 NaN
2386  ...                    NaN                    NaN                 NaN
2387  ...                    NaN                    NaN                 NaN
2388  ...                    NaN                    NaN                 NaN
2389  ...                    NaN                    NaN                 NaN
2390  ...                    NaN                    NaN                 NaN
2391  ...                    NaN                    NaN                 NaN
2392  ...                    NaN                    NaN                 NaN
2393  ...                    NaN                    NaN                 NaN
2394  ...                    NaN                    NaN                 NaN
2395  ...                    NaN                    NaN                 NaN
2396  ...                    NaN                    NaN                 NaN
2397  ...                    NaN                    NaN                 NaN
2398  ...                    NaN                    NaN                 NaN
2399  ...                    NaN                    NaN                 NaN
2400  ...                    NaN                    NaN                 NaN
2401  ...                    NaN                    NaN                 NaN
2402  ...                    NaN                    NaN                 NaN
2403  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2357                    NaN                     NaN                      NaN
2358                    NaN                     NaN                      NaN
2359                    NaN                     NaN                      NaN
2360                    NaN                     NaN                      NaN
2361                    NaN                     NaN                      NaN
2362                    NaN                     NaN                      NaN
2363                    NaN                     NaN                      NaN
2364                    NaN                     NaN                      NaN
2365                    NaN                     NaN                      NaN
2366                    NaN                     NaN                      NaN
2367                    NaN                     NaN                      NaN
2368                    NaN                     NaN                      NaN
2369                    NaN                     NaN                      NaN
2370                    NaN                     NaN                      NaN
2371                    NaN                     NaN                      NaN
2372                    NaN                     NaN                      NaN
2373                    NaN                     NaN                      NaN
2374                    NaN                     NaN                      NaN
2375                    NaN                     NaN                      NaN
2376                    NaN                     NaN                      NaN
2377                    NaN                     NaN                      NaN
2378                    NaN                     NaN                      NaN
2379                    NaN                     NaN                      NaN
2380                    NaN                     NaN                      NaN
2381                    NaN                     NaN                      NaN
2382                    NaN                     NaN                      NaN
2383                    NaN                     NaN                      NaN
2384                    NaN                     NaN                      NaN
2385                    NaN                     NaN                      NaN
2386                    NaN                     NaN                      NaN
2387                    NaN                     NaN                      NaN
2388                    NaN                     NaN                      NaN
2389                    NaN                     NaN                      NaN
2390                    NaN                     NaN                      NaN
2391                    NaN                     NaN                      NaN
2392                    NaN                     NaN                      NaN
2393                    NaN                     NaN                      NaN
2394                    NaN                     NaN                      NaN
2395                    NaN                     NaN                      NaN
2396                    NaN                     NaN                      NaN
2397                    NaN                     NaN                      NaN
2398                    NaN                     NaN                      NaN
2399                    NaN                     NaN                      NaN
2400                    NaN                     NaN                      NaN
2401                    NaN                     NaN                      NaN
2402                    NaN                     NaN                      NaN
2403                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2357                      NaN                   NaN                      NaN
2358                      NaN                   NaN                      NaN
2359                      NaN                   NaN                      NaN
2360                      NaN                   NaN                      NaN
2361                      NaN                   NaN                      NaN
2362                      NaN                   NaN                      NaN
2363                      NaN                   NaN                      NaN
2364                      NaN                   NaN                      NaN
2365                      NaN                   NaN                      NaN
2366                      NaN                   NaN                      NaN
2367                      NaN                   NaN                      NaN
2368                      NaN                   NaN                      NaN
2369                      NaN                   NaN                      NaN
2370                      NaN                   NaN                      NaN
2371                      NaN                   NaN                      NaN
2372                      NaN                   NaN                      NaN
2373                      NaN                   NaN                      NaN
2374                      NaN                   NaN                      NaN
2375                      NaN                   NaN                      NaN
2376                      NaN                   NaN                      NaN
2377                      NaN                   NaN                      NaN
2378                      NaN                   NaN                      NaN
2379                      NaN                   NaN                      NaN
2380                      NaN                   NaN                      NaN
2381                      NaN                   NaN                      NaN
2382                      NaN                   NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of SD       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2404               46                 0              46000                 SD
2405               46                 3              46003                 SD
2406               46                 5              46005                 SD
2407               46                 7              46007                 SD
2408               46                 9              46009                 SD
...               ...               ...                ...                ...
2466               46               125              46125                 SD
2467               46               127              46127                 SD
2468               46               129              46129                 SD
2469               46               135              46135                 SD
2470               46               137              46137                 SD

                  name  premature_death  premature_death_black  \
2404      South Dakota      7339.778915                    NaN
2405     Aurora County      3179.364514                    NaN
2406     Beadle County      7377.885977                    NaN
2407    Bennett County     18392.044086                    NaN
2408  Bon Homme County      4624.205654                    NaN
...                ...              ...                    ...
2466     Turner County      8039.297634                    NaN
2467      Union County      4602.819796                    NaN
2468   Walworth County      8846.862478                    NaN
2469    Yankton County      7694.488022                    NaN
2470    Ziebach County     13942.582878                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2404                       NaN                    NaN             0.117813
2405                       NaN                    NaN             0.099509
2406                       NaN                    NaN             0.139789
2407                       NaN                    NaN             0.236997
2408                       NaN                    NaN             0.121505
...                        ...                    ...                  ...
2466                       NaN                    NaN             0.107375
2467                       NaN                    NaN             0.094016
2468                       NaN                    NaN             0.113102
2469                       NaN                    NaN             0.124249
2470                       NaN                    NaN             0.284281

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2404  ...                    NaN                    NaN                 NaN
2405  ...                    NaN                    NaN                 NaN
2406  ...                    NaN                    NaN                 NaN
2407  ...                    NaN                    NaN                 NaN
2408  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2466  ...                    NaN                    NaN                 NaN
2467  ...                    NaN                    NaN                 NaN
2468  ...                    NaN                    NaN                 NaN
2469  ...                    NaN                    NaN                 NaN
2470  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2404                    NaN                     NaN                      NaN
2405                    NaN                     NaN                      NaN
2406                    NaN                     NaN                      NaN
2407                    NaN                     NaN                      NaN
2408                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2466                    NaN                     NaN                      NaN
2467                    NaN                     NaN                      NaN
2468                    NaN                     NaN                      NaN
2469                    NaN                     NaN                      NaN
2470                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2404                      NaN                   NaN                      NaN
2405                      NaN                   NaN                      NaN
2406                      NaN                   NaN                      NaN
2407                      NaN                   NaN                      NaN
2408                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2466                      NaN                   NaN                      NaN
2467                      NaN                   NaN                      NaN
2468                      NaN                   NaN                      NaN
2469                      NaN                   NaN                      NaN
2470                      NaN                   NaN                      NaN

      population_growth
2404                NaN
2405                NaN
2406                NaN
2407                NaN
2408                NaN
...                 ...
2466                NaN
2467                NaN
2468                NaN
2469                NaN
2470                NaN

[67 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of TN       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2471               47                 0              47000                 TN
2472               47                 1              47001                 TN
2473               47                 3              47003                 TN
2474               47                 5              47005                 TN
2475               47                 7              47007                 TN
...               ...               ...                ...                ...
2562               47               181              47181                 TN
2563               47               183              47183                 TN
2564               47               185              47185                 TN
2565               47               187              47187                 TN
2566               47               189              47189                 TN

                   name  premature_death  premature_death_black  \
2471          Tennessee      9121.436865                    NaN
2472    Anderson County      9535.894012           11586.112598
2473     Bedford County      9761.767067            9264.933342
2474      Benton County     12828.456636                    NaN
2475     Bledsoe County      7734.611831                    NaN
...                 ...              ...                    ...
2562       Wayne County      8865.400120                    NaN
2563     Weakley County      9598.137589            9839.482343
2564       White County     10575.962195                    NaN
2565  Williamson County      4051.519987            6063.826717
2566      Wilson County      7062.618517            9819.558974

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2471                       NaN                    NaN             0.190936
2472                       NaN            9748.594403             0.190976
2473               4454.298941           10683.394608             0.215416
2474                       NaN                    NaN             0.212046
2475                       NaN                    NaN             0.220262
...                        ...                    ...                  ...
2562                       NaN                    NaN             0.225397
2563                       NaN            9612.377272             0.206748
2564                       NaN                    NaN             0.196904
2565               3131.207717            4092.606426             0.124682
2566               5041.313458            6919.577177             0.148789

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2471  ...                    NaN                    NaN                 NaN
2472  ...                    NaN                    NaN                 NaN
2473  ...                    NaN                    NaN                 NaN
2474  ...                    NaN                    NaN                 NaN
2475  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2562  ...                    NaN                    NaN                 NaN
2563  ...                    NaN                    NaN                 NaN
2564  ...                    NaN                    NaN                 NaN
2565  ...                    NaN                    NaN                 NaN
2566  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2471                    NaN                     NaN                      NaN
2472                    NaN                     NaN                      NaN
2473                    NaN                     NaN                      NaN
2474                    NaN                     NaN                      NaN
2475                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2562                    NaN                     NaN                      NaN
2563                    NaN                     NaN                      NaN
2564                    NaN                     NaN                      NaN
2565                    NaN                     NaN                      NaN
2566                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2471                      NaN                   NaN                      NaN
2472                      NaN                   NaN                      NaN
2473                      NaN                   NaN                      NaN
2474                      NaN                   NaN                      NaN
2475                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2562                      NaN                   NaN                      NaN
2563                      NaN                   NaN                      NaN
2564                      NaN                   NaN                      NaN
2565                      NaN                   NaN                      NaN
2566                      NaN                   NaN                      NaN

      population_growth
2471                NaN
2472                NaN
2473                NaN
2474                NaN
2475                NaN
...                 ...
2562                NaN
2563                NaN
2564                NaN
2565                NaN
2566                NaN

[96 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of TX       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2567               48                 0              48000                 TX
2568               48                 1              48001                 TX
2569               48                 3              48003                 TX
2570               48                 5              48005                 TX
2571               48                 7              48007                 TX
...               ...               ...                ...                ...
2817               48               499              48499                 TX
2818               48               501              48501                 TX
2819               48               503              48503                 TX
2820               48               505              48505                 TX
2821               48               507              48507                 TX

                 name  premature_death  premature_death_black  \
2567            Texas      6681.323364                    NaN
2568  Anderson County     10272.949118           12962.159784
2569   Andrews County      7952.973251                    NaN
2570  Angelina County      9018.498513           14014.161619
2571   Aransas County      9315.870361                    NaN
...               ...              ...                    ...
2817      Wood County      9457.366431           11529.284333
2818    Yoakum County      8031.592211                    NaN
2819     Young County     10234.600248                    NaN
2820    Zapata County      6770.768596                    NaN
2821    Zavala County      9389.759155                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2567                       NaN                    NaN             0.181738
2568              10880.315229            9971.540573             0.195296
2569               7774.144329            8202.896838             0.173077
2570               4450.704830            9293.129659             0.232073
2571               6088.571549           11277.610901             0.195177
...                        ...                    ...                  ...
2817               5200.873212           10111.489999             0.157451
2818               6346.983631           12725.031142             0.212009
2819                       NaN                    NaN             0.164604
2820                       NaN                    NaN             0.354378
2821                       NaN                    NaN             0.395759

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2567  ...                    NaN                    NaN                 NaN
2568  ...                    NaN                    NaN                 NaN
2569  ...                    NaN                    NaN                 NaN
2570  ...                    NaN                    NaN                 NaN
2571  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2817  ...                    NaN                    NaN                 NaN
2818  ...                    NaN                    NaN                 NaN
2819  ...                    NaN                    NaN                 NaN
2820  ...                    NaN                    NaN                 NaN
2821  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2567                    NaN                     NaN                      NaN
2568                    NaN                     NaN                      NaN
2569                    NaN                     NaN                      NaN
2570                    NaN                     NaN                      NaN
2571                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2817                    NaN                     NaN                      NaN
2818                    NaN                     NaN                      NaN
2819                    NaN                     NaN                      NaN
2820                    NaN                     NaN                      NaN
2821                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2567                      NaN                   NaN                      NaN
2568                      NaN                   NaN                      NaN
2569                      NaN                   NaN                      NaN
2570                      NaN                   NaN                      NaN
2571                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2817                      NaN                   NaN                      NaN
2818                      NaN                   NaN                      NaN
2819                      NaN                   NaN                      NaN
2820                      NaN                   NaN                      NaN
2821                      NaN                   NaN                      NaN

      population_growth
2567                NaN
2568                NaN
2569                NaN
2570                NaN
2571                NaN
...                 ...
2817                NaN
2818                NaN
2819                NaN
2820                NaN
2821                NaN

[255 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of UT       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2822               49                 0              49000                 UT
2823               49                 1              49001                 UT
2824               49                 3              49003                 UT
2825               49                 5              49005                 UT
2826               49                 7              49007                 UT
2827               49                 9              49009                 UT
2828               49                11              49011                 UT
2829               49                13              49013                 UT
2830               49                15              49015                 UT
2831               49                17              49017                 UT
2832               49                19              49019                 UT
2833               49                21              49021                 UT
2834               49                23              49023                 UT
2835               49                25              49025                 UT
2836               49                27              49027                 UT
2837               49                29              49029                 UT
2838               49                31              49031                 UT
2839               49                33              49033                 UT
2840               49                35              49035                 UT
2841               49                37              49037                 UT
2842               49                39              49039                 UT
2843               49                41              49041                 UT
2844               49                43              49043                 UT
2845               49                45              49045                 UT
2846               49                47              49047                 UT
2847               49                49              49049                 UT
2848               49                51              49051                 UT
2849               49                53              49053                 UT
2850               49                55              49055                 UT
2851               49                57              49057                 UT

                   name  premature_death  premature_death_black  \
2822               Utah      6090.837929                    NaN
2823      Beaver County      9138.856573                    NaN
2824   Box Elder County      6467.311023                    NaN
2825       Cache County      4798.055960                    NaN
2826      Carbon County     10629.059577                    NaN
2827     Daggett County              NaN                    NaN
2828       Davis County      5101.815387            6474.259543
2829    Duchesne County      9021.356776                    NaN
2830       Emery County      9635.650123                    NaN
2831    Garfield County      8689.140334                    NaN
2832       Grand County      7539.957903                    NaN
2833        Iron County      7252.679839                    NaN
2834        Juab County      6694.825615                    NaN
2835        Kane County      6939.950000                    NaN
2836     Millard County      7046.680892                    NaN
2837      Morgan County      4266.073955                    NaN
2838       Piute County              NaN                    NaN
2839        Rich County      6554.448232                    NaN
2840   Salt Lake County      6384.212970            8517.254642
2841    San Juan County     10683.034890                    NaN
2842     Sanpete County      6198.485541                    NaN
2843      Sevier County      6320.502378                    NaN
2844      Summit County      4287.889442                    NaN
2845      Tooele County      6755.238262                    NaN
2846      Uintah County      7936.034118                    NaN
2847        Utah County      5231.251892            7277.148162
2848     Wasatch County      4961.964940                    NaN
2849  Washington County      6190.548466                    NaN
2850       Wayne County      4250.535995                    NaN
2851       Weber County      7230.684661            9867.666458

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2822                       NaN                    NaN             0.121174
2823                       NaN                    NaN             0.120618
2824               9293.843714            6090.854694             0.126193
2825               4701.787852            4730.365721             0.104034
2826              12387.379168           10687.704110             0.151659
2827                       NaN                    NaN             0.088681
2828               4002.838578            5272.418395             0.105165
2829                       NaN                    NaN             0.140654
2830                       NaN                    NaN             0.135688
2831                       NaN                    NaN             0.143079
2832                       NaN                    NaN             0.141800
2833               7497.438895            7223.457634             0.143577
2834                       NaN                    NaN             0.127379
2835                       NaN                    NaN             0.121403
2836                       NaN                    NaN             0.132301
2837                       NaN                    NaN             0.096516
2838                       NaN                    NaN             0.135677
2839                       NaN                    NaN             0.133091
2840               5211.366998            6655.028574             0.121125
2841                       NaN                    NaN             0.209102
2842                       NaN                    NaN             0.148321
2843                       NaN                    NaN             0.133544
2844                       NaN                    NaN             0.094411
2845               6864.666589            6583.888580             0.141351
2846                       NaN                    NaN             0.142374
2847               3344.501463            5501.912428             0.119228
2848                       NaN                    NaN             0.112492
2849               3719.868187            6429.010750             0.114597
2850                       NaN                    NaN             0.117286
2851               6169.618679            7514.399841             0.136835

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2822  ...                    NaN                    NaN                 NaN
2823  ...                    NaN                    NaN                 NaN
2824  ...                    NaN                    NaN                 NaN
2825  ...                    NaN                    NaN                 NaN
2826  ...                    NaN                    NaN                 NaN
2827  ...                    NaN                    NaN                 NaN
2828  ...                    NaN                    NaN                 NaN
2829  ...                    NaN                    NaN                 NaN
2830  ...                    NaN                    NaN                 NaN
2831  ...                    NaN                    NaN                 NaN
2832  ...                    NaN                    NaN                 NaN
2833  ...                    NaN                    NaN                 NaN
2834  ...                    NaN                    NaN                 NaN
2835  ...                    NaN                    NaN                 NaN
2836  ...                    NaN                    NaN                 NaN
2837  ...                    NaN                    NaN                 NaN
2838  ...                    NaN                    NaN                 NaN
2839  ...                    NaN                    NaN                 NaN
2840  ...                    NaN                    NaN                 NaN
2841  ...                    NaN                    NaN                 NaN
2842  ...                    NaN                    NaN                 NaN
2843  ...                    NaN                    NaN                 NaN
2844  ...                    NaN                    NaN                 NaN
2845  ...                    NaN                    NaN                 NaN
2846  ...                    NaN                    NaN                 NaN
2847  ...                    NaN                    NaN                 NaN
2848  ...                    NaN                    NaN                 NaN
2849  ...                    NaN                    NaN                 NaN
2850  ...                    NaN                    NaN                 NaN
2851  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2822                    NaN                     NaN                      NaN
2823                    NaN                     NaN                      NaN
2824                    NaN                     NaN                      NaN
2825                    NaN                     NaN                      NaN
2826                    NaN                     NaN                      NaN
2827                    NaN                     NaN                      NaN
2828                    NaN                     NaN                      NaN
2829                    NaN                     NaN                      NaN
2830                    NaN                     NaN                      NaN
2831                    NaN                     NaN                      NaN
2832                    NaN                     NaN                      NaN
2833                    NaN                     NaN                      NaN
2834                    NaN                     NaN                      NaN
2835                    NaN                     NaN                      NaN
2836                    NaN                     NaN                      NaN
2837                    NaN                     NaN                      NaN
2838                    NaN                     NaN                      NaN
2839                    NaN                     NaN                      NaN
2840                    NaN                     NaN                      NaN
2841                    NaN                     NaN                      NaN
2842                    NaN                     NaN                      NaN
2843                    NaN                     NaN                      NaN
2844                    NaN                     NaN                      NaN
2845                    NaN                     NaN                      NaN
2846                    NaN                     NaN                      NaN
2847                    NaN                     NaN                      NaN
2848                    NaN                     NaN                      NaN
2849                    NaN                     NaN                      NaN
2850                    NaN                     NaN                      NaN
2851                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2822                      NaN                   NaN                      NaN
2823                      NaN                   NaN                      NaN
2824                      NaN                   NaN                      NaN
2825                      NaN                   NaN                      NaN
2826                      NaN                   NaN                      NaN
2827                      NaN                   NaN                      NaN
2828                      NaN                   NaN                      NaN
2829                      NaN                   NaN                      NaN
2830                      NaN                   NaN                      NaN
2831                      NaN                   NaN                      NaN
2832                      NaN                   NaN                      NaN
2833                      NaN                   NaN                      NaN
2834                      NaN                   NaN                      NaN
2835                      NaN                   NaN                      NaN
2836                      NaN                   NaN                      NaN
2837                      NaN                   NaN                      NaN
2838                      NaN                   NaN                      NaN
2839                      NaN                   NaN                      NaN
2840                      NaN                   NaN                      NaN
2841                      NaN                   NaN                      NaN
2842                      NaN                   NaN                      NaN
2843                      NaN                   NaN                      NaN
2844                      NaN                   NaN                      NaN
2845                      NaN                   NaN                      NaN
2846                      NaN                   NaN                      NaN
2847                      NaN                   NaN                      NaN
2848                      NaN                   NaN                      NaN
2849                      NaN                   NaN                      NaN
2850                      NaN                   NaN                      NaN
2851                      NaN                   NaN                      NaN

      population_growth
2822                NaN
2823                NaN
2824                NaN
2825                NaN
2826                NaN
2827                NaN
2828                NaN
2829                NaN
2830                NaN
2831                NaN
2832                NaN
2833                NaN
2834                NaN
2835                NaN
2836                NaN
2837                NaN
2838                NaN
2839                NaN
2840                NaN
2841                NaN
2842                NaN
2843                NaN
2844                NaN
2845                NaN
2846                NaN
2847                NaN
2848                NaN
2849                NaN
2850                NaN
2851                NaN

[30 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of VT       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2852               50                 0              50000                 VT
2853               50                 1              50001                 VT
2854               50                 3              50003                 VT
2855               50                 5              50005                 VT
2856               50                 7              50007                 VT
2857               50                 9              50009                 VT
2858               50                11              50011                 VT
2859               50                13              50013                 VT
2860               50                15              50015                 VT
2861               50                17              50017                 VT
2862               50                19              50019                 VT
2863               50                21              50021                 VT
2864               50                23              50023                 VT
2865               50                25              50025                 VT
2866               50                27              50027                 VT

                   name  premature_death  premature_death_black  \
2852            Vermont      6081.421931                    NaN
2853     Addison County      3725.057297                    NaN
2854  Bennington County      6928.898903                    NaN
2855   Caledonia County      7140.862817                    NaN
2856  Chittenden County      5005.466048            9614.843473
2857       Essex County     13050.800151                    NaN
2858    Franklin County      6671.921113                    NaN
2859  Grand Isle County      5876.525861                    NaN
2860    Lamoille County      5470.864275                    NaN
2861      Orange County      5928.305043                    NaN
2862     Orleans County      7818.358279                    NaN
2863     Rutland County      7263.985549                    NaN
2864  Washington County      6225.480406                    NaN
2865     Windham County      7299.979054                    NaN
2866     Windsor County      6280.635521                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2852                       NaN                    NaN             0.125073
2853                       NaN                    NaN             0.114137
2854                       NaN                    NaN             0.115792
2855                       NaN                    NaN             0.132702
2856                       NaN            4885.296883             0.100610
2857                       NaN                    NaN             0.162656
2858                       NaN                    NaN             0.119699
2859                       NaN                    NaN             0.107420
2860                       NaN                    NaN             0.106404
2861                       NaN                    NaN             0.116360
2862                       NaN                    NaN             0.143231
2863                       NaN                    NaN             0.119184
2864                       NaN                    NaN             0.104951
2865                       NaN                    NaN             0.113872
2866                       NaN                    NaN             0.107901

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2852  ...                    NaN                    NaN                 NaN
2853  ...                    NaN                    NaN                 NaN
2854  ...                    NaN                    NaN                 NaN
2855  ...                    NaN                    NaN                 NaN
2856  ...                    NaN                    NaN                 NaN
2857  ...                    NaN                    NaN                 NaN
2858  ...                    NaN                    NaN                 NaN
2859  ...                    NaN                    NaN                 NaN
2860  ...                    NaN                    NaN                 NaN
2861  ...                    NaN                    NaN                 NaN
2862  ...                    NaN                    NaN                 NaN
2863  ...                    NaN                    NaN                 NaN
2864  ...                    NaN                    NaN                 NaN
2865  ...                    NaN                    NaN                 NaN
2866  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2852                    NaN                     NaN                      NaN
2853                    NaN                     NaN                      NaN
2854                    NaN                     NaN                      NaN
2855                    NaN                     NaN                      NaN
2856                    NaN                     NaN                      NaN
2857                    NaN                     NaN                      NaN
2858                    NaN                     NaN                      NaN
2859                    NaN                     NaN                      NaN
2860                    NaN                     NaN                      NaN
2861                    NaN                     NaN                      NaN
2862                    NaN                     NaN                      NaN
2863                    NaN                     NaN                      NaN
2864                    NaN                     NaN                      NaN
2865                    NaN                     NaN                      NaN
2866                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2852                      NaN                   NaN                      NaN
2853                      NaN                   NaN                      NaN
2854                      NaN                   NaN                      NaN
2855                      NaN                   NaN                      NaN
2856                      NaN                   NaN                      NaN
2857                      NaN                   NaN                      NaN
2858                      NaN                   NaN                      NaN
2859                      NaN                   NaN                      NaN
2860                      NaN                   NaN                      NaN
2861                      NaN                   NaN                      NaN
2862                      NaN                   NaN                      NaN
2863                      NaN                   NaN                      NaN
2864                      NaN                   NaN                      NaN
2865                      NaN                   NaN                      NaN
2866                      NaN                   NaN                      NaN

      population_growth
2852                NaN
2853                NaN
2854                NaN
2855                NaN
2856                NaN
2857                NaN
2858                NaN
2859                NaN
2860                NaN
2861                NaN
2862                NaN
2863                NaN
2864                NaN
2865                NaN
2866                NaN

[15 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of VA       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
2867               51                 0              51000                 VA
2868               51                 1              51001                 VA
2869               51                 3              51003                 VA
2870               51                 5              51005                 VA
2871               51                 7              51007                 VA
...               ...               ...                ...                ...
2996               51               800              51800                 VA
2997               51               810              51810                 VA
2998               51               820              51820                 VA
2999               51               830              51830                 VA
3000               51               840              51840                 VA

                     name  premature_death  premature_death_black  \
2867             Virginia      6360.326448                    NaN
2868      Accomack County     10459.767289           14925.389610
2869     Albemarle County      3795.755690            5703.361265
2870     Alleghany County      8121.374968            9667.575520
2871        Amelia County      9774.084751           11029.662209
...                   ...              ...                    ...
2996         Suffolk city      6597.743972            7814.924534
2997  Virginia Beach city      5702.405892            7168.159023
2998      Waynesboro city      8713.265575            7300.985947
2999    Williamsburg city      2610.690433                    NaN
3000      Winchester city      7634.098672            8063.747682

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
2867                       NaN                    NaN             0.159169
2868                       NaN            9113.737785             0.200100
2869               3392.750642            3715.088477             0.129452
2870                       NaN            8148.239095             0.164129
2871                       NaN            9093.684036             0.151933
...                        ...                    ...                  ...
2996                       NaN            6125.220225             0.159448
2997               3149.890193            5750.395749             0.127079
2998                       NaN            9553.773144             0.171317
2999                       NaN                    NaN             0.179449
3000                       NaN            8045.845823             0.179555

      ...  male_population_18_44  male_population_45_64  male_population_65  \
2867  ...                    NaN                    NaN                 NaN
2868  ...                    NaN                    NaN                 NaN
2869  ...                    NaN                    NaN                 NaN
2870  ...                    NaN                    NaN                 NaN
2871  ...                    NaN                    NaN                 NaN
...   ...                    ...                    ...                 ...
2996  ...                    NaN                    NaN                 NaN
2997  ...                    NaN                    NaN                 NaN
2998  ...                    NaN                    NaN                 NaN
2999  ...                    NaN                    NaN                 NaN
3000  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
2867                    NaN                     NaN                      NaN
2868                    NaN                     NaN                      NaN
2869                    NaN                     NaN                      NaN
2870                    NaN                     NaN                      NaN
2871                    NaN                     NaN                      NaN
...                     ...                     ...                      ...
2996                    NaN                     NaN                      NaN
2997                    NaN                     NaN                      NaN
2998                    NaN                     NaN                      NaN
2999                    NaN                     NaN                      NaN
3000                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
2867                      NaN                   NaN                      NaN
2868                      NaN                   NaN                      NaN
2869                      NaN                   NaN                      NaN
2870                      NaN                   NaN                      NaN
2871                      NaN                   NaN                      NaN
...                       ...                   ...                      ...
2996                      NaN                   NaN                      NaN
2997                      NaN                   NaN                      NaN
2998                      NaN                   NaN                      NaN
2999                      NaN                   NaN                      NaN
3000                      NaN                   NaN                      NaN

      population_growth
2867                NaN
2868                NaN
2869                NaN
2870                NaN
2871                NaN
...                 ...
2996                NaN
2997                NaN
2998                NaN
2999                NaN
3000                NaN

[134 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of WA       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
3001               53                 0              53000                 WA
3002               53                 1              53001                 WA
3003               53                 3              53003                 WA
3004               53                 5              53005                 WA
3005               53                 7              53007                 WA
3006               53                 9              53009                 WA
3007               53                11              53011                 WA
3008               53                13              53013                 WA
3009               53                15              53015                 WA
3010               53                17              53017                 WA
3011               53                19              53019                 WA
3012               53                21              53021                 WA
3013               53                23              53023                 WA
3014               53                25              53025                 WA
3015               53                27              53027                 WA
3016               53                29              53029                 WA
3017               53                31              53031                 WA
3018               53                33              53033                 WA
3019               53                35              53035                 WA
3020               53                37              53037                 WA
3021               53                39              53039                 WA
3022               53                41              53041                 WA
3023               53                43              53043                 WA
3024               53                45              53045                 WA
3025               53                47              53047                 WA
3026               53                49              53049                 WA
3027               53                51              53051                 WA
3028               53                53              53053                 WA
3029               53                55              53055                 WA
3030               53                57              53057                 WA
3031               53                59              53059                 WA
3032               53                61              53061                 WA
3033               53                63              53063                 WA
3034               53                65              53065                 WA
3035               53                67              53067                 WA
3036               53                69              53069                 WA
3037               53                71              53071                 WA
3038               53                73              53073                 WA
3039               53                75              53075                 WA
3040               53                77              53077                 WA

                     name  premature_death  premature_death_black  \
3001           Washington      5603.333738                    NaN
3002         Adams County      6579.071980                    NaN
3003        Asotin County      7272.540441                    NaN
3004        Benton County      5902.181838            7089.161207
3005        Chelan County      5150.662512                    NaN
3006       Clallam County      7646.528739                    NaN
3007         Clark County      5412.662882            7291.164738
3008      Columbia County     10197.248970                    NaN
3009       Cowlitz County      8470.012397                    NaN
3010       Douglas County      5004.572584                    NaN
3011         Ferry County     10381.430737                    NaN
3012      Franklin County      4469.743544                    NaN
3013      Garfield County      4672.577520                    NaN
3014         Grant County      6712.805217                    NaN
3015  Grays Harbor County      8848.136657                    NaN
3016        Island County      5723.357433            8053.280932
3017     Jefferson County      7104.496797                    NaN
3018          King County      4455.961040            7995.113237
3019        Kitsap County      5551.189119            7953.302293
3020      Kittitas County      5602.084121                    NaN
3021     Klickitat County      5817.717226                    NaN
3022         Lewis County      7605.310948                    NaN
3023       Lincoln County      5811.755316                    NaN
3024         Mason County      7449.845512                    NaN
3025      Okanogan County      7480.503630                    NaN
3026       Pacific County      9258.539903                    NaN
3027  Pend Oreille County      8030.904683                    NaN
3028        Pierce County      6479.917864            8972.455460
3029      San Juan County      4778.722063                    NaN
3030        Skagit County      6292.164238                    NaN
3031      Skamania County      6022.002716                    NaN
3032     Snohomish County      5337.853796            6297.906241
3033       Spokane County      6900.572608           10446.375104
3034       Stevens County      6477.209900                    NaN
3035      Thurston County      5550.574185            6849.219417
3036     Wahkiakum County      5668.140659                    NaN
3037   Walla Walla County      6237.767503                    NaN
3038       Whatcom County      5205.182073           10266.196668
3039       Whitman County      4607.121988                    NaN
3040        Yakima County      7349.331475            8262.622768

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
3001                       NaN                    NaN             0.139020
3002               4901.646713            8259.543361             0.238821
3003                       NaN                    NaN             0.136330
3004               4961.495966            6075.614727             0.131353
3005               3615.114073            5770.601904             0.141343
3006               6549.593245            7256.137097             0.136336
3007               3828.903881            5628.077510             0.122860
3008                       NaN                    NaN             0.155825
3009               5743.440021            8679.201626             0.151453
3010               2834.285346            6003.780923             0.151055
3011                       NaN                    NaN             0.178204
3012               3516.745741            5515.597566             0.192443
3013                       NaN                    NaN             0.135236
3014               5072.999948            7616.073490             0.201039
3015               6827.340052            8955.919958             0.159975
3016               4153.084010            6156.042050             0.121983
3017                       NaN                    NaN             0.121020
3018               3894.303021            4417.842437             0.109505
3019               4520.333378            5466.885095             0.109675
3020                       NaN                    NaN             0.130854
3021                       NaN                    NaN             0.149926
3022               5093.474543            7922.348261             0.142096
3023                       NaN                    NaN             0.139678
3024               7977.642698            6869.495755             0.157164
3025               4502.896173            7015.887383             0.193091
3026                       NaN                    NaN             0.182518
3027                       NaN                    NaN             0.159213
3028               4769.064876            6345.877874             0.130008
3029                       NaN                    NaN             0.105042
3030               4658.063204            6370.518992             0.141875
3031                       NaN                    NaN             0.143169
3032               3812.017787            5702.342672             0.118657
3033               5433.833409            6844.536801             0.122097
3034                       NaN                    NaN             0.173233
3035               3668.731138            5704.473778             0.123681
3036                       NaN                    NaN             0.148130
3037               5025.589593            6551.429771             0.148135
3038               3693.951130            4855.689597             0.138248
3039                       NaN                    NaN             0.149802
3040               5146.368078            8217.710971             0.211565

      ...  male_population_18_44  male_population_45_64  male_population_65  \
3001  ...                    NaN                    NaN                 NaN
3002  ...                    NaN                    NaN                 NaN
3003  ...                    NaN                    NaN                 NaN
3004  ...                    NaN                    NaN                 NaN
3005  ...                    NaN                    NaN                 NaN
3006  ...                    NaN                    NaN                 NaN
3007  ...                    NaN                    NaN                 NaN
3008  ...                    NaN                    NaN                 NaN
3009  ...                    NaN                    NaN                 NaN
3010  ...                    NaN                    NaN                 NaN
3011  ...                    NaN                    NaN                 NaN
3012  ...                    NaN                    NaN                 NaN
3013  ...                    NaN                    NaN                 NaN
3014  ...                    NaN                    NaN                 NaN
3015  ...                    NaN                    NaN                 NaN
3016  ...                    NaN                    NaN                 NaN
3017  ...                    NaN                    NaN                 NaN
3018  ...                    NaN                    NaN                 NaN
3019  ...                    NaN                    NaN                 NaN
3020  ...                    NaN                    NaN                 NaN
3021  ...                    NaN                    NaN                 NaN
3022  ...                    NaN                    NaN                 NaN
3023  ...                    NaN                    NaN                 NaN
3024  ...                    NaN                    NaN                 NaN
3025  ...                    NaN                    NaN                 NaN
3026  ...                    NaN                    NaN                 NaN
3027  ...                    NaN                    NaN                 NaN
3028  ...                    NaN                    NaN                 NaN
3029  ...                    NaN                    NaN                 NaN
3030  ...                    NaN                    NaN                 NaN
3031  ...                    NaN                    NaN                 NaN
3032  ...                    NaN                    NaN                 NaN
3033  ...                    NaN                    NaN                 NaN
3034  ...                    NaN                    NaN                 NaN
3035  ...                    NaN                    NaN                 NaN
3036  ...                    NaN                    NaN                 NaN
3037  ...                    NaN                    NaN                 NaN
3038  ...                    NaN                    NaN                 NaN
3039  ...                    NaN                    NaN                 NaN
3040  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
3001                    NaN                     NaN                      NaN
3002                    NaN                     NaN                      NaN
3003                    NaN                     NaN                      NaN
3004                    NaN                     NaN                      NaN
3005                    NaN                     NaN                      NaN
3006                    NaN                     NaN                      NaN
3007                    NaN                     NaN                      NaN
3008                    NaN                     NaN                      NaN
3009                    NaN                     NaN                      NaN
3010                    NaN                     NaN                      NaN
3011                    NaN                     NaN                      NaN
3012                    NaN                     NaN                      NaN
3013                    NaN                     NaN                      NaN
3014                    NaN                     NaN                      NaN
3015                    NaN                     NaN                      NaN
3016                    NaN                     NaN                      NaN
3017                    NaN                     NaN                      NaN
3018                    NaN                     NaN                      NaN
3019                    NaN                     NaN                      NaN
3020                    NaN                     NaN                      NaN
3021                    NaN                     NaN                      NaN
3022                    NaN                     NaN                      NaN
3023                    NaN                     NaN                      NaN
3024                    NaN                     NaN                      NaN
3025                    NaN                     NaN                      NaN
3026                    NaN                     NaN                      NaN
3027                    NaN                     NaN                      NaN
3028                    NaN                     NaN                      NaN
3029                    NaN                     NaN                      NaN
3030                    NaN                     NaN                      NaN
3031                    NaN                     NaN                      NaN
3032                    NaN                     NaN                      NaN
3033                    NaN                     NaN                      NaN
3034                    NaN                     NaN                      NaN
3035                    NaN                     NaN                      NaN
3036                    NaN                     NaN                      NaN
3037                    NaN                     NaN                      NaN
3038                    NaN                     NaN                      NaN
3039                    NaN                     NaN                      NaN
3040                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
3001                      NaN                   NaN                      NaN
3002                      NaN                   NaN                      NaN
3003                      NaN                   NaN                      NaN
3004                      NaN                   NaN                      NaN
3005                      NaN                   NaN                      NaN
3006                      NaN                   NaN                      NaN
3007                      NaN                   NaN                      NaN
3008                      NaN                   NaN                      NaN
3009                      NaN                   NaN                      NaN
3010                      NaN                   NaN                      NaN
3011                      NaN                   NaN                      NaN
3012                      NaN                   NaN                      NaN
3013                      NaN                   NaN                      NaN
3014                      NaN                   NaN                      NaN
3015                      NaN                   NaN                      NaN
3016                      NaN                   NaN                      NaN
3017                      NaN                   NaN                      NaN
3018                      NaN                   NaN                      NaN
3019                      NaN                   NaN                      NaN
3020                      NaN                   NaN                      NaN
3021                      NaN                   NaN                      NaN
3022                      NaN                   NaN                      NaN
3023                      NaN                   NaN                      NaN
3024                      NaN                   NaN                      NaN
3025                      NaN                   NaN                      NaN
3026                      NaN                   NaN                      NaN
3027                      NaN                   NaN                      NaN
3028                      NaN                   NaN                      NaN
3029                      NaN                   NaN                      NaN
3030                      NaN                   NaN                      NaN
3031                      NaN                   NaN                      NaN
3032                      NaN                   NaN                      NaN
3033                      NaN                   NaN                      NaN
3034                      NaN                   NaN                      NaN
3035                      NaN                   NaN                      NaN
3036                      NaN                   NaN                      NaN
3037                      NaN                   NaN                      NaN
3038                      NaN                   NaN                      NaN
3039                      NaN                   NaN                      NaN
3040                      NaN                   NaN                      NaN

      population_growth
3001                NaN
3002                NaN
3003                NaN
3004                NaN
3005                NaN
3006                NaN
3007                NaN
3008                NaN
3009                NaN
3010                NaN
3011                NaN
3012                NaN
3013                NaN
3014                NaN
3015                NaN
3016                NaN
3017                NaN
3018                NaN
3019                NaN
3020                NaN
3021                NaN
3022                NaN
3023                NaN
3024                NaN
3025                NaN
3026                NaN
3027                NaN
3028                NaN
3029                NaN
3030                NaN
3031                NaN
3032                NaN
3033                NaN
3034                NaN
3035                NaN
3036                NaN
3037                NaN
3038                NaN
3039                NaN
3040                NaN

[40 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of WV       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
3041               54                 0              54000                 WV
3042               54                 1              54001                 WV
3043               54                 3              54003                 WV
3044               54                 5              54005                 WV
3045               54                 7              54007                 WV
3046               54                 9              54009                 WV
3047               54                11              54011                 WV
3048               54                13              54013                 WV
3049               54                15              54015                 WV
3050               54                17              54017                 WV
3051               54                19              54019                 WV
3052               54                21              54021                 WV
3053               54                23              54023                 WV
3054               54                25              54025                 WV
3055               54                27              54027                 WV
3056               54                29              54029                 WV
3057               54                31              54031                 WV
3058               54                33              54033                 WV
3059               54                35              54035                 WV
3060               54                37              54037                 WV
3061               54                39              54039                 WV
3062               54                41              54041                 WV
3063               54                43              54043                 WV
3064               54                45              54045                 WV
3065               54                47              54047                 WV
3066               54                49              54049                 WV
3067               54                51              54051                 WV
3068               54                53              54053                 WV
3069               54                55              54055                 WV
3070               54                57              54057                 WV
3071               54                59              54059                 WV
3072               54                61              54061                 WV
3073               54                63              54063                 WV
3074               54                65              54065                 WV
3075               54                67              54067                 WV
3076               54                69              54069                 WV
3077               54                71              54071                 WV
3078               54                73              54073                 WV
3079               54                75              54075                 WV
3080               54                77              54077                 WV
3081               54                79              54079                 WV
3082               54                81              54081                 WV
3083               54                83              54083                 WV
3084               54                85              54085                 WV
3085               54                87              54087                 WV
3086               54                89              54089                 WV
3087               54                91              54091                 WV
3088               54                93              54093                 WV
3089               54                95              54095                 WV
3090               54                97              54097                 WV
3091               54                99              54099                 WV
3092               54               101              54101                 WV
3093               54               103              54103                 WV
3094               54               105              54105                 WV
3095               54               107              54107                 WV
3096               54               109              54109                 WV

                   name  premature_death  premature_death_black  \
3041      West Virginia     10472.515993                    NaN
3042     Barbour County      9319.736534                    NaN
3043    Berkeley County      9646.799963           12637.269999
3044       Boone County     12792.844839                    NaN
3045     Braxton County      9530.786003                    NaN
3046      Brooke County      9019.729365                    NaN
3047      Cabell County     14698.993244           23876.211696
3048     Calhoun County      9440.842440                    NaN
3049        Clay County     10431.251848                    NaN
3050   Doddridge County      7065.658480                    NaN
3051     Fayette County     12764.200568           13289.552304
3052      Gilmer County      7817.500272                    NaN
3053       Grant County      7371.855543                    NaN
3054  Greenbrier County      9549.405722           13366.873645
3055   Hampshire County     10535.049738                    NaN
3056     Hancock County     10821.818460                    NaN
3057       Hardy County      8792.150759                    NaN
3058    Harrison County      9699.917391                    NaN
3059     Jackson County      9572.626059                    NaN
3060   Jefferson County      7196.657206            9165.366382
3061     Kanawha County     11844.101793           14123.247837
3062       Lewis County     12586.056101                    NaN
3063     Lincoln County     12944.254640                    NaN
3064       Logan County     15681.885044           28271.761274
3065    McDowell County     18571.489514           17981.981488
3066      Marion County      8456.089253           16688.450660
3067    Marshall County      7271.289612                    NaN
3068       Mason County     11365.198541                    NaN
3069      Mercer County     13220.429277           14120.750659
3070     Mineral County      7984.229287                    NaN
3071       Mingo County     14857.550970                    NaN
3072  Monongalia County      6490.691679            8500.234630
3073      Monroe County      9416.799195                    NaN
3074      Morgan County     11410.113804                    NaN
3075    Nicholas County     11708.313003                    NaN
3076        Ohio County      8731.875988           24453.902361
3077   Pendleton County      9170.544419                    NaN
3078   Pleasants County      8798.155961                    NaN
3079  Pocahontas County      9111.158131                    NaN
3080     Preston County      8111.754147                    NaN
3081      Putnam County      7956.661458                    NaN
3082     Raleigh County     12773.993648           10280.458026
3083    Randolph County      8809.740910                    NaN
3084     Ritchie County      8395.174272                    NaN
3085       Roane County     11834.520845                    NaN
3086     Summers County     12326.765291                    NaN
3087      Taylor County      9201.136686                    NaN
3088      Tucker County      7719.178227                    NaN
3089       Tyler County      9213.187470                    NaN
3090      Upshur County      8823.455939                    NaN
3091       Wayne County     12244.898845                    NaN
3092     Webster County     11532.560283                    NaN
3093      Wetzel County     10336.425603                    NaN
3094        Wirt County      7625.284009                    NaN
3095        Wood County      9923.013957                    NaN
3096     Wyoming County     13638.602493                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
3041                       NaN                    NaN             0.240982
3042                       NaN                    NaN             0.244610
3043                       NaN            9715.025190             0.220687
3044                       NaN                    NaN             0.268855
3045                       NaN                    NaN             0.220708
3046                       NaN                    NaN             0.184714
3047                       NaN           14279.198332             0.219220
3048                       NaN                    NaN             0.227216
3049                       NaN                    NaN             0.234961
3050                       NaN                    NaN             0.210632
3051                       NaN           12834.222617             0.262603
3052                       NaN                    NaN             0.260484
3053                       NaN                    NaN             0.222010
3054                       NaN            9277.721907             0.222772
3055                       NaN                    NaN             0.217889
3056                       NaN                    NaN             0.189952
3057                       NaN                    NaN             0.205741
3058                       NaN                    NaN             0.203082
3059                       NaN                    NaN             0.196099
3060                       NaN            7355.553136             0.182245
3061                       NaN           11763.882654             0.210493
3062                       NaN                    NaN             0.230796
3063                       NaN                    NaN             0.266836
3064                       NaN           15493.703109             0.277993
3065                       NaN           18835.861554             0.331894
3066                       NaN            8281.863218             0.207859
3067                       NaN                    NaN             0.199391
3068                       NaN                    NaN             0.238031
3069                       NaN           13345.317284             0.254930
3070                       NaN                    NaN             0.226324
3071                       NaN                    NaN             0.296787
3072                       NaN            6641.399210             0.180065
3073                       NaN                    NaN             0.219469
3074                       NaN                    NaN             0.197342
3075                       NaN                    NaN             0.227196
3076                       NaN            8083.734823             0.184792
3077                       NaN                    NaN             0.218141
3078                       NaN                    NaN             0.226578
3079                       NaN                    NaN             0.209822
3080                       NaN                    NaN             0.202835
3081                       NaN                    NaN             0.180896
3082                       NaN           13133.459916             0.245471
3083                       NaN                    NaN             0.215039
3084                       NaN                    NaN             0.220518
3085                       NaN                    NaN             0.232740
3086                       NaN                    NaN             0.252798
3087                       NaN                    NaN             0.219146
3088                       NaN                    NaN             0.208106
3089                       NaN                    NaN             0.209631
3090                       NaN                    NaN             0.233679
3091                       NaN                    NaN             0.247214
3092                       NaN                    NaN             0.242691
3093                       NaN                    NaN             0.224203
3094                       NaN                    NaN             0.228446
3095                       NaN                    NaN             0.188864
3096                       NaN                    NaN             0.265777

      ...  male_population_18_44  male_population_45_64  male_population_65  \
3041  ...                    NaN                    NaN                 NaN
3042  ...                    NaN                    NaN                 NaN
3043  ...                    NaN                    NaN                 NaN
3044  ...                    NaN                    NaN                 NaN
3045  ...                    NaN                    NaN                 NaN
3046  ...                    NaN                    NaN                 NaN
3047  ...                    NaN                    NaN                 NaN
3048  ...                    NaN                    NaN                 NaN
3049  ...                    NaN                    NaN                 NaN
3050  ...                    NaN                    NaN                 NaN
3051  ...                    NaN                    NaN                 NaN
3052  ...                    NaN                    NaN                 NaN
3053  ...                    NaN                    NaN                 NaN
3054  ...                    NaN                    NaN                 NaN
3055  ...                    NaN                    NaN                 NaN
3056  ...                    NaN                    NaN                 NaN
3057  ...                    NaN                    NaN                 NaN
3058  ...                    NaN                    NaN                 NaN
3059  ...                    NaN                    NaN                 NaN
3060  ...                    NaN                    NaN                 NaN
3061  ...                    NaN                    NaN                 NaN
3062  ...                    NaN                    NaN                 NaN
3063  ...                    NaN                    NaN                 NaN
3064  ...                    NaN                    NaN                 NaN
3065  ...                    NaN                    NaN                 NaN
3066  ...                    NaN                    NaN                 NaN
3067  ...                    NaN                    NaN                 NaN
3068  ...                    NaN                    NaN                 NaN
3069  ...                    NaN                    NaN                 NaN
3070  ...                    NaN                    NaN                 NaN
3071  ...                    NaN                    NaN                 NaN
3072  ...                    NaN                    NaN                 NaN
3073  ...                    NaN                    NaN                 NaN
3074  ...                    NaN                    NaN                 NaN
3075  ...                    NaN                    NaN                 NaN
3076  ...                    NaN                    NaN                 NaN
3077  ...                    NaN                    NaN                 NaN
3078  ...                    NaN                    NaN                 NaN
3079  ...                    NaN                    NaN                 NaN
3080  ...                    NaN                    NaN                 NaN
3081  ...                    NaN                    NaN                 NaN
3082  ...                    NaN                    NaN                 NaN
3083  ...                    NaN                    NaN                 NaN
3084  ...                    NaN                    NaN                 NaN
3085  ...                    NaN                    NaN                 NaN
3086  ...                    NaN                    NaN                 NaN
3087  ...                    NaN                    NaN                 NaN
3088  ...                    NaN                    NaN                 NaN
3089  ...                    NaN                    NaN                 NaN
3090  ...                    NaN                    NaN                 NaN
3091  ...                    NaN                    NaN                 NaN
3092  ...                    NaN                    NaN                 NaN
3093  ...                    NaN                    NaN                 NaN
3094  ...                    NaN                    NaN                 NaN
3095  ...                    NaN                    NaN                 NaN
3096  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
3041                    NaN                     NaN                      NaN
3042                    NaN                     NaN                      NaN
3043                    NaN                     NaN                      NaN
3044                    NaN                     NaN                      NaN
3045                    NaN                     NaN                      NaN
3046                    NaN                     NaN                      NaN
3047                    NaN                     NaN                      NaN
3048                    NaN                     NaN                      NaN
3049                    NaN                     NaN                      NaN
3050                    NaN                     NaN                      NaN
3051                    NaN                     NaN                      NaN
3052                    NaN                     NaN                      NaN
3053                    NaN                     NaN                      NaN
3054                    NaN                     NaN                      NaN
3055                    NaN                     NaN                      NaN
3056                    NaN                     NaN                      NaN
3057                    NaN                     NaN                      NaN
3058                    NaN                     NaN                      NaN
3059                    NaN                     NaN                      NaN
3060                    NaN                     NaN                      NaN
3061                    NaN                     NaN                      NaN
3062                    NaN                     NaN                      NaN
3063                    NaN                     NaN                      NaN
3064                    NaN                     NaN                      NaN
3065                    NaN                     NaN                      NaN
3066                    NaN                     NaN                      NaN
3067                    NaN                     NaN                      NaN
3068                    NaN                     NaN                      NaN
3069                    NaN                     NaN                      NaN
3070                    NaN                     NaN                      NaN
3071                    NaN                     NaN                      NaN
3072                    NaN                     NaN                      NaN
3073                    NaN                     NaN                      NaN
3074                    NaN                     NaN                      NaN
3075                    NaN                     NaN                      NaN
3076                    NaN                     NaN                      NaN
3077                    NaN                     NaN                      NaN
3078                    NaN                     NaN                      NaN
3079                    NaN                     NaN                      NaN
3080                    NaN                     NaN                      NaN
3081                    NaN                     NaN                      NaN

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of WI       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
3097               55                 0              55000                 WI
3098               55                 1              55001                 WI
3099               55                 3              55003                 WI
3100               55                 5              55005                 WI
3101               55                 7              55007                 WI
...               ...               ...                ...                ...
3165               55               133              55133                 WI
3166               55               135              55135                 WI
3167               55               137              55137                 WI
3168               55               139              55139                 WI
3169               55               141              55141                 WI

                  name  premature_death  premature_death_black  \
3097         Wisconsin      6291.219118                    NaN
3098      Adams County      7323.797383                    NaN
3099    Ashland County      8571.488657                    NaN
3100     Barron County      5969.342882                    NaN
3101   Bayfield County      7321.943173                    NaN
...                ...              ...                    ...
3165   Waukesha County      4632.561237            6801.244750
3166    Waupaca County      6999.337639                    NaN
3167   Waushara County      6262.724414                    NaN
3168  Winnebago County      5780.150969           12173.708686
3169       Wood County      6800.043824                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
3097                       NaN                    NaN             0.153768
3098                       NaN                    NaN             0.151499
3099                       NaN                    NaN             0.158171
3100                       NaN                    NaN             0.135478
3101                       NaN                    NaN             0.137904
...                        ...                    ...                  ...
3165               3416.916562            4761.457365             0.107912
3166                       NaN                    NaN             0.130227
3167                       NaN                    NaN             0.145003
3168               5474.620371            5576.520235             0.119875
3169                       NaN                    NaN             0.120099

      ...  male_population_18_44  male_population_45_64  male_population_65  \
3097  ...              1004204.0               781937.0            432330.0
3098  ...                 3092.0                 3556.0              2901.0
3099  ...                 2548.0                 2257.0              1503.0
3100  ...                 6891.0                 6535.0              4764.0
3101  ...                 1766.0                 2676.0              2118.0
...   ...                    ...                    ...                 ...
3165  ...                60499.0                58476.0             31968.0
3166  ...                 7458.0                 7643.0              6113.0
3167  ...                 3842.0                 4092.0              2793.0
3168  ...                31744.0                23005.0             12140.0
3169  ...                11213.0                10613.0              6855.0

      total_male_population  female_population_0_17  female_population_18_44  \
3097              2874471.0                626656.0                 969103.0
3098                10978.0                  1351.0                   2027.0
3099                 8048.0                  1670.0                   2338.0
3100                23085.0                  4690.0                   6327.0
3101                 7825.0                  1109.0                   1545.0
...                     ...                     ...                      ...
3165               194680.0                 41487.0                  59795.0
3166                26486.0                  4945.0                   7077.0
3167                12923.0                  2180.0                   2932.0
3168                85436.0                 17969.0                  28909.0
3169                36667.0                  7601.0                  10912.0

      female_population_45_64  female_population_65  total_female_population  \
3097                 789101.0              519498.0                2904358.0
3098                   3301.0                2853.0                   9532.0
3099                   2228.0                1522.0                   7758.0
3100                   6427.0                5506.0                  22950.0
3101                   2563.0                2062.0                   7279.0
...                       ...                   ...                      ...
3165                  61147.0               40063.0                 202492.0
3166                   7549.0                5980.0                  25551.0
3167                   3599.0                2842.0                  11553.0
3168                  22243.0               14927.0                  84048.0
3169                  10989.0                8345.0                  37847.0

      population_growth
3097           0.016150
3098          -0.017485
3099          -0.021724
3100           0.003597
3101           0.005994
...                 ...
3165           0.018674
3166          -0.007117
3167          -0.000816
3168           0.014911
3169          -0.003144

[73 rows x 155 columns]

<ipython-input-30-d13461fd7d6f>:12: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  [~((df[df.state_abbreviation==state][indep_features_list]< (Q1 - 1.5 * IQR)) |\
<ipython-input-30-d13461fd7d6f>:13: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  (df[df.state_abbreviation==state][indep_features_list] > (Q3 + 1.5 * IQR))).any(axis=1)]
/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

state of WY       state_fips_code  county_fips_code  5_digit_fips_code state_abbreviation  \
3170               56                 0              56000                 WY
3171               56                 1              56001                 WY
3172               56                 3              56003                 WY
3173               56                 5              56005                 WY
3174               56                 7              56007                 WY
3175               56                 9              56009                 WY
3176               56                11              56011                 WY
3177               56                13              56013                 WY
3178               56                15              56015                 WY
3179               56                17              56017                 WY
3180               56                19              56019                 WY
3181               56                21              56021                 WY
3182               56                23              56023                 WY
3183               56                25              56025                 WY
3184               56                27              56027                 WY
3185               56                29              56029                 WY
3186               56                31              56031                 WY
3187               56                33              56033                 WY
3188               56                35              56035                 WY
3189               56                37              56037                 WY
3190               56                39              56039                 WY
3191               56                41              56041                 WY
3192               56                43              56043                 WY
3193               56                45              56045                 WY

                    name  premature_death  premature_death_black  \
3170             Wyoming      7307.824667                    NaN
3171       Albany County      5209.847795                    NaN
3172     Big Horn County      8077.317011                    NaN
3173     Campbell County      6213.935125                    NaN
3174       Carbon County      9836.062960                    NaN
3175     Converse County      8589.686689                    NaN
3176        Crook County      5494.823773                    NaN
3177      Fremont County     12248.191891                    NaN
3178       Goshen County      6820.870689                    NaN
3179  Hot Springs County     12173.116982                    NaN
3180      Johnson County      7224.571317                    NaN
3181      Laramie County      7533.320944            7445.913422
3182      Lincoln County      5639.056128                    NaN
3183      Natrona County      7905.500700                    NaN
3184     Niobrara County      4406.655173                    NaN
3185         Park County      6161.160922                    NaN
3186       Platte County      6147.123193                    NaN
3187     Sheridan County      8365.102601                    NaN
3188     Sublette County      5657.772195                    NaN
3189   Sweetwater County      7497.439952                    NaN
3190        Teton County      3786.128226                    NaN
3191        Uinta County      7790.302043                    NaN
3192     Washakie County      5504.650970                    NaN
3193       Weston County      4991.168273                    NaN

      premature_death_hispanic  premature_death_white  poor_or_fair_health  \
3170                       NaN                    NaN             0.151280
3171                       NaN                    NaN             0.160019
3172                       NaN                    NaN             0.149362
3173                       NaN                    NaN             0.117665
3174               8629.378939           10431.175229             0.159288
3175                       NaN                    NaN             0.132786
3176                       NaN                    NaN             0.115095
3177              10033.833830            8643.269951             0.167707
3178                       NaN                    NaN             0.154826
3179                       NaN                    NaN             0.134879
3180                       NaN                    NaN             0.120568
3181               7514.978838            7595.941552             0.145980
3182                       NaN                    NaN             0.121492
3183               5506.036928            8074.232439             0.149370
3184                       NaN                    NaN             0.146530
3185                       NaN                    NaN             0.124377
3186                       NaN                    NaN             0.155697
3187                       NaN                    NaN             0.123433
3188                       NaN                    NaN             0.118276
3189               6413.215910            7834.050381             0.153772
3190                       NaN                    NaN             0.121817
3191                       NaN                    NaN             0.158858
3192                       NaN                    NaN             0.161261
3193                       NaN                    NaN             0.132375

      ...  male_population_18_44  male_population_45_64  male_population_65  \
3170  ...                    NaN                    NaN                 NaN
3171  ...                    NaN                    NaN                 NaN
3172  ...                    NaN                    NaN                 NaN
3173  ...                    NaN                    NaN                 NaN
3174  ...                    NaN                    NaN                 NaN
3175  ...                    NaN                    NaN                 NaN
3176  ...                    NaN                    NaN                 NaN
3177  ...                    NaN                    NaN                 NaN
3178  ...                    NaN                    NaN                 NaN
3179  ...                    NaN                    NaN                 NaN
3180  ...                    NaN                    NaN                 NaN
3181  ...                    NaN                    NaN                 NaN
3182  ...                    NaN                    NaN                 NaN
3183  ...                    NaN                    NaN                 NaN
3184  ...                    NaN                    NaN                 NaN
3185  ...                    NaN                    NaN                 NaN
3186  ...                    NaN                    NaN                 NaN
3187  ...                    NaN                    NaN                 NaN
3188  ...                    NaN                    NaN                 NaN
3189  ...                    NaN                    NaN                 NaN
3190  ...                    NaN                    NaN                 NaN
3191  ...                    NaN                    NaN                 NaN
3192  ...                    NaN                    NaN                 NaN
3193  ...                    NaN                    NaN                 NaN

      total_male_population  female_population_0_17  female_population_18_44  \
3170                    NaN                     NaN                      NaN
3171                    NaN                     NaN                      NaN
3172                    NaN                     NaN                      NaN
3173                    NaN                     NaN                      NaN
3174                    NaN                     NaN                      NaN
3175                    NaN                     NaN                      NaN
3176                    NaN                     NaN                      NaN
3177                    NaN                     NaN                      NaN
3178                    NaN                     NaN                      NaN
3179                    NaN                     NaN                      NaN
3180                    NaN                     NaN                      NaN
3181                    NaN                     NaN                      NaN
3182                    NaN                     NaN                      NaN
3183                    NaN                     NaN                      NaN
3184                    NaN                     NaN                      NaN
3185                    NaN                     NaN                      NaN
3186                    NaN                     NaN                      NaN
3187                    NaN                     NaN                      NaN
3188                    NaN                     NaN                      NaN
3189                    NaN                     NaN                      NaN
3190                    NaN                     NaN                      NaN
3191                    NaN                     NaN                      NaN
3192                    NaN                     NaN                      NaN
3193                    NaN                     NaN                      NaN

      female_population_45_64  female_population_65  total_female_population  \
3170                      NaN                   NaN                      NaN
3171                      NaN                   NaN                      NaN
3172                      NaN                   NaN                      NaN
3173                      NaN                   NaN                      NaN
3174                      NaN                   NaN                      NaN
3175                      NaN                   NaN                      NaN
3176                      NaN                   NaN                      NaN
3177                      NaN                   NaN                      NaN
3178                      NaN                   NaN                      NaN
3179                      NaN                   NaN                      NaN
3180                      NaN                   NaN                      NaN
3181                      NaN                   NaN                      NaN
3182                      NaN                   NaN                      NaN
3183                      NaN                   NaN                      NaN
3184                      NaN                   NaN                      NaN
3185                      NaN                   NaN                      NaN
3186                      NaN                   NaN                      NaN
3187                      NaN                   NaN                      NaN
3188                      NaN                   NaN                      NaN
3189                      NaN                   NaN                      NaN
3190                      NaN                   NaN                      NaN
3191                      NaN                   NaN                      NaN
3192                      NaN                   NaN                      NaN
3193                      NaN                   NaN                      NaN

      population_growth
3170                NaN
3171                NaN
3172                NaN
3173                NaN
3174                NaN
3175                NaN
3176                NaN
3177                NaN
3178                NaN
3179                NaN
3180                NaN
3181                NaN
3182                NaN
3183                NaN
3184                NaN
3185                NaN
3186                NaN
3187                NaN
3188                NaN
3189                NaN
3190                NaN
3191                NaN
3192                NaN
3193                NaN

[24 rows x 155 columns]

In [31]:
df

,state_fips_code,county_fips_code,5_digit_fips_code,state_abbreviation,name,premature_death,premature_death_black,premature_death_hispanic,premature_death_white,poor_or_fair_health,...,male_population_18_44,male_population_45_64,male_population_65,total_male_population,female_population_0_17,female_population_18_44,female_population_45_64,female_population_65,total_female_population,population_growth
0,0,0,0,US,United States,6900.630354,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,1000,AL,Alabama,9917.232898,NaN,NaN,NaN,0.214024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1001,AL,Autauga County,8824.057123,10471.252986,NaN,8706.658832,0.184111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,1003,AL,Baldwin County,7224.632160,10042.472874,3086.605695,7277.780727,0.180605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,1005,AL,Barbour County,9586.165037,11332.562909,NaN,7309.636719,0.257734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,56,37,56037,WY,Sweetwater County,7497.439952,NaN,6413.215910,7834.050381,0.153772,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3190,56,39,56039,WY,Teton County,3786.128226,NaN,NaN,NaN,0.121817,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3191,56,41,56041,WY,Uinta County,7790.302043,NaN,NaN,NaN,0.158858,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3192,56,43,56043,WY,Washakie County,5504.650970,NaN,NaN,NaN,0.161261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3193,56,45,56045,WY,Weston County,4991.168273,NaN,NaN,NaN,0.132375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.state_abbreviation.unique()

array(['US', nan, 'AL', 'AK', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
       'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NH', 'NJ', 'NM', 'NY', 'NC',
       'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT',
       'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [ ]:
# Find and filter out univariate outliers
z_scores = scipy.stats.zscore(df)
abs_z = numpy.abs(z_scores)
fltr = (abs_z < 3).all(axis=1)

df[fltr]

In [ ]:
# Find univariate outliers for features using boxplots 
indep_features_df = df.drop(columns=['state_fips_code',
 'county_fips_code',
 '5_digit_fips_code',
 'name', 'uninsured'])

def create_boxplot(state, column, df):
    sns.boxplot(x=df[df.state_abbreviation==state][column], orient="h")
    y = np.arange(1)
    
    sns.despine(left=True)
    plt.yticks(y, " ")
    plt.xlabel(column)
    
    plt.title(("State of {0}: {1} Boxplot").format(state, column))
    
    
    plt.savefig(('EDA_Visualizations/Boxplots/{0}_{1}_boxplot.jpg').format(state, column))
    plt.close()
    
for state in indep_features_df.state_abbreviation.unique():
    if state != 'US':
        for column in indep_features_df.columns:
            if column != 'state_abbreviation':
                create_boxplot(state, column, indep_features_df)

In [ ]:
# Find Outliers 
for state in df.state_abbreviation.unique().tolist():
    temp_df = df[df.state_abbreviation==state]['uninsured']
    Q1 = temp_df.quantile(0.25)
    Q3 = temp_df.quantile(0.75)
    IQR = Q3 - Q1
    
    temp_df_out = temp_df[~((temp_df < (Q1 - 1.5 * IQR)) |(temp_df > (Q3 + 1.5 * IQR))).any(axis=1)]
    df[df.state_abbreviation==state] = temp_df_out

#df = df.dropna(subset='state_abbreviation')
    
df

In [ ]:
df.groupby('state_abbreviation').count()

In [ ]:
# Looking at collinearity among independent features